.TH BST\-EXPORT\-METASCHEMA "1" "February 2026" "" "User Commands"
.SH NAME
.B bst\ export\-metaschema
\(en Export BIDS schema to JSON document
.SH SYNOPSIS
.B bst\ export\-metaschema
.RI [ OPTIONS ]
.SH OPTIONS
.TP
.B \-\-output\ \fITEXT
.TP
.B \-h\fR, \fB\-\-help
Show a help message and exit
.SH "SEE ALSO"
.BR bst\-export (1),
.BR bst\-pre\-receive\-hook (1)
.P
.BR bst (1)
