%global source0_hash 49e6bdbbe5d13015b21a49a778a29ae3cee9c450c3154e1648aed670d57fe5ba

# Generated by rust2rpm 27
%bcond check 1
%global debug_package %{nil}

%global crate qapi-spec

Name:           rust-qapi-spec
Version:        0.3.2
Release:        %autorelease
Summary:        QEMU QAPI common types

License:        MIT
URL:            https://crates.io/crates/qapi-spec
Source:         %{crates_source}
# https://github.com/arcnmx/qapi-rs/pull/26
Source1:        https://github.com/arcnmx/qapi-rs/raw/COPYING

BuildRequires:  cargo-rpm-macros >= 24

%global _description %{expand:
QEMU QAPI common types.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
%license %{crate_instdir}/COPYING
%doc %{crate_instdir}/README.md
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
test "%{source0_hash}" = "none" || { f="%{SOURCE0}"; test -f "$f" || { echo "oreon: missing Source0 $f" >&2; exit 1; }; h=$(sha256sum "$f" | awk '{print $1}'); test "$h" = "%{source0_hash}" || { echo "oreon: Source0 hash mismatch" >&2; exit 1; }; }

%autosetup -n %{crate}-%{version} -p1
cp -pav %{SOURCE1} .
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
%autochangelog
