%global source0_hash 969afcdc518e7b9d57a0f8cdeda3fe6b824fafdd34475eb24a56be4f0cb805d3

# Generated by go2rpm
%bcond check 0

%global debug_package %{nil}

# https://github.com/nwidger/jsoncolor
%global goipath         github.com/nwidger/jsoncolor
Version:                0.3.2

%gometa

%global common_description %{expand:
jsoncolor is a drop-in replacement for encoding/json's Marshal and MarshalIndent
functions which produce colorized output using fatih's color package.}

%global golicenses      LICENSE
%global godocs          README.md

Name:           %{goname}
Release:        %autorelease
Summary:        Colorized JSON output for Go

License:        MIT
URL:            %{gourl}
Source0:        %{gosource}

BuildRequires:  golang(github.com/fatih/color)

%description
%{common_description}

%gopkg

%prep
test "%{source0_hash}" = "none" || { f="%{SOURCE0}"; test -f "$f" || { echo "oreon: missing Source0 $f" >&2; exit 1; }; h=$(sha256sum "$f" | awk '{print $1}'); test "$h" = "%{source0_hash}" || { echo "oreon: Source0 hash mismatch" >&2; exit 1; }; }

%goprep

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog
%autochangelog
