%global source0_hash 61aef7ceebc7c5cd2cfa6902c4d0be4df3056bf8b776d03005334218a05b460e

# Generated by go2rpm 1.3
%bcond check 0

# https://github.com/kalafut/imohash
%global goipath         github.com/kalafut/imohash
Version:                1.0.2

%gometa

%global common_description %{expand:
Fast hashing for large files.}

%global golicenses      LICENSE
%global godocs          README.md algorithm.md

Name:           %{goname}
Release:        %autorelease
Summary:        Fast hashing for large files

License:        MIT
URL:            %{gourl}
Source0:        %{gosource}

BuildRequires:  golang(github.com/twmb/murmur3)

%if %{with check}
# Tests
BuildRequires:  golang(gopkg.in/tylerb/is.v1)
%endif

%description
%{common_description}

%gopkg

%prep
test "%{source0_hash}" = "none" || { f="%{SOURCE0}"; test -f "$f" || { echo "oreon: missing Source0 $f" >&2; exit 1; }; h=$(sha256sum "$f" | awk '{print $1}'); test "$h" = "%{source0_hash}" || { echo "oreon: Source0 hash mismatch" >&2; exit 1; }; }

%goprep

%build
for cmd in cmd/* ; do
  %gobuild -o %{gobuilddir}/bin/$(basename $cmd) %{goipath}/$cmd
done

%install
%gopkginstall
install -m 0755 -vd                     %{buildroot}%{_bindir}
install -m 0755 -vp %{gobuilddir}/bin/* %{buildroot}%{_bindir}/

%if %{with check}
%check
%gocheck
%endif

%files
%license LICENSE
%doc README.md algorithm.md
%{_bindir}/*

%gopkgfiles

%changelog
%autochangelog
