---
downstream_package_name: jackson-databind
specfile_path: jackson-databind.spec
upstream_package_name: jackson-databind
upstream_project_url: https://github.com/FasterXML/jackson-databind
upstream_tag_template: jackson-databind-{version}

actions:
  post-upstream-clone:
    - "wget https://src.fedoraproject.org/rpms/jackson-databind/raw/main/f/jackson-databind.spec -O jackson-databind.spec"

jobs:
- job: pull_from_upstream
  trigger: release
  dist_git_branches:
    - fedora-rawhide

# We cannot do koji_build/bodhi_update jobs yet as we need to use
# a side-tag and this is no supported yet. We can add them is this
# issue gets resolved: https://github.com/packit/packit/issues/1870
