%global source0_hash 9aad212d014dac439257cc7417810f10d629b4f36c6bb68f69260c29b8f62cd5

# Generated by rust2rpm 28
%bcond check 0
%global debug_package %{nil}

%global crate sval_derive_macros

Name:           rust-sval_derive_macros
Version:        2.20.0
Release:        %autorelease
Summary:        Minimal derive support for `sval`

License:        Apache-2.0 OR MIT
URL:            https://crates.io/crates/sval_derive_macros
Source:         %{crates_source}

BuildRequires:  cargo-rpm-macros >= 24

%global _description %{expand:
Minimal derive support for `sval`}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
%license %{crate_instdir}/LICENSE-APACHE
%license %{crate_instdir}/LICENSE-MIT
%doc %{crate_instdir}/README.md
%{crate_instdir}/

%package     -n %{name}+flatten-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+flatten-devel %{_description}

This package contains library source intended for building other packages which
use the "flatten" feature of the "%{crate}" crate.

%files       -n %{name}+flatten-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+ref-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+ref-devel %{_description}

This package contains library source intended for building other packages which
use the "ref" feature of the "%{crate}" crate.

%files       -n %{name}+ref-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
test "%{source0_hash}" = "none" || { f="%{SOURCE0}"; test -f "$f" || { echo "oreon: missing Source0 $f" >&2; exit 1; }; h=$(sha256sum "$f" | awk '{print $1}'); test "$h" = "%{source0_hash}" || { echo "oreon: Source0 hash mismatch" >&2; exit 1; }; }
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
%autochangelog
