%global source0_hash 0e00243d27a20feb05cf001ae52ddc79831ac70c020f215ba1153ff9270b650a

# Generated by rust2rpm 27
# * disable tests since /dev/kvm is unusable in containerized builds
%bcond check 0
%global debug_package %{nil}

%global crate kvm-ioctls

# compile and run tests only on supported architectures
%global supported_arches aarch64 riscv64 x86_64

Name:           rust-kvm-ioctls
Version:        0.23.0
Release:        %autorelease
Summary:        Safe wrappers over KVM ioctls

License:        Apache-2.0 OR MIT
URL:            https://crates.io/crates/kvm-ioctls
Source:         %{crates_source}

BuildRequires:  cargo-rpm-macros >= 24

%global _description %{expand:
Safe wrappers over KVM ioctls.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
%license %{crate_instdir}/LICENSE-APACHE
%license %{crate_instdir}/LICENSE-MIT
%doc %{crate_instdir}/CHANGELOG.md
%doc %{crate_instdir}/README.md
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
test "%{source0_hash}" = "none" || { f="%{SOURCE0}"; test -f "$f" || { echo "oreon: missing Source0 $f" >&2; exit 1; }; h=$(sha256sum "$f" | awk '{print $1}'); test "$h" = "%{source0_hash}" || { echo "oreon: Source0 hash mismatch" >&2; exit 1; }; }

%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%ifarch %{supported_arches}
%cargo_build
%endif

%install
%cargo_install

%if %{with check}
%ifarch %{supported_arches}
%check
%cargo_test
%endif
%endif

%changelog
%autochangelog
