# Configuration snippet for vdr-tvscraper               -*- sh -*-
#
# Add command line options to pass to the tvscraper plugin to PLUGIN_OPTIONS.
# See /usr/share/doc/vdr-tvscraper/README for info about available options.

PLUGIN_OPTIONS=""
