%global source0_hash 8aa599cf7de733306cf8770f854f8a38e6c819b1ae4296f15e44b1e7c6698f34

# Generated by go2rpm 1.9.0
%bcond check 0
%global debug_package %{nil}

# https://github.com/uber-go/multierr
%global goipath         go.uber.org/multierr
%global forgeurl        https://github.com/uber-go/multierr
Version:                1.11.0

%gometa

%global common_description %{expand:
Combine one or more Go errors together.}

%global golicenses      LICENSE.txt
%global godocs          CHANGELOG.md README.md

Name:           %{goname}
Release:        %autorelease
Summary:        Combine one or more Go errors together

License:        MIT
URL:            %{gourl}
Source:         %{gosource}

%description %{common_description}

%gopkg

%prep
test "%{source0_hash}" = "none" || { f="%{SOURCE0}"; test -f "$f" || { echo "oreon: missing Source0 $f" >&2; exit 1; }; h=$(sha256sum "$f" | awk '{print $1}'); test "$h" = "%{source0_hash}" || { echo "oreon: Source0 hash mismatch" >&2; exit 1; }; }

%goprep
%autopatch -p1

%generate_buildrequires
%go_generate_buildrequires

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog
%autochangelog
