%global source0_hash e32a70cf75e5846d53a673923498228bbec6a8624708a9ea5645f075d6276122

# Generated by rust2rpm 28
%bcond check 0
%global debug_package %{nil}

%global crate libc

Name:           rust-libc0.1
Version:        0.1.12
Release:        %autorelease
Summary:        A library for types and bindings to native C functions often found in...

License:        MIT OR Apache-2.0
URL:            https://crates.io/crates/libc
Source:         %{crates_source}
# Manually created patch for downstream crate metadata changes
# * remove reference to readme file that is not included in published crates
Patch:          libc-fix-metadata.diff

BuildRequires:  cargo-rpm-macros >= 24

%global _description %{expand:
A library for types and bindings to native C functions often found in libc or
other common platform libraries.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+cargo-build-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+cargo-build-devel %{_description}

This package contains library source intended for building other packages which
use the "cargo-build" feature of the "%{crate}" crate.

%files       -n %{name}+cargo-build-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
test "%{source0_hash}" = "none" || { f="%{SOURCE0}"; test -f "$f" || { echo "oreon: missing Source0 $f" >&2; exit 1; }; h=$(sha256sum "$f" | awk '{print $1}'); test "$h" = "%{source0_hash}" || { echo "oreon: Source0 hash mismatch" >&2; exit 1; }; }
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
%autochangelog
