%global source0_hash 429133cbda9f8a46e03ef3aae6abb6c3d22875f8585cad472138101bfd517255

# Generated by rust2rpm 28
%bcond check 1
%global debug_package %{nil}

%global crate tree-sitter-r

Name:           rust-tree-sitter-r
Version:        1.2.0
Release:        %autorelease
Summary:        R grammar for tree-sitter

License:        MIT
URL:            https://crates.io/crates/tree-sitter-r
Source:         %{crates_source}
# * LICENSE file not shipped, see
#   https://github.com/r-lib/tree-sitter-r/pull/192
Source1:        https://raw.githubusercontent.com/r-lib/tree-sitter-r/refs/tags/v%{version}/LICENSE

BuildRequires:  cargo-rpm-macros >= 24

%global _description %{expand:
R grammar for tree-sitter.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
%license %{crate_instdir}/LICENSE
%doc %{crate_instdir}/README.md
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
test "%{source0_hash}" = "none" || { f="%{SOURCE0}"; test -f "$f" || { echo "oreon: missing Source0 $f" >&2; exit 1; }; h=$(sha256sum "$f" | awk '{print $1}'); test "$h" = "%{source0_hash}" || { echo "oreon: Source0 hash mismatch" >&2; exit 1; }; }

%autosetup -n %{crate}-%{version} -p1
cp -p %{SOURCE1} .
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install
cp -p LICENSE %{buildroot}%{crate_instdir}/

%if %{with check}
%check
%cargo_test
%endif

%changelog
%autochangelog
