%global source0_hash e2288c906f0ab336623286e32732a3f22aa91d126d226e89579a70761fe59462

# Generated by go2rpm 1.8.0
%bcond check 0
%global debug_package %{nil}

# https://github.com/go-yaml/yaml
%global goipath         gopkg.in/yaml.v1
%global forgeurl        https://github.com/go-yaml/yaml
%global commit          9f9df34309c04878acc86042b16630b0f696e1de

%gometa

%global goaltipaths     gopkg.in/v1/yaml

%global common_description %{expand:
The yaml package enables Go programs to comfortably encode and decode YAML
values. It was developed within Canonical as part of the juju project, and is
based on a pure Go port of the well-known libyaml C library to parse and
generate YAML data quickly and reliably.

The yaml package supports most of YAML 1.1 and 1.2, including support for
anchors, tags, map merging, etc. Multi-document unmarshalling is not yet
implemented, and base-60 floats from YAML 1.1 are purposefully not supported
since they're a poor design and are gone in YAML 1.2.}

%global golicenses      LICENSE LICENSE.libyaml
%global godocs          README.md

Name:           %{goname}
Version:        0
Release:        0.19%{?dist}
Summary:        YAML support for the Go language

License:        MIT AND LGPL-3.0-only WITH LGPL-3.0-linking-exception
URL:            %{gourl}
Source:         %{gosource}

BuildRequires:  golang(gopkg.in/check.v1)

%description %{common_description}

%gopkg

%prep
test "%{source0_hash}" = "none" || { f="%{SOURCE0}"; test -f "$f" || { echo "oreon: missing Source0 $f" >&2; exit 1; }; h=$(sha256sum "$f" | awk '{print $1}'); test "$h" = "%{source0_hash}" || { echo "oreon: Source0 hash mismatch" >&2; exit 1; }; }

%goprep

%install
%gopkginstall

%if %{with check}
%check
for test in "TestMarshal" "TestMarshalErrors" "TestUnmarshal"\
; do
awk -i inplace '/^func.*'"$test"'\(/ { print; print "\tc.Skip(\"disabled failing test\")"; next}1' $(grep -rl $test)
done
%gocheck
%endif

%gopkgfiles

%changelog
%autochangelog
