# Configuration snippet for vdr-extrecmenung.conf                   -*- sh -*-
#
# Add command line options to pass to the extrecmenung plugin to PLUGIN_OPTIONS,
# but this plugin has currently no available options.

PLUGIN_OPTIONS=""
