#!/bin/sh
# name this script 'pbuilder-bookworm', 'pbuilder-bullseye', 'pbuilder-buster', 'pbuilder-jammy' etc.

OPERATION=$1
DISTRIBUTION=`basename $0 | cut -f2 -d '-'`
PROCEED=false
BASE_DIR="/var/cache/pbuilder/"
REPO="http://deb.debian.org/debian"
REPO2="http://security.debian.org/debian-security/"
COMPONENTS="contrib main non-free non-free-firmware"
case $OPERATION in
   create|update|build|clean|login|execute )
      PROCEED=true
      ;;
esac
if ( $PROCEED == true ) then
   shift 
   sudo pbuilder $OPERATION \
   --mirror $REPO \
   --extrapackages wget --extrapackages nano \
   --debootstrapopts "--include=wget,nano,net-tools" \
   --debootstrapopts "--keyring=/usr/share/keyrings/debian-archive-keyring.gpg" \
   --components "$COMPONENTS" \
   --othermirror "deb-src $REPO $DISTRIBUTION $COMPONENTS|deb $REPO $DISTRIBUTION-updates $COMPONENTS|deb-src $REPO $DISTRIBUTION-updates $COMPONENTS|deb $REPO $DISTRIBUTION-backports $COMPONENTS|deb-src $REPO $DISTRIBUTION-backports $COMPONENTS|deb $REPO2 $DISTRIBUTION-security $COMPONENTS|deb-src $REPO2 $DISTRIBUTION-security $COMPONENTS" \
   --distribution $DISTRIBUTION \
   --basetgz $BASE_DIR/base-$DISTRIBUTION.tgz \
   --architecture amd64 --override-config  $@
else
   echo "Invalid command..."
   echo "Valid commands are:"
   echo "   create"
   echo "   update"
   echo "   build"
   echo "   clean"
   echo "   login"
   echo "   execute"
   exit 1
fi