%global source0_hash a35116c25419836955a509bfb9f705657dc34bc414ce314ee92f3df983244d7b

# Generated by go2rpm 1.12.0
%bcond check 0
%global debug_package %{nil}

# https://github.com/seccomp/libseccomp-golang
%global goipath         github.com/seccomp/libseccomp-golang
Version:                0.12.0

%gometa -L

%global common_description %{expand:
The libseccomp library provides an easy to use, platform independent, interface
to the Linux Kernel's syscall filtering mechanism.  The libseccomp API is
designed to abstract away the underlying BPF based syscall filter language and
present a more conventional function-call based filtering interface that should
be familiar to, and easily adopted by, application developers.

The libseccomp-golang library provides a Go based interface to the libseccomp
library.}

%global golicenses      LICENSE
%global godocs          CHANGELOG README

Name:           golang-github-seccomp-libseccomp
Release:        %autorelease
Summary:        Libseccomp Go bindings

License:        BSD-2-Clause
URL:            %{gourl}
Source:         %{gosource}

%if %{with check}
BuildRequires:  pkgconfig(libseccomp)
%endif

%description %{common_description}

%gopkg

%prep
test "%{source0_hash}" = "none" || { f="%{SOURCE0}"; test -f "$f" || { echo "oreon: missing Source0 $f" >&2; exit 1; }; h=$(sha256sum "$f" | awk '{print $1}'); test "$h" = "%{source0_hash}" || { echo "oreon: Source0 hash mismatch" >&2; exit 1; }; }

%goprep -A
%autopatch -p1

%generate_buildrequires
%go_generate_buildrequires

%install
%gopkginstall

%if %{with check}
%check
%ifnarch i686 ppc64le s390x riscv64
%gocheck
%endif
%endif

%gopkgfiles

%changelog
%autochangelog
