%global source0_hash 6fe962d42e07c22aec2618191c3683412735b7e6dcd7bab2eec811ab4697c58e

# Generated by rust2rpm 28
%bcond check 0
%global debug_package %{nil}

%global crate cap-std-ext

Name:           rust-cap-std-ext
Version:        4.0.7
Release:        %autorelease
Summary:        Extension APIs for cap-std

License:        MIT OR Apache-2.0
URL:            https://crates.io/crates/cap-std-ext
Source:         %{crates_source}
Patch:          cap-std-ext-fix-metadata-auto.diff

BuildRequires:  cargo-rpm-macros >= 24

%global _description %{expand:
Extension APIs for cap-std}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
%license %{crate_instdir}/LICENSE-APACHE
%license %{crate_instdir}/LICENSE-MIT
%doc %{crate_instdir}/README.md
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+fs_utf8-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+fs_utf8-devel %{_description}

This package contains library source intended for building other packages which
use the "fs_utf8" feature of the "%{crate}" crate.

%files       -n %{name}+fs_utf8-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
test "%{source0_hash}" = "none" || { f="%{SOURCE0}"; test -f "$f" || { echo "oreon: missing Source0 $f" >&2; exit 1; }; h=$(sha256sum "$f" | awk '{print $1}'); test "$h" = "%{source0_hash}" || { echo "oreon: Source0 hash mismatch" >&2; exit 1; }; }
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
%autochangelog
