.TH FASTAPI\-DEPLOY "1" "December 2025" "" "User Commands"
.SH NAME
.B fastapi\ deploy
\(en Deploy a FastAPI app to FastAPI Cloud. \[u1F680]
.SH SYNOPSIS
.B fastapi\ deploy
.RI [ OPTIONS ]
.RI [ PATH ]
.SH OPTIONS
.TP
.B \-\-no\-wait
Skip waiting for deployment status.
.TP
.B \-\-help
Show a help message and exit.
.SS "ARGUMENTS"
.TP
.I PATH
A path to the folder containing the app you want to deploy.
.SH "SEE ALSO"
.BR fastapi\-dev (1),
.BR fastapi\-run (1),
.BR fastapi\-login (1),
.BR fastapi\-cloud (1),
.BR fastapi\-new (1)
.P
.BR fastapi (1)
