.TH FASTAPI\-LOGIN "1" "December 2025" "" "User Commands"
.SH NAME
.B fastapi\ login
\(en Login to FastAPI Cloud. \[u1F680]
.SH SYNOPSIS
.B fastapi\ login
.RI [ OPTIONS ]
.SH OPTIONS
.TP
.B \-\-help
Show a help message and exit.
.SH "SEE ALSO"
.BR fastapi\-dev (1),
.BR fastapi\-run (1),
.BR fastapi\-deploy (1),
.BR fastapi\-cloud (1),
.BR fastapi\-new (1)
.P
.BR fastapi (1)
