%global source0_hash 747d8437319e3a2f43d93b341c137927ca70c0f5dabeea7a005a73665e247c7e

# Generated by rust2rpm 28
# * tests can only be run in-tree
%bcond check 0
%global debug_package %{nil}

%global crate cxx

Name:           rust-cxx
Version:        1.0.194
Release:        %autorelease
Summary:        Safe interop between Rust and C++

License:        MIT OR Apache-2.0
URL:            https://crates.io/crates/cxx
Source:         %{crates_source}
# Manually created patch for downstream crate metadata changes
# * drop dependency hack for cxx-build and cxxbridge-cmd crates
# * exclude files that are only needed for integration in bazel or buck
# * exclude unused docs sources
Patch:          cxx-fix-metadata.diff

BuildRequires:  cargo-rpm-macros >= 24

%global _description %{expand:
Safe interop between Rust and C++.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
%license %{crate_instdir}/LICENSE-APACHE
%license %{crate_instdir}/LICENSE-MIT
%doc %{crate_instdir}/README.md
%doc %{crate_instdir}/compile_flags.txt
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+alloc-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+alloc-devel %{_description}

This package contains library source intended for building other packages which
use the "alloc" feature of the "%{crate}" crate.

%files       -n %{name}+alloc-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+c++14-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+c++14-devel %{_description}

This package contains library source intended for building other packages which
use the "c++14" feature of the "%{crate}" crate.

%files       -n %{name}+c++14-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+c++17-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+c++17-devel %{_description}

This package contains library source intended for building other packages which
use the "c++17" feature of the "%{crate}" crate.

%files       -n %{name}+c++17-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+c++20-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+c++20-devel %{_description}

This package contains library source intended for building other packages which
use the "c++20" feature of the "%{crate}" crate.

%files       -n %{name}+c++20-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+std-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+std-devel %{_description}

This package contains library source intended for building other packages which
use the "std" feature of the "%{crate}" crate.

%files       -n %{name}+std-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
test "%{source0_hash}" = "none" || { f="%{SOURCE0}"; test -f "$f" || { echo "oreon: missing Source0 $f" >&2; exit 1; }; h=$(sha256sum "$f" | awk '{print $1}'); test "$h" = "%{source0_hash}" || { echo "oreon: Source0 hash mismatch" >&2; exit 1; }; }

%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
%autochangelog
