# GAP SCSCP server configuration file.
#

# Options for gapd
# see gapd(8) for details
## For example:
## GAPD_OPTIONS="-l -p 26133 -t log --infolevel 0"
GAPD_OPTIONS=""

# Temporary directory
TMPDIR=/tmp
