%global source0_hash 05c85cc446125980d1b1f173f04199401506307fff106039b8a7b326b6cf749f

# Generated by rust2rpm 28
%bcond check 0
%global debug_package %{nil}

%global crate sqlite3-parser

Name:           rust-sqlite3-parser
Version:        0.16.0
Release:        %autorelease
Summary:        SQL parser (as understood by SQLite)

License:        Apache-2.0 OR MIT
URL:            https://crates.io/crates/sqlite3-parser
Source:         %{crates_source}

BuildRequires:  cargo-rpm-macros >= 24

%global _description %{expand:
SQL parser (as understood by SQLite)}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
%license %{crate_instdir}/LICENSE
%doc %{crate_instdir}/README.md
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+NDEBUG-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+NDEBUG-devel %{_description}

This package contains library source intended for building other packages which
use the "NDEBUG" feature of the "%{crate}" crate.

%files       -n %{name}+NDEBUG-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+SQLITE_ENABLE_ORDERED_SET_AGGREGATES-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+SQLITE_ENABLE_ORDERED_SET_AGGREGATES-devel %{_description}

This package contains library source intended for building other packages which
use the "SQLITE_ENABLE_ORDERED_SET_AGGREGATES" feature of the "%{crate}" crate.

%files       -n %{name}+SQLITE_ENABLE_ORDERED_SET_AGGREGATES-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+YYCOVERAGE-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+YYCOVERAGE-devel %{_description}

This package contains library source intended for building other packages which
use the "YYCOVERAGE" feature of the "%{crate}" crate.

%files       -n %{name}+YYCOVERAGE-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+YYNOERRORRECOVERY-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+YYNOERRORRECOVERY-devel %{_description}

This package contains library source intended for building other packages which
use the "YYNOERRORRECOVERY" feature of the "%{crate}" crate.

%files       -n %{name}+YYNOERRORRECOVERY-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+YYTRACKMAXSTACKDEPTH-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+YYTRACKMAXSTACKDEPTH-devel %{_description}

This package contains library source intended for building other packages which
use the "YYTRACKMAXSTACKDEPTH" feature of the "%{crate}" crate.

%files       -n %{name}+YYTRACKMAXSTACKDEPTH-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+extra_checks-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+extra_checks-devel %{_description}

This package contains library source intended for building other packages which
use the "extra_checks" feature of the "%{crate}" crate.

%files       -n %{name}+extra_checks-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
test "%{source0_hash}" = "none" || { f="%{SOURCE0}"; test -f "$f" || { echo "oreon: missing Source0 $f" >&2; exit 1; }; h=$(sha256sum "$f" | awk '{print $1}'); test "$h" = "%{source0_hash}" || { echo "oreon: Source0 hash mismatch" >&2; exit 1; }; }
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
%autochangelog
