# Uncomment the alias line to have the pcspkr.ko driver load
# automatically on boot.
#
# The pcspkr.ko driver module is shipped in the kernel-modules-extra
# which you need to install manually at this time.
#
# An automatic installation via "requires" or "recommends" is not
# possible due to "dnf install 'kmod(pcspkr.ko)'" likely installing an
# unrelated (-debug) kernel (see
# https://bugzilla.redhat.com/show_bug.cgi?id=1652823).
#
# Note that the kernel-modules-extra package and the pcspkr.ko module
# might also not be available inside a container, while the hosts's
# actual pcspkr.ko API might or might not be available inside the
# container depending on how the container is launched.
#
# So inside a container, the "beep" command might or might not produce
# sound depending on things entirely outside of the control of "beep"
# or even the container.
#
# alias platform:pcspkr pcspkr
