.TH "txt2rss" 1
.SH NAME
txt2rss \- convert a simple txt file to a rss feed file
.SH SYNOPSIS
.B txt2rss
\fItxt-file \fIoutput-file
.SH DESCRIPTION
txt2rss is a shell script that parses a simple txt file (in a simple
format) and convert it to RSS feed file. Simple to use and intuitive,
      You need to set up a config file (/etc/txt2rss/txt2rss.conf)
with parameter like webmaster's name, link of the site and others,
after you just call the script with txt-file and output-file.

.SH "AUTHORS"
Carlos Roberto do Nascimento Costa <crncosta AT gmail.com> &
.br
Paulo Ricardo Paz Vital <pvital AT gmail.com>
.SH REPORTING BUGS
Bugs should be reported to http://code.google.com/p/txt2rss/issues/list 


