%global source0_hash 863f57f96f77c2b4e5488e34e8df47478e9ffa9920779ca4df2cc3adc0d03252

# Generated by go2rpm
%bcond check 0

%global debug_package %{nil}

# https://github.com/bgentry/speakeasy
%global goipath         github.com/bgentry/speakeasy
Version:                0.1.0

%gometa

%global common_description %{expand:
This package provides cross-platform Go helpers for taking user input from the
terminal while not echoing the input back (similar to getpasswd). The package
uses syscalls to avoid any dependence on cgo, and is therefore compatible with
cross-compiling.}

%global golicenses      LICENSE LICENSE_WINDOWS
%global godocs          example Readme.md

%global gosupfiles glide.lock glide.yaml

Name:           %{goname}
Release:        %autorelease
Summary:        Cross-platform golang helpers for reading password input without cgo

License:        MIT
URL:            %{gourl}
Source0:        %{gosource}
Source1:        glide.yaml
Source2:        glide.lock

%description
%{common_description}

%gopkg

%prep
test "%{source0_hash}" = "none" || { f="%{SOURCE0}"; test -f "$f" || { echo "oreon: missing Source0 $f" >&2; exit 1; }; h=$(sha256sum "$f" | awk '{print $1}'); test "$h" = "%{source0_hash}" || { echo "oreon: Source0 hash mismatch" >&2; exit 1; }; }

%goprep
cp %{S:1} %{S:2} .

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog
%autochangelog
