.TH "CSDP-GRAPHTOPROB" "1" "6.1.1" "Brian Borchers" "User Commands"
.SH "NAME"
csdp-graphtoprob \- Convert a graph description to SDPA sparse format
.SH "SYNOPSIS"
.B csdp-graphtoprob
GRAPH_FILE PROBLEM_FILE
.SH "DESCRIPTION"
.PP 
The csdp-graphtoprob program converts a graph into SDPA sparse format.

.SH "FILE FORMAT"
.PP
The input file should be in the following format:
.RS
.br
n
.br
m
.br
i1 j1
.br
\[u2026]
.br
im jm
.RE
where n is the number of nodes, m is the number of edges, and each i/j pair
describes one edge.
.PP
The output file has the same graph written to it in SDPA sparse format.

.SH "EXIT STATUS"
.PP 
The exit status is zero if the graph is converted successfully.  Otherwise, the
exit status is one, and an error message indicating the problem is produced on
standard out.

.SH "AUTHORS"
Csdp was written by Dr. Brian Borchers <borchers@nmt.edu>, with contributions
by Joseph Young <josyoun@nmt.edu> and Aaron Wilson <wilson@nmt.edu>.
.PP 
This man page was written by Jerry James <loganjerry@gmail.com>.
It is distributed under the same terms as Csdp.

.SH "SEE ALSO"
.PP
\fIcsdp-theta\fP(1), \fIcsdp-complement\fP(1), \fIcsdp-rand_graph\fP(1)
