.TH "CSDP" "1" "6.1.1" "Brian Borchers" "User Commands"
.SH "NAME"
csdp \- Semidefinite Programming solver
.SH "SYNOPSIS"
.B csdp
PROBLEM [\fIFINAL_SOLUTION \fR[\fIINITIAL_SOLUTION\fR]]
.SH "DESCRIPTION"
.PP 
CSDP is a library of routines that implements a predictor corrector variant of
the semidefinite programming algorithm of Helmberg, Rendl, Vanderbei, and
Wolkowicz.  The main advantages of this code are that it is written to be used
as a callable subroutine, it is written in C for efficiency, the code runs in
parallel on shared memory multi\-processor systems, and it makes effective use
of sparsity in the constraint matrices.
.PP 
The csdp binary is a simple command\-line interface to the library.

.SH "EXIT STATUS"
.PP 
The output is a solution, together with some timing information.
The exit status indicates the following:
.IP 0
A solution to the problem was found.
.IP 1
The problem is primal infeasible.
.IP 2
The problem is dual infeasible.
.IP 3
The problem was solved with reduced accuracy.
.IP 4
The maximum number of iterations was reached without finding a solution.
.IP 5
The search got stuck at the edge of primal feasibility.
.IP 6
The search got stuck at the edge of dual feasibility.
.IP 7
Lack of progress in finding a solution was detected.
.IP 8
The system matrix is singular, factorization of the matrix failed, or solving
for dy or dy1 failed.
.IP 9
Too many line search failures were encountered.
.IP 10
An input problem or solution could not be read.
.IP 12
The gap became infinite or NaN.

.SH "AUTHORS"
Csdp was written by Dr. Brian Borchers <borchers@nmt.edu>, with contributions
by Joseph Young <josyoun@nmt.edu> and Aaron Wilson <wilson@nmt.edu>.
.PP 
This man page was written by Jerry James <loganjerry@gmail.com>.
It is distributed under the same terms as Csdp.
