#Type Name         ID        GECOS                  Home directory    Shell
g     mosquitto    -
u     mosquitto    -         "Mosquitto Broker"     /etc/mosquitto    /sbin/nologin
m     mosquitto    mosquitto
