%global source0_hash 1c2c3a20523ccd5f002be3718dd90fbc7954c3442a1b32334926ba2ded79795c

# Generated by go2rpm 1.9.0
%bcond check 0
%global debug_package %{nil}

# https://github.com/lestrrat-go/backoff
%global goipath         github.com/lestrrat-go/backoff/v2
Version:                2.0.8

%gometa -f

%global common_description %{expand:
Backoff mechanics for Go.}

%global golicenses      LICENSE
%global godocs          README.md

Name:           %{goname}
Release:        %autorelease
Summary:        Backoff mechanics for Go

License:        MIT
URL:            %{gourl}
Source:         %{gosource}

%description %{common_description}

%gopkg

%prep
test "%{source0_hash}" = "none" || { f="%{SOURCE0}"; test -f "$f" || { echo "oreon: missing Source0 $f" >&2; exit 1; }; h=$(sha256sum "$f" | awk '{print $1}'); test "$h" = "%{source0_hash}" || { echo "oreon: Source0 hash mismatch" >&2; exit 1; }; }

%goprep
%autopatch -p1

%generate_buildrequires
%go_generate_buildrequires

%install
%gopkginstall

%if %{with check}
%check
for test in "TestExponential" \
; do
awk -i inplace '/^func.*'"$test"'\(/ { print; print "\tt.Skip(\"disabled failing test\")"; next}1' $(grep -rl $test)
done
%gocheck
%endif

%gopkgfiles

%changelog
%autochangelog
