%global source0_hash bb7354b64cc760ca057ba88d2651210b855c138b105cdbe86e57c494f3d53a9f

# Generated by go2rpm 1.11.1
%bcond check 0
%global debug_package %{nil}

# https://github.com/go-openapi/errors
%global goipath         github.com/go-openapi/errors
Version:                0.22.9

%gometa -L

%global common_description %{expand:
Package Errors provides an Error interface and several concrete types
implementing this interface to manage API errors and JSON-schema validation
errors.

A middleware handler ServeError() is provided to serve the errors types it
defines.

It is used throughout the various Go-openapi toolkit libraries.}

%global golicenses      LICENSE
%global godocs          CODE_OF_CONDUCT.md README.md

Name:           golang-github-openapi-errors
Release:        %autorelease
Summary:        Openapi toolkit common errors

License:        Apache-2.0
URL:            %{gourl}
Source:         %{gosource}

%description %{common_description}

%gopkg

%prep
test "%{source0_hash}" = "none" || { f="%{SOURCE0}"; test -f "$f" || { echo "oreon: missing Source0 $f" >&2; exit 1; }; h=$(sha256sum "$f" | awk '{print $1}'); test "$h" = "%{source0_hash}" || { echo "oreon: Source0 hash mismatch" >&2; exit 1; }; }

%goprep -A
%autopatch -p1

%generate_buildrequires
%go_generate_buildrequires

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog
%autochangelog
