.\" Hey, EMACS: -*- nroff -*-
.\" Copyright (C) 2016 Johan Heikkila <johan.heikkila@gmail.com>
.\"
.\" This document is free software.  You may distribute and/or modify
.\" it under the terms of:
.\"
.\" * The GNU General Public License, as published by the Free
.\"   Software Foundation, version 3 or (at your option) any later
.\"   version.  You should have received a copy of the GNU General
.\"   Public License along with this program.  If not, see
.\"   <http://www.gnu.org/licenses/>.
.\"
.\" $Id$
.TH CKB-NEXT 1 "version 1.0.0" "December 2016"
.\" Please adjust this date whenever revising the manpage.
.\"

.SH NAME

ckb-next \- User interface for the ckb-next driver for Corsair RGB keyboards and mice.

.SH DESCRIPTION

\fBckb-next\fP is an open-source driver for Corsair keyboards and mice. It aims
to bring the features of their proprietary CUE software to the Linux and Mac
operating systems. This project is currently a work in progress, but it already
supports much of the same functionality, including full RGB animations.

\fBckb-next\fP supports the following keyboards:

 - K65 RGB
 - K70
 - K70 RGB
 - K70 LUX
 - K70 LUX RGB
 - K95*
 - K95 RGB
 - Strafe
 - Strafe RGB

*= hardware playback not supported. Settings will be saved to software only.

Mice:

 - M65 RGB
 - M65 PRO RGB
 - Sabre RGB
 - Scimitar RGB

.SH OPTIONS

\fB\-v\fR|\-\-version         Displays version information.
\fB\-h\fR|\-\-help            Displays this help.
\fB\-B\fR|\-\-background      Starts in background, without displaying the main window.
\fB\-c\fR|\-\-close           Causes already running instance (if any) to exit.

.SH BUGS

\fB<https://github.com/mattanger/ckb-next/issues>\fP.

.SH HOMEPAGE

\fB<https://github.com/mattanger/ckb-next>\fP

.SH AUTHORS

MSC https://github.com/ccMSC (original ckb project)
mattanger https://github.com/mattanger et al. (ckb-next)

.PP

This manual page was written by Johan Heikkila <johan.heikkila@gmail.com>.
