.TH BRUKER\-FILTER "1" "August 2023" "" "User Commands"
.SH NAME
.B bruker\-filter
\(en get files based on query
.SH SYNOPSIS
.B bruker\-filter
.RB [ \-h ]
.BI \-i\  INPUT
.BI \-q\  QUERY
.SH OPTIONS
.SS "OPTIONAL\ ARGUMENTS"
.TP
.B \-h\fR, \fB\-\-help
Show a help message and exit
.TP
.B \-i\ \fIINPUT\fR, \fB\-\-input\ \fIINPUT
Path to a folder containing Bruker data
.TP
.B \-q\ \fIQUERY\fR, \fB\-\-query\ \fIQUERY
Filter query
.SH "SEE\ ALSO"
.BR bruker (1)
.P
.BR bruker\-report (1),
.BR bruker\-split (1)
