%global source0_hash 635a4abf7b375659c9bab1839779487eb2a964934ad4f67ceb4e0364b75c37e2

# Generated by rust2rpm 27
%bcond check 1
%global debug_package %{nil}

%global crate librsvg-rebind-sys

Name:           rust-librsvg-rebind-sys0.1
Version:        0.1.0
Release:        %autorelease
Summary:        FFI bindings for librsvg

License:        MIT
URL:            https://crates.io/crates/librsvg-rebind-sys
Source:         %{crates_source}

BuildRequires:  cargo-rpm-macros >= 24
BuildRequires:  pkgconfig(librsvg-2.0) >= 2.50

%global _description %{expand:
FFI bindings for librsvg.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch
Requires:       pkgconfig(librsvg-2.0) >= 2.50

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
%license %{crate_instdir}/LICENSE
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+v2_58-devel
Summary:        %{summary}
BuildArch:      noarch
Requires:       pkgconfig(librsvg-2.0) >= 2.58

%description -n %{name}+v2_58-devel %{_description}

This package contains library source intended for building other packages which
use the "v2_58" feature of the "%{crate}" crate.

%files       -n %{name}+v2_58-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
test "%{source0_hash}" = "none" || { f="%{SOURCE0}"; test -f "$f" || { echo "oreon: missing Source0 $f" >&2; exit 1; }; h=$(sha256sum "$f" | awk '{print $1}'); test "$h" = "%{source0_hash}" || { echo "oreon: Source0 hash mismatch" >&2; exit 1; }; }

%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
%autochangelog
