# PSGIApp defines a file to be loaded by 'do' Perl keyword at the time of
# parent process startup. The file must be a Perl program that returns a code
# reference that is a PSGI application as defined in PSGI specification
# <https://metacpan.org/pod/PSGI>.

# This will route '/psgi' URL path requests to a PSGI application defined with
# the 'PSGIApp' keyword.
#
#<Location /psgi>
#  SetHandler psgi
#  PSGIApp /path/to/app.psgi
#</Location>

