%global source0_hash 9865a50f7c335f53564bb694ef660825eb8610e0a53d3e11bf1b0d3df31e03b0

# Generated by rust2rpm 28
%bcond check 0
%global debug_package %{nil}

%global crate darling_core

Name:           rust-darling_core
Version:        0.23.0
Release:        %autorelease
Summary:        Helper crate for proc-macro library for reading attributes into struc...

License:        MIT
URL:            https://crates.io/crates/darling_core
Source:         %{crates_source}

BuildRequires:  cargo-rpm-macros >= 24

%global _description %{expand:
Helper crate for proc-macro library for reading attributes into structs when
implementing custom derives. Use https://crates.io/crates/darling in your code.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
%license %{crate_instdir}/LICENSE

%{crate_instdir}/

%package     -n %{name}+diagnostics-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+diagnostics-devel %{_description}

This package contains library source intended for building other packages which
use the "diagnostics" feature of the "%{crate}" crate.

%files       -n %{name}+diagnostics-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+serde-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+serde-devel %{_description}

This package contains library source intended for building other packages which
use the "serde" feature of the "%{crate}" crate.

%files       -n %{name}+serde-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+strsim-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+strsim-devel %{_description}

This package contains library source intended for building other packages which
use the "strsim" feature of the "%{crate}" crate.

%files       -n %{name}+strsim-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+suggestions-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+suggestions-devel %{_description}

This package contains library source intended for building other packages which
use the "suggestions" feature of the "%{crate}" crate.

%files       -n %{name}+suggestions-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
test "%{source0_hash}" = "none" || { f="%{SOURCE0}"; test -f "$f" || { echo "oreon: missing Source0 $f" >&2; exit 1; }; h=$(sha256sum "$f" | awk '{print $1}'); test "$h" = "%{source0_hash}" || { echo "oreon: Source0 hash mismatch" >&2; exit 1; }; }
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
%autochangelog
