# Configuration snippet for vdr-skinnopacity                   -*- sh -*-
#
# Add command line options to pass to the skinnopacity plugin to PLUGIN_OPTIONS.
# See /usr/share/doc/vdr-skinnopacity/README for info about available options.

PLUGIN_OPTIONS="--iconpath=/usr/share/vdr/plugins/skinnopacity/icons/ --logopath=/usr/share/vdr/plugins/skinnopacity/logos/ --epgimages=/var/cache/vdr/plugins/skinnopacity/epgimages/"
