
# We want to use the following Packit functions in the ncompress package:
# koji_build, bodhi_update, pull_from_upstream

# See the documentation for more information:
# https://packit.dev/docs/configuration/

specfile_path: ncompress.spec

# name in upstream package repository or registry (e.g. in PyPI)
upstream_package_name: ncompress
upstream_project_url: https://github.com/vapier/ncompress
# downstream (Fedora) RPM package name
downstream_package_name: ncompress

jobs:
  - job: pull_from_upstream
    trigger: release
    dist_git_branches:
      - fedora-latest
      - fedora-rawhide

  - job: koji_build
    trigger: commit
    allowed_pr_authors: ["ljavorsk", "ovasik", "praiskup", "tdawson", "packit"]
    allowed_committers: ["ljavorsk", "ovasik", "praiskup", "tdawson", "packit"]
    dist_git_branches:
      - fedora-latest
      - fedora-rawhide

  - job: bodhi_update
    trigger: commit
    dist_git_branches:
      - fedora-latest # rawhide updates are created automatically
