%global source0_hash 286345981973c72cfcd7ac41fa593dd940b31fb5497e2de28a58a706913e3f61

# Generated by go2rpm
%bcond check 0

%global debug_package %{nil}

# https://github.com/revel/log15
%global goipath         github.com/revel/log15
Version:                2.11.20

%gometa

%global common_description %{expand:
Package log15 provides an opinionated, simple toolkit for best-practice logging
in Go (golang) that is both human and machine readable. It is modeled after the
Go standard library's io and net/http packages and is an alternative to the
standard library's log package.}

%global golicenses      LICENSE
%global godocs          CONTRIBUTORS README.md

Name:           %{goname}
Release:        %autorelease
Summary:        Structured, composable logging for Go

# Upstream license specification: MIT and Apache-2.0
# Automatically converted from old format: MIT and ASL 2.0 - review is highly recommended.
License:        LicenseRef-Callaway-MIT AND Apache-2.0
URL:            %{gourl}
Source0:        %{gosource}

BuildRequires:  golang(github.com/inconshreveable/log15)
BuildRequires:  golang(github.com/inconshreveable/log15/term)
BuildRequires:  golang(github.com/mattn/go-colorable)
BuildRequires:  golang(gopkg.in/stack.v0)

%description
%{common_description}

%gopkg

%prep
test "%{source0_hash}" = "none" || { f="%{SOURCE0}"; test -f "$f" || { echo "oreon: missing Source0 $f" >&2; exit 1; }; h=$(sha256sum "$f" | awk '{print $1}'); test "$h" = "%{source0_hash}" || { echo "oreon: Source0 hash mismatch" >&2; exit 1; }; }

%goprep

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog
%autochangelog
