.TH OP1SVG "1" "April 2021" "" "User Commands"
.SH NAME
op1svg \- normalize SVG files so that the OP-1 understands them
.SH SYNOPSIS
.B op1svg
.RB [ \-h ]
.RB [ \-\-debug ]
.RB [ \-\-version ]
.I in_path
.I out_path
.SH OPTIONS
.SS "POSITIONAL\ ARGUMENTS"
.TP
.I in_path
file path of svg file to fix
.TP
.I out_path
file path to write the fixed svg to
.SS "OPTIONAL\ ARGUMENTS"
.TP
.B \-h, \-\-help
show a help message and exit
.TP
.B \-\-debug
print debug messages
.TP
.B \-\-version
show program\(cqs version number and exit
