# Configuration snippet for vdr-skinelchihd                           -*- sh -*-
#
# Add command line options to pass to the skinelchihd plugin to PLUGIN_OPTIONS.
# See /usr/share/doc/vdr-skinelchihd/README for info about available options.
# -l <LogoPath>,  --logopath=<LogoPath>
#	Path to SVG channel logos, default is <ResourceDir>/plugins/skinelchihd/logos
# -e <ImageDir>, --epgimages=<ImageDir>
#	Path to EPG-Pictures
#	Default is <CacheDir>/plugins/skinelchihd/epgimages

PLUGIN_OPTIONS=""

