Name: hyphen-ru
Summary: Russian hyphenation rules
%global upstreamid 20200325
Version: 0.%{upstreamid}
Release: 15%{?dist}
Source1: http://mirrors.ctan.org/language/hyph-utf8/tex/generic/hyph-utf8/patterns/tex/hyph-ru.tex
Source2: http://mirrors.ctan.org/language/hyph-utf8/tex/generic/hyph-utf8/patterns/txt/hyph-ru.pat.txt
URL: https://ctan.org/tex-archive/language/hyph-utf8
License: LPPL-1.3a
BuildArch: noarch
Requires: hyphen
BuildRequires: hyphen-devel
Supplements: (hyphen and langpacks-ru)

%description
Russian hyphenation rules.

%prep
%autosetup -c -n hyphen-ru -T

%build
substrings.pl %{SOURCE2} hyph_ru_RU.dic UTF-8 2 2
cat > README_hyph_ru_RU.txt << EOF
hyph_ru_RU.dic generated by:
 substrings.pl hyph-ru.pat.txt hyph_ru_RU.dic UTF-8 2 2
from hyph-ru.pat.txt provided by hyph-utf8 from
https://ctan.org/tex-archive/language/hyph-utf8
where hyph-ru.pat.txt is derived from hyph-ru.tex
whose licence header follows here:

EOF
head -n 44 %{SOURCE1} >> README_hyph_ru_RU.txt

%install
mkdir -p $RPM_BUILD_ROOT/%{_datadir}/hyphen
cp -p hyph_ru_RU.dic $RPM_BUILD_ROOT/%{_datadir}/hyphen
pushd $RPM_BUILD_ROOT/%{_datadir}/hyphen/
ru_RU_aliases="ru_UA"
for lang in $ru_RU_aliases; do
        ln -s hyph_ru_RU.dic hyph_$lang.dic
done


%files
%doc README_hyph_ru_RU.txt
%{_datadir}/hyphen/*

%changelog
* Mon May 25 2026 Oreon Packaging Team <packaging@oreonhq.com> - 0.20200325-15
- Import
