%global source0_hash c4325b12188dc7bba92b49a2d74c2bcc1e287b4f9ff240b4ca42e31ab5d61882

# Perform optional tests
%bcond_without perl_Syntax_Operator_Equ_enables_optional_test

# A build cycle: perl-Syntax-Operator-Equ → perl-Syntax-Keyword-Match.spec
%if %{with perl_Syntax_Operator_Equ_enables_optional_test} && !%{defined perl_bootstrap}
%global optional_tests 1
%else
%global optional_tests 0
%endif

Name:           perl-Syntax-Operator-Equ
Version:        0.10
Release:        6%{?dist}
Summary:        Equality operators that distinguish undef
License:        GPL-1.0-or-later OR Artistic-1.0-Perl
URL:            https://metacpan.org/release/Syntax-Operator-Equ
Source0:        https://cpan.metacpan.org/authors/id/P/PE/PEVANS/Syntax-Operator-Equ-%{version}.tar.gz
BuildRequires:  coreutils
BuildRequires:  findutils
BuildRequires:  perl-devel
BuildRequires:  perl-generators
BuildRequires:  perl-interpreter
BuildRequires:  perl(:VERSION) >= 5.14
BuildRequires:  perl(ExtUtils::CBuilder)
BuildRequires:  perl(Module::Build)
BuildRequires:  perl(strict)
BuildRequires:  perl(warnings)
%global xs_parse_infix_build_minver 0.44
BuildRequires:  perl(XS::Parse::Infix::Builder) >= %{xs_parse_infix_build_minver}
# Run-time:
BuildRequires:  perl(Carp)
%global meta_min_ver 0.003.002
BuildRequires:  perl(meta) >= %{meta_min_ver}
BuildRequires:  perl(XSLoader)
# Tests:
BuildRequires:  perl(B::Deparse)
BuildRequires:  perl(overload)
BuildRequires:  perl(Test2::V0)
%if %{optional_tests}
# Optional tests:
%global Syntax_Keyword_Match_min_ver 0.08
BuildRequires:  perl(Syntax::Keyword::Match) >= %{Syntax_Keyword_Match_min_ver}
%if 0%{?fedora} >= 39
# Requires PL_infix_plugin support in Perl (since 5.37.7)
BuildRequires:  perl(Syntax::Operator::Equ)
%global Syntax_Operator_In_min_ver 0.03
BuildRequires:  perl(Syntax::Operator::In) >= %{Syntax_Operator_In_min_ver}
%endif
BuildRequires:  perl(Test::Pod) >= 1.00
%endif
Requires:       perl(meta) >= %{meta_min_ver}
# Minimal XS::Parse::Infix version requsted in boot_xs_parse_infix() argument
Requires:       perl(XS::Parse::Infix) >= %{xs_parse_infix_build_minver}
%if %{defined perl_XS_Parse_Infix_ABI}
# XS::Parse::Infix ABI checked in XSParseInfix.h generated by
# XS::Parse::Infix::Builder. 
Requires:       %{perl_XS_Parse_Infix_ABI}
%endif

# Filter under-specified dependencies
%global __requires_exclude %{?__requires_exclude:%{__requires_exclude}|}^perl\\(meta\\) >= 0.003$

Provides:       perl(Syntax::Operator::Eqr)
Provides:       perl(Syntax::Operator::Equ)
%description
This module provides infix operators that implement equality tests of
strings or numbers similar to Perl's eq and == operators, except that they
consider undef to be a distinct value, separate from the empty string or
the number zero.

%package tests
Summary:        Tests for %{name}
BuildArch:      noarch
Requires:       %{name} = %{?epoch:%{epoch}:}%{version}-%{release}
Requires:       perl-Test-Harness
%if %{optional_tests}
Requires:       perl(Syntax::Keyword::Match) >= %{Syntax_Keyword_Match_min_ver}
%if 0%{?fedora} >= 39
# Requires PL_infix_plugin support in Perl (since 5.37.7)
Requires:       perl(Syntax::Operator::Equ)
Requires:       perl(Syntax::Operator::In) >= %{Syntax_Operator_In_min_ver}
%endif
%endif

%description tests
Tests from %{name}. Execute them
with "%{_libexecdir}/%{name}/test".

%prep
test "%{source0_hash}" = "none" || { f="%{SOURCE0}"; test -f "$f" || { echo "oreon: missing Source0 $f" >&2; exit 1; }; h=$(sha256sum "$f" | awk '{print $1}'); test "$h" = "%{source0_hash}" || { echo "oreon: Source0 hash mismatch" >&2; exit 1; }; }
%setup -q -n Syntax-Operator-Equ-%{version}
%if !%{optional_tests}
for T in t/80in+equ.t t/80match-equ.t t/99pod.t; do
    rm "$T"
    perl -i -ne 'print $_ unless m{^\Q'"$T"'\E}' MANIFEST
done
%endif
chmod +x t/*.t

%build
perl Build.PL --installdirs=vendor --optimize="$RPM_OPT_FLAGS"
./Build

%install
./Build install --destdir=%{buildroot} --create_packlist=0
find %{buildroot} -type f -name '*.bs' -size 0 -delete
%{_fixperms} %{buildroot}/*
# Install tests
mkdir -p %{buildroot}%{_libexecdir}/%{name}
cp -a t %{buildroot}%{_libexecdir}/%{name}
%if %{optional_tests}
rm %{buildroot}%{_libexecdir}/%{name}/t/99pod.t
%endif
cat > %{buildroot}%{_libexecdir}/%{name}/test << 'EOF'
#!/bin/sh
cd %{_libexecdir}/%{name} && exec prove -I . -j "$(getconf _NPROCESSORS_ONLN)"
EOF
chmod +x %{buildroot}%{_libexecdir}/%{name}/test

%check
export HARNESS_OPTIONS=j$(perl -e 'if ($ARGV[0] =~ /.*-j([0-9][0-9]*).*/) {print $1} else {print 1}' -- '%{?_smp_mflags}')
./Build test

%files
%license LICENSE
%doc Changes README
%dir %{perl_vendorarch}/auto/Syntax
%dir %{perl_vendorarch}/auto/Syntax/Operator
%{perl_vendorarch}/auto/Syntax/Operator/Equ
%dir %{perl_vendorarch}/Syntax
%dir %{perl_vendorarch}/Syntax/Operator
%{perl_vendorarch}/Syntax/Operator/Eqr.pm
%{perl_vendorarch}/Syntax/Operator/Equ.pm
%{_mandir}/man3/Syntax::Operator::Eqr.*
%{_mandir}/man3/Syntax::Operator::Equ.*

%files tests
%{_libexecdir}/%{name}

%changelog
%autochangelog
