# Edit /etc/greetd/config.toml to set gtkgreet as the default session:
# ```
# [default_session]
# command = "wayfire --config /etc/gtkgreet/gtkgreet-wayfire.ini"
# ```

[autostart]
autostart_wf_shell = false
background = swaybg -o "*" -m fill -i /usr/share/backgrounds/default.png
# set GTK theme (requires gnome-themes-extra)
# theme = gsettings set org.gnome.desktop.interface color-scheme 'prefer-dark'; \
#         gsettings set org.gnome.desktop.interface gtk-theme 'Adwaita'; \
#         gsettings set org.gnome.desktop.interface cursor-theme 'Adwaita'
gtkgreet = gtkgreet --layer-shell --style /etc/gtkgreet/gtkgreet.css; wayland-logout

[core]
plugins = autostart
vheight = 1
vwidth = 1
xwayland = false
