# Edit /etc/greetd/config.toml to set gtkgreet as the default session:
# ```
# [default_session]
# command = "sway --config /etc/gtkgreet/gtkgreet-sway.conf"
# ```
bindsym Mod4+shift+e exec swaynag \
	-t warning \
	-m 'What do you want to do?' \
	-b 'Poweroff' 'systemctl poweroff' \
	-b 'Reboot' 'systemctl reboot'

# Disable displays on idle
exec command -v swayidle >/dev/null && swayidle -w \
        timeout 300 'swaymsg "output * power off"' \
             resume 'swaymsg "output * power on"'

# set background
output * bg /usr/share/backgrounds/default.png fill

# set GTK theme (requires gnome-themes-extra)
# exec gsettings set org.gnome.desktop.interface {
#     color-scheme 'prefers-dark'
#     cursor-theme 'Adwaita'
#     gtk-theme 'Adwaita'
# }

# Don't need XWayland for gtkgreet
xwayland disable

# start greeter
exec "gtkgreet --layer-shell --style /etc/gtkgreet/gtkgreet.css; wayland-logout"
