%global source0_hash eabffdaee24bd1bf95c5ef7cec31260444317e72ea56c4c91750e8b7ee58d5f1

# Generated by rust2rpm 28
%bcond check 0
%global debug_package %{nil}

%global crate ena

Name:           rust-ena
Version:        0.14.4
Release:        %autorelease
Summary:        Union-find, congruence closure, and other unification code. Based on...

License:        MIT OR Apache-2.0
URL:            https://crates.io/crates/ena
Source:         %{crates_source}

BuildRequires:  cargo-rpm-macros >= 24

%global _description %{expand:
Union-find, congruence closure, and other unification code. Based on code from rustc.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
%license %{crate_instdir}/LICENSE-APACHE
%license %{crate_instdir}/LICENSE-MIT
%doc %{crate_instdir}/README.md
%{crate_instdir}/

%package     -n %{name}+bench-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+bench-devel %{_description}

This package contains library source intended for building other packages which
use the "bench" feature of the "%{crate}" crate.

%files       -n %{name}+bench-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+dogged-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+dogged-devel %{_description}

This package contains library source intended for building other packages which
use the "dogged" feature of the "%{crate}" crate.

%files       -n %{name}+dogged-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+persistent-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+persistent-devel %{_description}

This package contains library source intended for building other packages which
use the "persistent" feature of the "%{crate}" crate.

%files       -n %{name}+persistent-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
test "%{source0_hash}" = "none" || { f="%{SOURCE0}"; test -f "$f" || { echo "oreon: missing Source0 $f" >&2; exit 1; }; h=$(sha256sum "$f" | awk '{print $1}'); test "$h" = "%{source0_hash}" || { echo "oreon: Source0 hash mismatch" >&2; exit 1; }; }
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
%autochangelog
