%global source0_hash 3a64b051fb2a1ea7422cac21153e2852b3ed1142c9ffa5fac7b3194074611cd3

# Generated by rust2rpm 28
%bcond check 0
%global debug_package %{nil}

%global crate ffmpeg-the-third
%global crate_version 3.0.2+ffmpeg-7.1
%global crate_instdir %{cargo_registry}/%{crate}-%{crate_version}

Name:           rust-ffmpeg-the-third
Version:        3.0.2
Release:        %autorelease
Summary:        Safe FFmpeg wrapper (FFmpeg 4 compatible fork of the ffmpeg crate)

License:        WTFPL
URL:            https://crates.io/crates/ffmpeg-the-third
Source:         %{crates_source}

BuildRequires:  cargo-rpm-macros >= 24

%global _description %{expand:
Safe FFmpeg wrapper (FFmpeg 4 compatible fork of the ffmpeg crate)}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
%license %{crate_instdir}/LICENSE
%doc %{crate_instdir}/README.md
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+build-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+build-devel %{_description}

This package contains library source intended for building other packages which
use the "build" feature of the "%{crate}" crate.

%files       -n %{name}+build-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+build-lib-aacplus-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+build-lib-aacplus-devel %{_description}

This package contains library source intended for building other packages which
use the "build-lib-aacplus" feature of the "%{crate}" crate.

%files       -n %{name}+build-lib-aacplus-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+build-lib-ass-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+build-lib-ass-devel %{_description}

This package contains library source intended for building other packages which
use the "build-lib-ass" feature of the "%{crate}" crate.

%files       -n %{name}+build-lib-ass-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+build-lib-avs-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+build-lib-avs-devel %{_description}

This package contains library source intended for building other packages which
use the "build-lib-avs" feature of the "%{crate}" crate.

%files       -n %{name}+build-lib-avs-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+build-lib-celt-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+build-lib-celt-devel %{_description}

This package contains library source intended for building other packages which
use the "build-lib-celt" feature of the "%{crate}" crate.

%files       -n %{name}+build-lib-celt-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+build-lib-dav1d-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+build-lib-dav1d-devel %{_description}

This package contains library source intended for building other packages which
use the "build-lib-dav1d" feature of the "%{crate}" crate.

%files       -n %{name}+build-lib-dav1d-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+build-lib-dcadec-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+build-lib-dcadec-devel %{_description}

This package contains library source intended for building other packages which
use the "build-lib-dcadec" feature of the "%{crate}" crate.

%files       -n %{name}+build-lib-dcadec-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+build-lib-faac-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+build-lib-faac-devel %{_description}

This package contains library source intended for building other packages which
use the "build-lib-faac" feature of the "%{crate}" crate.

%files       -n %{name}+build-lib-faac-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+build-lib-fdk-aac-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+build-lib-fdk-aac-devel %{_description}

This package contains library source intended for building other packages which
use the "build-lib-fdk-aac" feature of the "%{crate}" crate.

%files       -n %{name}+build-lib-fdk-aac-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+build-lib-fontconfig-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+build-lib-fontconfig-devel %{_description}

This package contains library source intended for building other packages which
use the "build-lib-fontconfig" feature of the "%{crate}" crate.

%files       -n %{name}+build-lib-fontconfig-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+build-lib-freebidi-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+build-lib-freebidi-devel %{_description}

This package contains library source intended for building other packages which
use the "build-lib-freebidi" feature of the "%{crate}" crate.

%files       -n %{name}+build-lib-freebidi-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+build-lib-freetype-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+build-lib-freetype-devel %{_description}

This package contains library source intended for building other packages which
use the "build-lib-freetype" feature of the "%{crate}" crate.

%files       -n %{name}+build-lib-freetype-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+build-lib-frei0r-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+build-lib-frei0r-devel %{_description}

This package contains library source intended for building other packages which
use the "build-lib-frei0r" feature of the "%{crate}" crate.

%files       -n %{name}+build-lib-frei0r-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+build-lib-gnutls-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+build-lib-gnutls-devel %{_description}

This package contains library source intended for building other packages which
use the "build-lib-gnutls" feature of the "%{crate}" crate.

%files       -n %{name}+build-lib-gnutls-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+build-lib-gsm-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+build-lib-gsm-devel %{_description}

This package contains library source intended for building other packages which
use the "build-lib-gsm" feature of the "%{crate}" crate.

%files       -n %{name}+build-lib-gsm-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+build-lib-ilbc-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+build-lib-ilbc-devel %{_description}

This package contains library source intended for building other packages which
use the "build-lib-ilbc" feature of the "%{crate}" crate.

%files       -n %{name}+build-lib-ilbc-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+build-lib-kvazaar-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+build-lib-kvazaar-devel %{_description}

This package contains library source intended for building other packages which
use the "build-lib-kvazaar" feature of the "%{crate}" crate.

%files       -n %{name}+build-lib-kvazaar-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+build-lib-ladspa-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+build-lib-ladspa-devel %{_description}

This package contains library source intended for building other packages which
use the "build-lib-ladspa" feature of the "%{crate}" crate.

%files       -n %{name}+build-lib-ladspa-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+build-lib-mp3lame-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+build-lib-mp3lame-devel %{_description}

This package contains library source intended for building other packages which
use the "build-lib-mp3lame" feature of the "%{crate}" crate.

%files       -n %{name}+build-lib-mp3lame-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+build-lib-opencore-amrnb-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+build-lib-opencore-amrnb-devel %{_description}

This package contains library source intended for building other packages which
use the "build-lib-opencore-amrnb" feature of the "%{crate}" crate.

%files       -n %{name}+build-lib-opencore-amrnb-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+build-lib-opencore-amrwb-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+build-lib-opencore-amrwb-devel %{_description}

This package contains library source intended for building other packages which
use the "build-lib-opencore-amrwb" feature of the "%{crate}" crate.

%files       -n %{name}+build-lib-opencore-amrwb-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+build-lib-opencv-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+build-lib-opencv-devel %{_description}

This package contains library source intended for building other packages which
use the "build-lib-opencv" feature of the "%{crate}" crate.

%files       -n %{name}+build-lib-opencv-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+build-lib-openh264-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+build-lib-openh264-devel %{_description}

This package contains library source intended for building other packages which
use the "build-lib-openh264" feature of the "%{crate}" crate.

%files       -n %{name}+build-lib-openh264-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+build-lib-openjpeg-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+build-lib-openjpeg-devel %{_description}

This package contains library source intended for building other packages which
use the "build-lib-openjpeg" feature of the "%{crate}" crate.

%files       -n %{name}+build-lib-openjpeg-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+build-lib-openssl-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+build-lib-openssl-devel %{_description}

This package contains library source intended for building other packages which
use the "build-lib-openssl" feature of the "%{crate}" crate.

%files       -n %{name}+build-lib-openssl-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+build-lib-opus-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+build-lib-opus-devel %{_description}

This package contains library source intended for building other packages which
use the "build-lib-opus" feature of the "%{crate}" crate.

%files       -n %{name}+build-lib-opus-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+build-lib-schroedinger-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+build-lib-schroedinger-devel %{_description}

This package contains library source intended for building other packages which
use the "build-lib-schroedinger" feature of the "%{crate}" crate.

%files       -n %{name}+build-lib-schroedinger-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+build-lib-shine-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+build-lib-shine-devel %{_description}

This package contains library source intended for building other packages which
use the "build-lib-shine" feature of the "%{crate}" crate.

%files       -n %{name}+build-lib-shine-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+build-lib-smbclient-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+build-lib-smbclient-devel %{_description}

This package contains library source intended for building other packages which
use the "build-lib-smbclient" feature of the "%{crate}" crate.

%files       -n %{name}+build-lib-smbclient-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+build-lib-snappy-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+build-lib-snappy-devel %{_description}

This package contains library source intended for building other packages which
use the "build-lib-snappy" feature of the "%{crate}" crate.

%files       -n %{name}+build-lib-snappy-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+build-lib-speex-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+build-lib-speex-devel %{_description}

This package contains library source intended for building other packages which
use the "build-lib-speex" feature of the "%{crate}" crate.

%files       -n %{name}+build-lib-speex-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+build-lib-ssh-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+build-lib-ssh-devel %{_description}

This package contains library source intended for building other packages which
use the "build-lib-ssh" feature of the "%{crate}" crate.

%files       -n %{name}+build-lib-ssh-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+build-lib-stagefright-h264-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+build-lib-stagefright-h264-devel %{_description}

This package contains library source intended for building other packages which
use the "build-lib-stagefright-h264" feature of the "%{crate}" crate.

%files       -n %{name}+build-lib-stagefright-h264-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+build-lib-theora-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+build-lib-theora-devel %{_description}

This package contains library source intended for building other packages which
use the "build-lib-theora" feature of the "%{crate}" crate.

%files       -n %{name}+build-lib-theora-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+build-lib-twolame-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+build-lib-twolame-devel %{_description}

This package contains library source intended for building other packages which
use the "build-lib-twolame" feature of the "%{crate}" crate.

%files       -n %{name}+build-lib-twolame-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+build-lib-utvideo-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+build-lib-utvideo-devel %{_description}

This package contains library source intended for building other packages which
use the "build-lib-utvideo" feature of the "%{crate}" crate.

%files       -n %{name}+build-lib-utvideo-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+build-lib-vmaf-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+build-lib-vmaf-devel %{_description}

This package contains library source intended for building other packages which
use the "build-lib-vmaf" feature of the "%{crate}" crate.

%files       -n %{name}+build-lib-vmaf-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+build-lib-vo-aacenc-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+build-lib-vo-aacenc-devel %{_description}

This package contains library source intended for building other packages which
use the "build-lib-vo-aacenc" feature of the "%{crate}" crate.

%files       -n %{name}+build-lib-vo-aacenc-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+build-lib-vo-amrwbenc-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+build-lib-vo-amrwbenc-devel %{_description}

This package contains library source intended for building other packages which
use the "build-lib-vo-amrwbenc" feature of the "%{crate}" crate.

%files       -n %{name}+build-lib-vo-amrwbenc-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+build-lib-vorbis-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+build-lib-vorbis-devel %{_description}

This package contains library source intended for building other packages which
use the "build-lib-vorbis" feature of the "%{crate}" crate.

%files       -n %{name}+build-lib-vorbis-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+build-lib-vpx-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+build-lib-vpx-devel %{_description}

This package contains library source intended for building other packages which
use the "build-lib-vpx" feature of the "%{crate}" crate.

%files       -n %{name}+build-lib-vpx-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+build-lib-wavpack-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+build-lib-wavpack-devel %{_description}

This package contains library source intended for building other packages which
use the "build-lib-wavpack" feature of the "%{crate}" crate.

%files       -n %{name}+build-lib-wavpack-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+build-lib-webp-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+build-lib-webp-devel %{_description}

This package contains library source intended for building other packages which
use the "build-lib-webp" feature of the "%{crate}" crate.

%files       -n %{name}+build-lib-webp-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+build-lib-x264-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+build-lib-x264-devel %{_description}

This package contains library source intended for building other packages which
use the "build-lib-x264" feature of the "%{crate}" crate.

%files       -n %{name}+build-lib-x264-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+build-lib-x265-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+build-lib-x265-devel %{_description}

This package contains library source intended for building other packages which
use the "build-lib-x265" feature of the "%{crate}" crate.

%files       -n %{name}+build-lib-x265-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+build-lib-xvid-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+build-lib-xvid-devel %{_description}

This package contains library source intended for building other packages which
use the "build-lib-xvid" feature of the "%{crate}" crate.

%files       -n %{name}+build-lib-xvid-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+build-license-gpl-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+build-license-gpl-devel %{_description}

This package contains library source intended for building other packages which
use the "build-license-gpl" feature of the "%{crate}" crate.

%files       -n %{name}+build-license-gpl-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+build-license-nonfree-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+build-license-nonfree-devel %{_description}

This package contains library source intended for building other packages which
use the "build-license-nonfree" feature of the "%{crate}" crate.

%files       -n %{name}+build-license-nonfree-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+build-license-version3-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+build-license-version3-devel %{_description}

This package contains library source intended for building other packages which
use the "build-license-version3" feature of the "%{crate}" crate.

%files       -n %{name}+build-license-version3-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+build-pic-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+build-pic-devel %{_description}

This package contains library source intended for building other packages which
use the "build-pic" feature of the "%{crate}" crate.

%files       -n %{name}+build-pic-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+build-zlib-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+build-zlib-devel %{_description}

This package contains library source intended for building other packages which
use the "build-zlib" feature of the "%{crate}" crate.

%files       -n %{name}+build-zlib-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+codec-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+codec-devel %{_description}

This package contains library source intended for building other packages which
use the "codec" feature of the "%{crate}" crate.

%files       -n %{name}+codec-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+device-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+device-devel %{_description}

This package contains library source intended for building other packages which
use the "device" feature of the "%{crate}" crate.

%files       -n %{name}+device-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+filter-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+filter-devel %{_description}

This package contains library source intended for building other packages which
use the "filter" feature of the "%{crate}" crate.

%files       -n %{name}+filter-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+format-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+format-devel %{_description}

This package contains library source intended for building other packages which
use the "format" feature of the "%{crate}" crate.

%files       -n %{name}+format-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+image-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+image-devel %{_description}

This package contains library source intended for building other packages which
use the "image" feature of the "%{crate}" crate.

%files       -n %{name}+image-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+non-exhaustive-enums-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+non-exhaustive-enums-devel %{_description}

This package contains library source intended for building other packages which
use the "non-exhaustive-enums" feature of the "%{crate}" crate.

%files       -n %{name}+non-exhaustive-enums-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+postprocessing-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+postprocessing-devel %{_description}

This package contains library source intended for building other packages which
use the "postprocessing" feature of the "%{crate}" crate.

%files       -n %{name}+postprocessing-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+rpi-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+rpi-devel %{_description}

This package contains library source intended for building other packages which
use the "rpi" feature of the "%{crate}" crate.

%files       -n %{name}+rpi-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+serde-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+serde-devel %{_description}

This package contains library source intended for building other packages which
use the "serde" feature of the "%{crate}" crate.

%files       -n %{name}+serde-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+serialize-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+serialize-devel %{_description}

This package contains library source intended for building other packages which
use the "serialize" feature of the "%{crate}" crate.

%files       -n %{name}+serialize-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+software-resampling-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+software-resampling-devel %{_description}

This package contains library source intended for building other packages which
use the "software-resampling" feature of the "%{crate}" crate.

%files       -n %{name}+software-resampling-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+software-scaling-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+software-scaling-devel %{_description}

This package contains library source intended for building other packages which
use the "software-scaling" feature of the "%{crate}" crate.

%files       -n %{name}+software-scaling-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+static-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+static-devel %{_description}

This package contains library source intended for building other packages which
use the "static" feature of the "%{crate}" crate.

%files       -n %{name}+static-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
test "%{source0_hash}" = "none" || { f="%{SOURCE0}"; test -f "$f" || { echo "oreon: missing Source0 $f" >&2; exit 1; }; h=$(sha256sum "$f" | awk '{print $1}'); test "$h" = "%{source0_hash}" || { echo "oreon: Source0 hash mismatch" >&2; exit 1; }; }
%autosetup -n %{crate}-%{crate_version} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
%autochangelog
