%global source0_hash 1130d80c7374efad55a117d715a3af9368f0fa7a2c54573afc15a188cd984837

# Generated by rust2rpm 27
%bcond check 1
%global debug_package %{nil}

%global crate kamadak-exif

Name:           rust-kamadak-exif
Version:        0.6.1
Release:        %autorelease
Summary:        Exif parsing library written in pure Rust

License:        BSD-2-Clause
URL:            https://crates.io/crates/kamadak-exif
Source:         %{crates_source}
Patch:          0001-Remove-brittle-expected-panic-message-from-a-test.patch

BuildRequires:  cargo-rpm-macros >= 24

%global _description %{expand:
Exif parsing library written in pure Rust.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
%license %{crate_instdir}/LICENSE
%doc %{crate_instdir}/README
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
test "%{source0_hash}" = "none" || { f="%{SOURCE0}"; test -f "$f" || { echo "oreon: missing Source0 $f" >&2; exit 1; }; h=$(sha256sum "$f" | awk '{print $1}'); test "$h" = "%{source0_hash}" || { echo "oreon: Source0 hash mismatch" >&2; exit 1; }; }

%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
%autochangelog
