%global source0_hash 41fe8c660ae4257887cf66394862d21dbca4a6ddd26f04a3560410406a2f819a

# Generated by rust2rpm 28
%bcond check 0
%global debug_package %{nil}

%global crate toml_edit

Name:           rust-toml_edit0.22
Version:        0.22.27
Release:        %autorelease
Summary:        Yet another format-preserving TOML parser.

License:        MIT OR Apache-2.0
URL:            https://crates.io/crates/toml_edit
Source:         %{crates_source}

BuildRequires:  cargo-rpm-macros >= 24

%global _description %{expand:
Yet another format-preserving TOML parser.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
%license %{crate_instdir}/LICENSE-APACHE
%license %{crate_instdir}/LICENSE-MIT
%doc %{crate_instdir}/README.md
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+display-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+display-devel %{_description}

This package contains library source intended for building other packages which
use the "display" feature of the "%{crate}" crate.

%files       -n %{name}+display-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+kstring-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+kstring-devel %{_description}

This package contains library source intended for building other packages which
use the "kstring" feature of the "%{crate}" crate.

%files       -n %{name}+kstring-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+parse-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+parse-devel %{_description}

This package contains library source intended for building other packages which
use the "parse" feature of the "%{crate}" crate.

%files       -n %{name}+parse-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+perf-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+perf-devel %{_description}

This package contains library source intended for building other packages which
use the "perf" feature of the "%{crate}" crate.

%files       -n %{name}+perf-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+serde-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+serde-devel %{_description}

This package contains library source intended for building other packages which
use the "serde" feature of the "%{crate}" crate.

%files       -n %{name}+serde-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+serde_spanned-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+serde_spanned-devel %{_description}

This package contains library source intended for building other packages which
use the "serde_spanned" feature of the "%{crate}" crate.

%files       -n %{name}+serde_spanned-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+toml_write-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+toml_write-devel %{_description}

This package contains library source intended for building other packages which
use the "toml_write" feature of the "%{crate}" crate.

%files       -n %{name}+toml_write-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+unbounded-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+unbounded-devel %{_description}

This package contains library source intended for building other packages which
use the "unbounded" feature of the "%{crate}" crate.

%files       -n %{name}+unbounded-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+unstable-debug-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+unstable-debug-devel %{_description}

This package contains library source intended for building other packages which
use the "unstable-debug" feature of the "%{crate}" crate.

%files       -n %{name}+unstable-debug-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+winnow-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+winnow-devel %{_description}

This package contains library source intended for building other packages which
use the "winnow" feature of the "%{crate}" crate.

%files       -n %{name}+winnow-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
test "%{source0_hash}" = "none" || { f="%{SOURCE0}"; test -f "$f" || { echo "oreon: missing Source0 $f" >&2; exit 1; }; h=$(sha256sum "$f" | awk '{print $1}'); test "$h" = "%{source0_hash}" || { echo "oreon: Source0 hash mismatch" >&2; exit 1; }; }
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
%autochangelog
