#!/bin/sh

cat >&2 <<EOF
This package is compiled in bootstrap mode and used only to solve circular 
build dependency. You don't want to use this package. It's not expected to
work.

In normal circumstances, you should not see bootstrap package in any 
released Fedora. 
EOF
exit 1

