%global source0_hash 34ed7ef773f7af7b8d8253bd3fac989f3bc8b69c319394eb49c3aa49e55ad015

# Generated by go2rpm 1.16.0
%bcond check 1
%bcond bootstrap 0

%if %{with bootstrap}
%global debug_package %{nil}
%endif

%if %{with bootstrap}
%global __requires_exclude %{?__requires_exclude:%{__requires_exclude}|}^golang\\(.*\\)$
%endif

# https://github.com/bugst/go-serial
%global goipath         go.bug.st/serial
%global forgeurl        https://github.com/bugst/go-serial
Version:                1.6.4

%gometa -L

%global common_description %{expand:
A cross-platform serial library for Golang.}

%global golicenses      LICENSE
%global godocs          README.md

Name:           golang-bug-serial-1
Release:        %autorelease
Summary:        Cross-platform serial library for Golang

License:        BSD-3-Clause
URL:            %{gourl}
Source:         %{gosource}

BuildRequires:  socat

%description %{common_description}

%gopkg

%prep
test "%{source0_hash}" = "none" || { f="%{SOURCE0}"; test -f "$f" || { echo "oreon: missing Source0 $f" >&2; exit 1; }; h=$(sha256sum "$f" | awk '{print $1}'); test "$h" = "%{source0_hash}" || { echo "oreon: Source0 hash mismatch" >&2; exit 1; }; }

%goprep -A
%autopatch -q -p1

%if %{without bootstrap}
%generate_buildrequires
%go_generate_buildrequires
%endif

%if %{without bootstrap}
%build
for cmd in portlist; do
  %gobuild -o %{gobuilddir}/bin/$(basename $cmd) %{goipath}/$cmd
done
%endif

%install
%gopkginstall
%if %{without bootstrap}
install -m 0755 -vd                     %{buildroot}%{_bindir}
install -m 0755 -vp %{gobuilddir}/bin/* %{buildroot}%{_bindir}/
%endif

%if %{without bootstrap}
%if %{with check}
%check
%gocheck
%endif
%endif

%if %{without bootstrap}
%files
%license LICENSE
%doc README.md
%{_bindir}/portlist
%endif

%gopkgfiles

%changelog
%autochangelog
