# packit config for vulkan-headers
# Build Stage 1 - no internal dependencies

jobs:
  - job: koji_build
    trigger: commit
    dist_git_branches:
      - fedora-all
    sidetag_group: vulkan-sdk-releases
    dependents:
      - vulkan-loader
