%global source0_hash 5dbfdc9c3e9275a87f4768cc455db2832c10dc7f2b9703810ff635dbf87c6cf0

# Generated by go2rpm
%bcond check 0

%global debug_package %{nil}

# https://github.com/gorilla/schema
%global goipath         github.com/gorilla/schema
Version:                1.2.0

%gometa

%global common_description %{expand:
Package Schema converts structs to and from form values.}

%global golicenses      LICENSE
%global godocs          README.md

Name:           %{goname}
Release:        %autorelease
Summary:        Fill a struct with form values

# Upstream license specification: BSD-3-Clause
# Automatically converted from old format: BSD - review is highly recommended.
License:        LicenseRef-Callaway-BSD
URL:            %{gourl}
Source0:        %{gosource}

%description
%{common_description}

%gopkg

%prep
test "%{source0_hash}" = "none" || { f="%{SOURCE0}"; test -f "$f" || { echo "oreon: missing Source0 $f" >&2; exit 1; }; h=$(sha256sum "$f" | awk '{print $1}'); test "$h" = "%{source0_hash}" || { echo "oreon: Source0 hash mismatch" >&2; exit 1; }; }

%goprep

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog
%autochangelog
