---
downstream_package_name: jackson-modules-base
specfile_path: jackson-modules-base.spec
upstream_package_name: jackson-modules-base
upstream_project_url: https://github.com/FasterXML/jackson-modules-base
upstream_tag_template: jackson-modules-base-{version}

actions:
  post-upstream-clone:
    - "wget https://src.fedoraproject.org/rpms/jackson-modules-base/raw/main/f/jackson-modules-base.spec -O jackson-modules-base.spec"

jobs:
- job: pull_from_upstream
  trigger: release
  dist_git_branches:
    - fedora-rawhide

# We cannot do koji_build/bodhi_update jobs yet as we need to use
# a side-tag and this is no supported yet. We can add them is this
# issue gets resolved: https://github.com/packit/packit/issues/1870
