%global source0_hash 3a8c3a0a472b3a556e269be64dc65a5c013ba85e940d089367eb8c88f3fdfda9

# Generated by rust2rpm 28
%bcond check 0
%global debug_package %{nil}

%global crate alloc_counter

Name:           rust-alloc_counter
Version:        0.0.4
Release:        %autorelease
Summary:        Count allocations, reallocations, deallocations. Allow, deny, or forb...

License:        MIT OR Apache-2.0
URL:            https://crates.io/crates/alloc_counter
Source:         %{crates_source}

BuildRequires:  cargo-rpm-macros >= 24

%global _description %{expand:
Count allocations, reallocations, deallocations. Allow, deny, or forbid allocations on an expression or function basis.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
%license %{crate_instdir}/LICENSE-APACHE
%license %{crate_instdir}/LICENSE-MIT
%doc %{crate_instdir}/README.md
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+alloc_counter_macro-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+alloc_counter_macro-devel %{_description}

This package contains library source intended for building other packages which
use the "alloc_counter_macro" feature of the "%{crate}" crate.

%files       -n %{name}+alloc_counter_macro-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+macros-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+macros-devel %{_description}

This package contains library source intended for building other packages which
use the "macros" feature of the "%{crate}" crate.

%files       -n %{name}+macros-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+rustdoc-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+rustdoc-devel %{_description}

This package contains library source intended for building other packages which
use the "rustdoc" feature of the "%{crate}" crate.

%files       -n %{name}+rustdoc-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+std-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+std-devel %{_description}

This package contains library source intended for building other packages which
use the "std" feature of the "%{crate}" crate.

%files       -n %{name}+std-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
test "%{source0_hash}" = "none" || { f="%{SOURCE0}"; test -f "$f" || { echo "oreon: missing Source0 $f" >&2; exit 1; }; h=$(sha256sum "$f" | awk '{print $1}'); test "$h" = "%{source0_hash}" || { echo "oreon: Source0 hash mismatch" >&2; exit 1; }; }
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
%autochangelog
