%global source0_hash e8d8428ebcb26e0a5fbdc1c2a4a8c30233d0c147798e0f8acc9b77faf6686045

# Generated by rust2rpm 28
%bcond check 1
%global debug_package %{nil}

%global crate asyncgit

Name:           rust-asyncgit
Version:        0.28.0
Release:        %autorelease
Summary:        Allow using git2 in a asynchronous context

License:        MIT
URL:            https://crates.io/crates/asyncgit
Source:         %{crates_source}

BuildRequires:  cargo-rpm-macros >= 24
%if %{with check}
BuildRequires:  /usr/bin/git
%endif

%global _description %{expand:
Allow using git2 in a asynchronous context.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
%license %{crate_instdir}/LICENSE.md
%doc %{crate_instdir}/README.md
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+trace-libgit-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+trace-libgit-devel %{_description}

This package contains library source intended for building other packages which
use the "trace-libgit" feature of the "%{crate}" crate.

%files       -n %{name}+trace-libgit-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
test "%{source0_hash}" = "none" || { f="%{SOURCE0}"; test -f "$f" || { echo "oreon: missing Source0 $f" >&2; exit 1; }; h=$(sha256sum "$f" | awk '{print $1}'); test "$h" = "%{source0_hash}" || { echo "oreon: Source0 hash mismatch" >&2; exit 1; }; }

%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
# * skip tests which require internet connectivity
%cargo_test -- -- --skip sync::submodules::tests::test_smoke
%endif

%changelog
%autochangelog
