WWW_PORT=8080
SSL_PORT=8443
SSLCERT="/var/lib/domoticz/domoticz.pem"
SSLPASS="<replace>"
SSLMETHOD="tls12_server"
SSLOPTIONS="default_workarounds"
SSLDHPARAM="/var/lib/domoticz/domoticz.pem"
APP_ROOT="/usr/share/domoticz"
DBASE="/var/lib/domoticz/domoticz.db"
USERDATA="/var/lib/domoticz/"
LOGLEVEL="1"

