# Configuration snippet for vdr-live                   -*- sh -*-
#
# Add command line options to pass to the live plugin to PLUGIN_OPTIONS.
# See /usr/share/doc/vdr-live-*/README for info about available options.

PLUGIN_OPTIONS="--ip=127.0.0.1"
