# edg-mkgridmap.conf file contains configuration informations for edg-mkgridmap.

# The default location is /etc/edg-mkgridmap.conf.

# The edg-mkgridmap.conf file is a free-form ASCII text file. It is parsed by the descent parser
# built into edg-mkgridmap. The file may contain extra tabs and white spaces for formatting purposes.
# Keywords in the file are case-insensitive.
# Comments may be placed anywhere within the file (except within quotes).
# Comments begin with the # character and end at the end of the line.

# The file essentially consists of a list of directives composed by a keyword and one or more arguments.
# Optional arguments are put in square brackets.

#  See man edg-gridmap.conf file for details

#  group URI [lcluser]

#  default_lcluser default_lcluser

#  auth URI

#  allow⎪deny pattern_to_match

#  gmf_local grid-mapfile-local

