%global source0_hash d67da1202628d85be00c52d8c5129e493186cad8fbf9abcd0bb58a559a18e7ea

# Generated by go2rpm
# Fixed upstream
%ifnarch %{ix86} %{arm} s390x
%bcond check 0
%endif
%global debug_package %{nil}

# https://github.com/performancecopilot/speed
%global goipath         github.com/performancecopilot/speed
Version:                3.0.1

%gometa

%global common_description %{expand:
Package Speed implements a Golang client for the Performance Co-Pilot
instrumentation API.}

%global golicenses      LICENSE
%global godocs          examples CHANGELOG.md README.md

Name:           %{goname}
Release:        %autorelease
Summary:        Go implementation of the PCP instrumentation API

License:        MIT
URL:            %{gourl}
Source0:        %{gosource}

BuildRequires:  golang(github.com/codahale/hdrhistogram)
BuildRequires:  golang(github.com/edsrzf/mmap-go)
BuildRequires:  golang(github.com/pkg/errors)

%description
%{common_description}

%gopkg

%prep
test "%{source0_hash}" = "none" || { f="%{SOURCE0}"; test -f "$f" || { echo "oreon: missing Source0 $f" >&2; exit 1; }; h=$(sha256sum "$f" | awk '{print $1}'); test "$h" = "%{source0_hash}" || { echo "oreon: Source0 hash mismatch" >&2; exit 1; }; }

%goprep

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog
%autochangelog
