%global source0_hash 6697d21c93468cb7552265b8064f53a4a83125aad2f2adf97598f4c8f8b5dd5c

# Generated by go2rpm 1.9.0
%bcond check 0
%global debug_package %{nil}

# https://github.com/jackc/pgservicefile
%global goipath         github.com/jackc/pgservicefile
%global commit          091c0ba34f0a65a78ab8d0e313fde0695c0f7186

%gometa

%global common_description %{expand:
Pgservicefile is a parser PostgreSQL for service files (e.g. .pg_service.conf).}

%global golicenses      LICENSE
%global godocs          README.md

Name:           %{goname}
Version:        0
Release:        %autorelease -p
Summary:        Parser PostgreSQL for service files

License:        MIT
URL:            %{gourl}
Source0:        %{gosource}

%description %{common_description}

%gopkg

%prep
test "%{source0_hash}" = "none" || { f="%{SOURCE0}"; test -f "$f" || { echo "oreon: missing Source0 $f" >&2; exit 1; }; h=$(sha256sum "$f" | awk '{print $1}'); test "$h" = "%{source0_hash}" || { echo "oreon: Source0 hash mismatch" >&2; exit 1; }; }

%goprep
%autopatch -p1

%generate_buildrequires
%go_generate_buildrequires

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog
%autochangelog
