.TH FFLAS\-FFPACK\-CONFIG "1" "December 2021" "" "User Commands"
.SH NAME
.B fflas\-ffpack\-config
\(en print details about the fflas-ffpack installation
.SH SYNOPSIS
.B fflas\-ffpack\-config
.RI [ OPTION ]
.SH OPTIONS
.TP
.B \-\-prefix
show FFLAS-FFPACK installation prefix
.TP
.B \-\-libs
print library linking information
.TP
.B \-\-blas\-libs
print BLAS library linking information
.TP
.B \-\-cflags
print pre-processor and compiler flags
.TP
.B \-\-blas\-cflags
print BLAS pre-processor and BLAS compiler flags
.TP
.B \-\-blas\-home
print where BLAS were found
.TP
.B \-\-help
display this help and exit
.TP
.B \-\-version
output version information string
.TP
.B \-\-decimal\-version
output version in decimal representation (base 100)
