.TH java-jd-decompiler 1
.SH java-jd-decompiler
decompile FQN which can see on its classpath
.SH SYNOPSIS
.B
CLASSPAHT="dir1:jar1:dir2...:jarN"
java-jd-decompiler
.B
fully/qualified/name
.SH DESCRIPTION
.B java-jd-decompiler		
JD-Core is a standalone JAVA library containing the JAVA decompiler of "Java Decompiler project".
It support Java 1.8.0 to Java 12.0, including Lambda expressions, method references and default methods.
JD-Core is the engine of JD-GUI.
We provide a small wrapper allowing to launch from cmdline, but still we are stuck with CLASSAPTH and FQNs
.SH OPTIONS
.TP
variable CLASSPAHT must contain resources which insides you wish to decompile. Arguemtns are then fuly qualifide names of classes you wish to print out. More sense is to do it one by one.
