%global source0_hash 413775a7eac2261d2211a79d10ef275e5b6f7b527eec42ad09adce2ffa92b6e5

# Generated by rust2rpm 28
%bcond check 1
%global debug_package %{nil}

%global crate parse_datetime

Name:           rust-parse_datetime
Version:        0.14.0
Release:        %autorelease
Summary:        Parsing human-readable time strings and converting them to a DateTime

License:        MIT
URL:            https://crates.io/crates/parse_datetime
Source:         %{crates_source}
# Manually created patch for downstream crate metadata changes
# * exclude renovate.json
Patch:          parse_datetime-fix-metadata.diff

BuildRequires:  cargo-rpm-macros >= 24

%global _description %{expand:
Parsing human-readable time strings and converting them to a DateTime.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
%license %{crate_instdir}/LICENSE
%doc %{crate_instdir}/README.md
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
test "%{source0_hash}" = "none" || { f="%{SOURCE0}"; test -f "$f" || { echo "oreon: missing Source0 $f" >&2; exit 1; }; h=$(sha256sum "$f" | awk '{print $1}'); test "$h" = "%{source0_hash}" || { echo "oreon: Source0 hash mismatch" >&2; exit 1; }; }

%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
# * skip failing tests
%{cargo_test -- -- %{shrink:
    --skip parse_relative_time::tests::test_days
    --skip parse_relative_time::tests::test_direction
    --skip parse_relative_time::tests::test_duration_parsing
    --skip parse_relative_time::tests::test_fortnights
    --skip parse_relative_time::tests::test_hours
    --skip parse_relative_time::tests::test_months
    --skip parse_relative_time::tests::test_relative_days
    --skip parse_datetime_at_date
}}
%endif

%changelog
%autochangelog
