.TH PYTEST\-BDD "1" "June 2025" "" "User Commands"
.SH NAME
.B pytest\-bdd
\(en BDD library for the pytest runner
.SH SYNOPSIS
.B pytest\-bdd
.RB [ \-h ]
.RB { generate , migrate }\ ...
.SH OPTIONS
.SS "POSITIONAL ARGUMENTS"
.TP
.B generate
Generate test code with feature files.
.IP
See
.BR pytest\-bdd\-generate (1).
.TP
.B migrate
Migrate outdated tests to the most recent form.
.IP
See
.BR pytest\-bdd\-migrate (1).
.SS "OPTIONAL ARGUMENTS"
.TP
.B \-h,\ \-\-help
Show a help message and exit
.SH "SEE ALSO"
.BR pytest\-bdd\-generate (1),
.BR pytest\-bdd\-migrate (1)
