.TH PYTEST\-BDD\-GENERATE "1" "November 2022" "" "User Commands"
.SH NAME
.B pytest\-bdd\-generate
\(en Generate test code with feature files
.SH SYNOPSIS
.B pytest\-bdd\-generate
.RB [ \-h ]
.I FEATURE_FILE
.RI [ FEATURE_FILE \ ...]
.SH OPTIONS
.SS "POSITIONAL ARGUMENTS"
.TP
.I FEATURE_FILE
Feature files to generate test code with
.SS "OPTIONAL ARGUMENTS"
.TP
.B \-h,\ \-\-help
Show a help message and exit
.SH "SEE ALSO"
.BR pytest\-bdd (1)
.P
.BR pytest\-bdd\-migrate (1)
