.TH PYTEST\-BDD\-MIGRATE "1" "November 2022" "" "User Commands"
.SH NAME
.B pytest\-bdd\-migrate
\(en Migrate outdated tests to the most recent form
.SH SYNOPSIS
.B pytest\-bdd\-migrate
.RB [ \-h ]
.I PATH
.SH OPTIONS
.SS "POSITIONAL ARGUMENTS"
.TP
.I PATH
Migrate outdated tests to the most recent form
.SS "OPTIONAL ARGUMENTS"
.TP
.B \-h,\ \-\-help
Show a help message and exit
.SH "SEE ALSO"
.BR pytest\-bdd (1)
.P
.BR pytest\-bdd\-generate (1)
