%global source0_hash dce49a371434ab7715f8eff1fbe618c46834a71be828980e60fc1012aabb111d

# Generated by rust2rpm 28
# * tests need crates not packaged in Oreon (or would form a build cycle)
%bcond check 0
%global debug_package %{nil}

%global crate libglycin-rebind

Name:           rust-libglycin-rebind0.2
Version:        0.2.0
Release:        1%{?dist}
Summary:        Safe bindings for libglycin

License:        MIT
URL:            https://crates.io/crates/libglycin-rebind
Source:         %{crates_source}

BuildRequires:  cargo-rpm-macros >= 24

%global _description %{expand:
Safe bindings for libglycin.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
%license %{crate_instdir}/LICENSE
%doc %{crate_instdir}/README.md
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+v2_2-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+v2_2-devel %{_description}

This package contains library source intended for building other packages which
use the "v2_2" feature of the "%{crate}" crate.

%files       -n %{name}+v2_2-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
test "%{source0_hash}" = "none" || { f="%{SOURCE0}"; test -f "$f" || { echo "oreon: missing Source0 $f" >&2; exit 1; }; h=$(sha256sum "$f" | awk '{print $1}'); test "$h" = "%{source0_hash}" || { echo "oreon: Source0 hash mismatch" >&2; exit 1; }; }
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
%autochangelog
