%global source0_hash 68d8ad5cfac469e58e632590f033d45c66415ef7a8aa801409884818036706f5

# Generated by rust2rpm 28
%bcond check 0
%global debug_package %{nil}

%global crate cap-tempfile

Name:           rust-cap-tempfile
Version:        3.4.5
Release:        %autorelease
Summary:        Capability-based temporary directories

License:        Apache-2.0 WITH LLVM-exception OR Apache-2.0 OR MIT
URL:            https://crates.io/crates/cap-tempfile
Source:         %{crates_source}
Patch:          cap-tempfile-fix-metadata-auto.diff

BuildRequires:  cargo-rpm-macros >= 24

%global _description %{expand:
Capability-based temporary directories}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
%license %{crate_instdir}/COPYRIGHT
%license %{crate_instdir}/LICENSE-APACHE
%license %{crate_instdir}/LICENSE-Apache-2.0_WITH_LLVM-exception
%license %{crate_instdir}/LICENSE-MIT
%doc %{crate_instdir}/README.md
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+arf_strings-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+arf_strings-devel %{_description}

This package contains library source intended for building other packages which
use the "arf_strings" feature of the "%{crate}" crate.

%files       -n %{name}+arf_strings-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+camino-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+camino-devel %{_description}

This package contains library source intended for building other packages which
use the "camino" feature of the "%{crate}" crate.

%files       -n %{name}+camino-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+fs_utf8-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+fs_utf8-devel %{_description}

This package contains library source intended for building other packages which
use the "fs_utf8" feature of the "%{crate}" crate.

%files       -n %{name}+fs_utf8-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
test "%{source0_hash}" = "none" || { f="%{SOURCE0}"; test -f "$f" || { echo "oreon: missing Source0 $f" >&2; exit 1; }; h=$(sha256sum "$f" | awk '{print $1}'); test "$h" = "%{source0_hash}" || { echo "oreon: Source0 hash mismatch" >&2; exit 1; }; }
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
%autochangelog
