# Configuration snippet for vdr-osd2web                           -*- sh -*-
#
# Add command line options to pass to the graphlcd plugin to PLUGIN_OPTIONS.
# See /usr/share/doc/vdr-osd2web/README for info about available options.

PLUGIN_OPTIONS=""
