%global source0_hash c880a97d28a3681c0267bd29cff89621202715b065127cd445fa0f0fe0aa2880

# Generated by rust2rpm 27
%bcond check 1
%global debug_package %{nil}

%global crate allocator-api2

Name:           rust-allocator-api2
Version:        0.4.0
Release:        %autorelease
Summary:        Mirror of Rust's allocator API

License:        MIT OR Apache-2.0
URL:            https://crates.io/crates/allocator-api2
Source:         %{crates_source}

BuildRequires:  cargo-rpm-macros >= 24

%global _description %{expand:
Mirror of Rust's allocator API.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
%license %{crate_instdir}/LICENSE-APACHE
%license %{crate_instdir}/LICENSE-MIT
%doc %{crate_instdir}/CHANGELOG.md
%doc %{crate_instdir}/README.md
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+alloc-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+alloc-devel %{_description}

This package contains library source intended for building other packages which
use the "alloc" feature of the "%{crate}" crate.

%files       -n %{name}+alloc-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+fresh-rust-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+fresh-rust-devel %{_description}

This package contains library source intended for building other packages which
use the "fresh-rust" feature of the "%{crate}" crate.

%files       -n %{name}+fresh-rust-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+serde-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+serde-devel %{_description}

This package contains library source intended for building other packages which
use the "serde" feature of the "%{crate}" crate.

%files       -n %{name}+serde-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+std-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+std-devel %{_description}

This package contains library source intended for building other packages which
use the "std" feature of the "%{crate}" crate.

%files       -n %{name}+std-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+serde_core-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+serde_core-devel %{_description}

This package contains library source intended for building other packages which
use the "serde_core" feature of the "%{crate}" crate.

%files       -n %{name}+serde_core-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
test "%{source0_hash}" = "none" || { f="%{SOURCE0}"; test -f "$f" || { echo "oreon: missing Source0 $f" >&2; exit 1; }; h=$(sha256sum "$f" | awk '{print $1}'); test "$h" = "%{source0_hash}" || { echo "oreon: Source0 hash mismatch" >&2; exit 1; }; }

%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
# * skip doctests which don't compile on stable Rust with RUSTC_BOOTSTRAP=1
%{cargo_test -- -- %{shrink:
    --skip "src/stable/boxed.rs"
    --skip "src/stable/vec/mod.rs"
}}
%endif

%changelog
%autochangelog
