%global source0_hash 93a196015c1ff42ac4dff2f363278fd0594002f81a572f9ba9147b66f8bfbb08

# Generated by go2rpm
%bcond check 0

%global debug_package %{nil}

# https://github.com/xeonx/timeago
%global goipath         github.com/xeonx/timeago
Version:                1.0.0
%global tag             v1.0.0-rc4
%global distprefix      %{nil}

%gometa

%global common_description %{expand:
Timeago allows the formatting of time in terms of fuzzy timestamps}

%global golicenses      LICENSE
%global godocs          README.md

Name:           %{goname}
Release:        %autorelease
Summary:        Go package for time formating based on current time

License:        MIT
URL:            %{gourl}
Source0:        %{gosource}

%description
%{common_description}

%gopkg

%prep
test "%{source0_hash}" = "none" || { f="%{SOURCE0}"; test -f "$f" || { echo "oreon: missing Source0 $f" >&2; exit 1; }; h=$(sha256sum "$f" | awk '{print $1}'); test "$h" = "%{source0_hash}" || { echo "oreon: Source0 hash mismatch" >&2; exit 1; }; }

%goprep

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog
%autochangelog
