%global source0_hash 832b69ac8c9e094825c9dd3614c4e5cda30fed0317009203ec956152ade66702

%if 0%{?fedora} >= 36 || 0%{?rhel} > 9 || (0%{?oreon} >= 11)
%global dict_dirname hunspell
%else
%global dict_dirname myspell
%endif

Name: hunspell-gv
Summary: Manx hunspell dictionaries
%global upstreamid 20040505
Version: 0.%{upstreamid}
Release: 37%{?dist}
# This source is generated by generate-source.sh using aspell dictionary
Source: hunspell-gv-0.50.tar.bz2
URL: http://ftp.gnu.org/gnu/aspell/dict/gv
License: GPL-1.0-or-later
BuildArch: noarch

Requires: hunspell-filesystem
Supplements: (hunspell and langpacks-gv)

%description
Manx hunspell dictionaries.

%prep
%(test "%{source0_hash}" = "none" || { f="%{SOURCE0}"; test -f "$f" || { echo "oreon: missing Source0 $f" >&2; exit 1; }; h=$(sha256sum "$f" | awk '{print $1}'); test "$h" = "%{source0_hash}" || { echo "oreon: Source0 hash mismatch" >&2; exit 1; }; })
%setup -q -n hunspell-gv-0.50

%build
# nothing to build here

%install
mkdir -p $RPM_BUILD_ROOT/%{_datadir}/%{dict_dirname}
cp -p *.dic *.aff $RPM_BUILD_ROOT/%{_datadir}/%{dict_dirname}


%files
%doc COPYING Copyright README Crawler.txt
%{_datadir}/%{dict_dirname}/*

%changelog
* Mon May 25 2026 Oreon Packaging Team <packaging@oreonhq.com> - 0.20040505-37
- Import
