.TH PACHI 6 "" "The Debian Project" ""
.
.SH NAME
.
Pachi \- Platform game featuring Pachi el marciano
.
.SH SYNOPSIS
.
.B pachi
.
.SH DESCRIPTION
.
Pachi came from Mars and crashlanded in our planet because of an accident
with his U.F.O.
.
.SH AUTHORS
.
.nf
Santiago Radeff <T-1000@Bigfoot.com>,
Nicolas Radeff <achala@softhome.net>,
Peter Hajba <www.futurecrew.com/skaven>
.fi
