#######################################################################
# Before running pintod service the Pinto repository has to be created.
# To do it run
#    pinto init /path/to/repository
#
PINTOD_OPTIONS='--root=/var/pinto'
