<?xml version="1.0"?>
<!--
   Licensed to the Apache Software Foundation (ASF) under one or more
   contributor license agreements.  See the NOTICE file distributed with
   this work for additional information regarding copyright ownership.
   The ASF licenses this file to You under the Apache License, Version 2.0
   (the "License"); you may not use this file except in compliance with
   the License.  You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.
-->
<project
    xmlns="http://maven.apache.org/POM/4.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
  <parent>
    <groupId>org.apache.commons</groupId>
    <artifactId>commons-parent</artifactId>
    <version>15</version>
  </parent>
  <modelVersion>4.0.0</modelVersion>
  <groupId>commons-modeler</groupId>
  <artifactId>commons-modeler</artifactId>
  <version>2.0.1</version>
  <name>Commons Modeler</name>
  <inceptionYear>2002</inceptionYear>
  <description>
      Commons Modeler makes the process of setting up JMX (Java
      Management Extensions) MBeans easier by configuring the required meta
      data using an XML descriptor. In addition, Modeler provides a factory
      mechanism to create the actual Model MBean instances. 
  </description>
  <url>http://commons.apache.org/proper/commons-modeler/</url>

  <issueManagement>
    <system>jira</system>
    <url>http://issues.apache.org/jira/browse/MODELER</url>
  </issueManagement>

  <scm>
    <connection>scm:svn:http://svn.apache.org/repos/asf/commons/proper/modeler/trunk</connection>
    <developerConnection>scm:svn:https://svn.apache.org/repos/asf/commons/proper/modeler/trunk</developerConnection>
    <url>http://svn.apache.org/viewvc/commons/proper/modeler/trunk</url>
  </scm>

  <developers>
    <developer>
      <name>Craig McClanahan</name>
      <id>craigmcc</id>
      <email>craigmcc@apache.org</email>
      <organization>Apache</organization>
    </developer>

    <developer>
      <name>Yoav Shapira</name>
      <id>yoavs</id>
      <email>yoavs@apache.org</email>
      <organization>Apache</organization>
    </developer>

    <developer>
      <name>Bill Barker</name>
      <id>billbarker</id>
      <email>billbarker@apache.org</email>
      <organization>Apache</organization>
    </developer>

    <developer>
      <name>Davanum Srinivas</name>
      <id>dims</id>
      <email>dims@apache.org</email>
      <organization>Apache</organization>
    </developer>
  </developers>

  <dependencies>
    <dependency>
      <groupId>commons-digester</groupId>
      <artifactId>commons-digester</artifactId>
      <version>1.4.1</version>
    </dependency>

    <dependency>
      <groupId>commons-logging</groupId>
      <artifactId>commons-logging-api</artifactId>
      <version>1.0.4</version>
    </dependency>

    <dependency>
      <groupId>mx4j</groupId>
      <artifactId>mx4j-jmx</artifactId>
      <version>2.1.1</version>
      <scope>provided</scope>
    </dependency>

    <dependency>
      <groupId>xml-apis</groupId>
      <artifactId>xml-apis</artifactId>
      <version>2.0.2</version>
      <scope>provided</scope>
    </dependency>

    <dependency>
      <groupId>junit</groupId>
      <artifactId>junit</artifactId>
      <version>3.8.1</version>
      <scope>test</scope>
    </dependency>

    <dependency>
      <groupId>ant</groupId>
      <artifactId>ant</artifactId>
      <version>1.5</version>
      <optional>true</optional>
    </dependency>
  </dependencies>

  <properties>
    <commons.componentid>modeler</commons.componentid>
    <commons.release.version>2.0.1</commons.release.version>
    <commons.binary.suffix></commons.binary.suffix>
    <commons.jira.id>MODELER</commons.jira.id>
    <commons.jira.pid>12310486</commons.jira.pid>
  </properties> 

  <build>
    <sourceDirectory>src/java</sourceDirectory>
    <testSourceDirectory>src/test</testSourceDirectory>
    <resources>
      <resource>
        <directory>.</directory>
        <targetPath>META-INF</targetPath>
        <includes>
          <include>NOTICE.txt</include>
          <include>LICENSE.txt</include>
        </includes>
      </resource>
      <resource>
        <directory>src/java/org/apache/commons/modeler/ant</directory>
        <targetPath>META-INF</targetPath>
        <includes>
          <include>ant.properties</include>
        </includes>
      </resource>
      <resource>
        <directory>src/java</directory>
        <targetPath>META-INF</targetPath>
        <includes>
          <include>**/ant.properties</include>
          <include>**/mbeans-descriptors.dtd</include>
        </includes>
      </resource>
    </resources>

    <testResources>
      <testResource>
        <directory>src/test</directory>
        <filtering>false</filtering>
        <includes>
          <include>**/*.xml</include>
        </includes>
      </testResource>
    </testResources>

    <plugins>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-surefire-plugin</artifactId>
        <configuration>
          <includes>
            <include>**/*TestCase.java</include>
          </includes>
        </configuration>
      </plugin>
      <plugin>
        <artifactId>maven-assembly-plugin</artifactId>
        <configuration>
          <descriptors>
            <descriptor>src/assembly/bin.xml</descriptor>
            <descriptor>src/assembly/src.xml</descriptor>
          </descriptors>
          <tarLongFileMode>gnu</tarLongFileMode>
        </configuration>
      </plugin>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-scm-publish-plugin</artifactId>
        <configuration>
          <ignorePathsToDelete>
            <ignorePathToDelete>javadocs</ignorePathToDelete>
          </ignorePathsToDelete>
        </configuration>
      </plugin>
<!-- copied from parent to be modified-->
          <plugin>
            <groupId>org.moditect</groupId>
            <artifactId>moditect-maven-plugin</artifactId>
            <version>${commons.moditect-maven-plugin.version}</version>
            <executions>
              <execution>
                <id>add-module-infos</id>
                <phase>package</phase>
                <goals>
                  <goal>add-module-info</goal>
                </goals>
                <configuration>
                  <jvmVersion>${moditect.java.version}</jvmVersion>
                  <jdepsExtraArgs>
<!-- added config--><arg>--ignore-missing-deps</arg> <!-- added config-->
                    <arg>--multi-release=${moditect.java.version}</arg>
                  </jdepsExtraArgs>
                  <outputDirectory>${project.build.directory}</outputDirectory>
                  <overwriteExistingFiles>true</overwriteExistingFiles>
                  <failOnWarning>false</failOnWarning>
                  <module>
                    <moduleInfo>
                      <name>${commons.module.name}</name>
                      <addServiceUses>${commons.moditect-maven-plugin.addServiceUses}</addServiceUses>
                    </moduleInfo>
                  </module>
                </configuration>
              </execution>
            </executions>
          </plugin>
    </plugins>
  </build>

  <reporting>
    <plugins>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-changes-plugin</artifactId>
        <version>2.0</version>
        <configuration>
          <xmlPath>${basedir}/xdocs/changes.xml</xmlPath>
          <issueLinkTemplate>%URL%/%ISSUE%</issueLinkTemplate>
        </configuration>
        <reportSets>
          <reportSet>
            <reports>
               <report>changes-report</report>
            </reports>
          </reportSet>
        </reportSets>
      </plugin>
    </plugins>
  </reporting>

</project>
