d /run/amavisd 755 amavis amavis -
d /run/clamd.amavisd 770 amavis clamupdate -

# Directory cleanup
d /var/spool/amavisd/quarantine 750 amavis amavis 30d
d /var/spool/amavisd/tmp 750 amavis amavis 1d
