%global source0_hash 59e562eb1e28aaa9dec53f3f5747470077fbfa42311baa8c4a4fe64c721bb968

# Generated by go2rpm 1.9.0
%bcond check 0
%global debug_package %{nil}

# https://gitlab.com/cznic/memory
%global goipath         modernc.org/memory
%global forgeurl        https://gitlab.com/cznic/memory
Version:                1.8.0
%global tag             v%{version}

%gometa -f

%global common_description %{expand:
A memory allocator.}

%global golicenses      LICENSE LICENSE-GO LICENSE-MMAP-GO
%global godocs          AUTHORS CONTRIBUTORS README.md

Name:           %{goname}
Release:        %autorelease
Summary:        A memory allocator

License:        BSD-3-Clause
URL:            %{gourl}
Source:         %{gosource}

%description %{common_description}

%gopkg

%prep
test "%{source0_hash}" = "none" || { f="%{SOURCE0}"; test -f "$f" || { echo "oreon: missing Source0 $f" >&2; exit 1; }; h=$(sha256sum "$f" | awk '{print $1}'); test "$h" = "%{source0_hash}" || { echo "oreon: Source0 hash mismatch" >&2; exit 1; }; }

%goprep
%autopatch -p1

%generate_buildrequires
%go_generate_buildrequires

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog
%autochangelog
