.TH SYLPHEED 1 "Nov 22 2004"
.SH NAME
.B sylpheed
\- a GTK+ based, lightweight, and fast email client

.SH SYNOPSIS
.B sylpheed [options]...

.SH DESCRIPTION
\fIsylpheed\fP is an X based fast email client.

.SH OPTIONS
.TP
.B \-\-compose [ADDRESS]
Open the composition window.
.TP
.B \-\-attach [FILE [FILE]...]
Open the composition window with FILE attached.
.TP
.B \-\-receive
Receive the new messages from the server.
.TP
.B \-\-receive-all
Receive the new messages of all accounts from the servers.
.TP
.B \-\-send
Send all queued messages.
.TP
.B \-\-status [FOLDER]
Show the total number of the message.
.TP
.B \-\-status\-full [FOLDER]
Show the status of each folder
.TP
.B \-\-debug
Enter the debug mode.
.TP
.B \-\-help
Show this message.
.TP
.B \-\-version
Show the version.

.SH SEE ALSO
more documentations are available on /usr/share/sylpheed/manual/ and /usr/share/sylpheed/faq/.

.SH AUTHOR
This manual page was written by Akira TAGOH <tagoh@redhat.com>.
