%global source0_hash 5d629d0e517ee46ef705d3b507ca824f5bc84306f9b3ae8844370cb1f6647648

# Generated by go2rpm
%bcond check 0

%global debug_package %{nil}

# https://github.com/revel/config
%global goipath         github.com/revel/config
Version:                1.1.0

%gometa

%global common_description %{expand:
This package implements a basic configuration file parser language which
provides a structure similar to what you would find on Microsoft Windows INI
files.}

%global godocs          README.md Doc

Name:           %{goname}
Release:        %autorelease
Summary:        Configuration file parser for INI format

# https://github.com/revel/config/issues/13
License:        MPL-2.0
URL:            %{gourl}
Source0:        %{gosource}

%description
%{common_description}

%gopkg

%prep
test "%{source0_hash}" = "none" || { f="%{SOURCE0}"; test -f "$f" || { echo "oreon: missing Source0 $f" >&2; exit 1; }; h=$(sha256sum "$f" | awk '{print $1}'); test "$h" = "%{source0_hash}" || { echo "oreon: Source0 hash mismatch" >&2; exit 1; }; }

%goprep

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog
%autochangelog
