%global source0_hash 275919987b4fc2d8735f2e706db0b393580dd79aed9a3e1913ffb64e82c0ae19

# Generated by go2rpm 1.10.0
%bcond check 0
%global debug_package %{nil}

# https://github.com/skeema/knownhosts
%global goipath         github.com/skeema/knownhosts
Version:                1.3.3

%gometa -L -f

%global common_description %{expand:
Go SSH known_hosts wrapper with host key lookup.}

%global golicenses      LICENSE NOTICE
%global godocs          README.md

Name:           golang-github-skeema-knownhosts
Release:        %autorelease
Summary:        Go SSH known_hosts wrapper with host key lookup

License:        Apache-2.0
URL:            %{gourl}
Source:         %{gosource}

%description %{common_description}

%gopkg

%prep
test "%{source0_hash}" = "none" || { f="%{SOURCE0}"; test -f "$f" || { echo "oreon: missing Source0 $f" >&2; exit 1; }; h=$(sha256sum "$f" | awk '{print $1}'); test "$h" = "%{source0_hash}" || { echo "oreon: Source0 hash mismatch" >&2; exit 1; }; }

%goprep -A
%autopatch -p1

%generate_buildrequires
%go_generate_buildrequires

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog
%autochangelog
