# Configuration snippet for vdr-tvguide                   -*- sh -*-
#
# Add command line options to pass to the tvguide plugin to PLUGIN_OPTIONS.
# See /usr/share/doc/vdr-tvguide/README for info about available options.

PLUGIN_OPTIONS="--logopath=/usr/share/vdr/plugins/tvguide/channellogos/ --epgimages=/usr/share/vdr/plugins/tvguide/epgimages/ --iconpath=/usr/share/vdr/plugins/tvguide/epgimages/"
