.TH PYDICOM\-HELP "1" "September 2024" "" "User Commands"
.SH NAME
.B pydicom\-help
\(en Display help for subcommands
.SH SYNOPSIS
.B pydicom help
.RB [ \-h ]
.RI [ subcommand ]
.SH OPTIONS
.SS "POSITIONAL\ ARGUMENTS"
.TP
.I subcommand
Subcommand to show help for
.SS "OPTIONAL\ ARGUMENTS"
.TP
.B \-h\fR, \fB\-\-help
Show a help message and exit
.SH "SEE\ ALSO"
.BR pydicom (1)
.P
.\" .BR pydicom\-help (1),
.BR pydicom\-codify (1),
.BR pydicom\-show (1)
