.TH HATCH\-DEP\-HASH "1" "October 2022" "" "User Commands"
.SH NAME
.B hatch\ dep\ hash
\(en Output a hash of the currently defined dependencies
.SH SYNOPSIS
.B hatch\ dep\ hash
.RI [ OPTIONS ]
.SH OPTIONS
.TP
.B \-p\fR, \fB\-\-project\-only
Whether or not to exclude environment dependencies
.TP
.B \-e\fR, \fB\-\-env\-only
Whether or not to exclude project dependencies
.TP
.B \-h\fR, \fB\-\-help
Show a help message and exit
.SH "SEE ALSO"
.BR hatch\-dep\-show (1)
.P
.BR hatch\-dep (1),
.BR hatch (1)
