.TH HATCH\-SELF\-RESTORE "1" "August 2024" "" "User Commands"
.SH NAME
.B hatch\ self\ restore
\(en Restore the installation
.SH SYNOPSIS
.B hatch\ self\ restore
.RI [ OPTIONS ]
.SH OPTIONS
.B \-h\fR, \fB\-\-help
Show a help message and exit
.SH "SEE ALSO"
.BR hatch\-self\-report (1),
.BR hatch\-self\-update (1)
.P
.BR hatch\-self (1),
.BR hatch (1)
