.TH HATCH\-PROJECT "1" "August 2024" "" "User Commands"
.SH NAME
.B hatch\ project
\(en View project information
.SH SYNOPSIS
.B hatch\ project
.RI [ OPTIONS ]
.I COMMAND
.RI [ ARGS ]...
.SH OPTIONS
.TP
.B \-h\fR, \fB\-\-help
Show a help message and exit
.SS "COMMANDS"
.TP
.B metadata
Display project metadata
.IP
See
.BR hatch\-project\-metadata (1).
.SH "SEE ALSO"
.BR hatch\-project\-metadata (1)
.P
.BR hatch\-build (1),
.BR hatch\-clean (1),
.BR hatch\-config (1),
.BR hatch\-dep (1),
.BR hatch\-env (1),
.BR hatch\-fmt (1),
.BR hatch\-new (1),
.BR hatch\-publish (1),
.BR hatch\-python (1),
.BR hatch\-run (1),
.BR hatch\-self (1),
.BR hatch\-shell (1),
.BR hatch\-status (1),
.BR hatch\-test (1),
.BR hatch\-version (1)
.P
.BR hatch (1)
