.TH HATCH\-SELF\-UPDATE "1" "August 2024" "" "User Commands"
.SH NAME
.B hatch\ self\ update
\(en Install the latest version
.SH SYNOPSIS
.B hatch\ self\ update
.RI [ OPTIONS ]
.SH OPTIONS
.B \-h\fR, \fB\-\-help
Show a help message and exit
.SH "SEE ALSO"
.BR hatch\-self\-restore (1),
.BR hatch\-self\-report (1)
.P
.BR hatch\-self (1),
.BR hatch (1)
