.TH HATCH\-CONFIG\-FIND "1" "October 2022" "" "User Commands"
.SH NAME
.B hatch\ config\ find
\(en Show the location of the config file
.SH SYNOPSIS
.B hatch\ config\ find
.RI [ OPTIONS ]
.SH OPTIONS
.TP
.B \-c\fR, \fB\-\-copy
Copy the path to the config file to the clipboard
.TP
.B \-h\fR, \fB\-\-help
Show a help message and exit
.SH "SEE ALSO"
.BR hatch\-config\-explore (1),
.BR hatch\-config\-restore (1),
.BR hatch\-config\-set (1),
.BR hatch\-config\-show (1),
.BR hatch\-config\-update (1)
.P
.BR hatch\-config (1),
.BR hatch (1)
