.TH HATCH\-CONFIG\-EXPLORE "1" "October 2022" "" "User Commands"
.SH NAME
.B hatch\ config\ explore
\(en Open the config location in your file manager
.SH SYNOPSIS
.B hatch\ config\ explore
.RI [ OPTIONS ]
.SH OPTIONS
.TP
.B \-h\fR, \fB\-\-help
Show a help message and exit
.SH "SEE ALSO"
.BR hatch\-config\-find (1),
.BR hatch\-config\-restore (1),
.BR hatch\-config\-set (1),
.BR hatch\-config\-show (1),
.BR hatch\-config\-update (1)
.P
.BR hatch\-config (1),
.BR hatch (1)
