.TH HATCH\-CONFIG\-SHOW "1" "October 2022" "" "User Commands"
.SH NAME
.B hatch\ config\ show
\(en Show the contents of the config file
.SH SYNOPSIS
.B hatch\ config\ show
.RI [ OPTIONS ]
.SH OPTIONS
.TP
.B \-a\fR, \fB\-\-all
Do not scrub secret fields
.TP
.B \-h\fR, \fB\-\-help
Show a help message and exit
.SH "SEE ALSO"
.BR hatch\-config\-explore (1),
.BR hatch\-config\-find (1),
.BR hatch\-config\-restore (1),
.BR hatch\-config\-set (1),
.BR hatch\-config\-update (1)
.P
.BR hatch\-config (1),
.BR hatch (1)
