.TH HATCH\-FMT "1" "August 2024" "" "User Commands"
.SH NAME
.B hatch\ fmt
\(en Format and lint source code
.SH SYNOPSIS
.B hatch\ fmt
.RI [ OPTIONS ]
.RI [ ARGS ]...
.SH OPTIONS
.TP
.B \-\-check
Only check for errors rather than fixing them
.TP
.B \-l\fR, \fB\-\-linter
Only run the linter
.TP
.B \-f\fR, \fB\-\-formatter
Only run the formatter
.TP
.B \-\-sync
Sync the default config file
with the current version of Hatch
.TP
.B \-h\fR, \fB\-\-help
Show a help message and exit
.SH "SEE ALSO"
.BR hatch\-build (1),
.BR hatch\-clean (1),
.BR hatch\-config (1),
.BR hatch\-dep (1),
.BR hatch\-env (1),
.BR hatch\-new (1),
.BR hatch\-project (1),
.BR hatch\-publish (1),
.BR hatch\-python (1),
.BR hatch\-run (1),
.BR hatch\-self (1),
.BR hatch\-shell (1),
.BR hatch\-status (1),
.BR hatch\-test (1),
.BR hatch\-version (1)
.P
.BR hatch (1)
