.TH HATCH\-PYTHON\-FIND "1" "December 2023" "" "User Commands"
.SH NAME
.B hatch\ python\ find
\(en Locate Python binaries
.SH SYNOPSIS
.B hatch\ python\ find
.RI [ OPTIONS ]
.RI [ NAME ]
.SH OPTIONS
.TP
.B \-p\fR, \fB\-\-parent
Show the parent directory of the Python binary
.TP
.B \-d\fR, \fB\-\-dir\ \fITEXT
The directory in which distributions reside
.TP
.B \-h\fR, \fB\-\-help
Show a help message and exit
.SH "SEE ALSO"
.BR hatch\-python\-install (1),
.BR hatch\-python\-remove (1),
.BR hatch\-python\-show (1),
.BR hatch\-python\-update (1)
.P
.BR hatch\-python (1),
.BR hatch (1)
