.TH HATCH\-ENV\-FIND "1" "October 2022" "" "User Commands"
.SH NAME
.B hatch\ env\ find
\(en Locate environments
.SH SYNOPSIS
.B hatch\ env\ find
.RI [ OPTIONS ]
.RI [ ENV_NAME ]
.SH OPTIONS
.TP
.B \-h\fR, \fB\-\-help
Show a help message and exit
.SH "SEE ALSO"
.BR hatch\-env\-create (1),
.BR hatch\-env\-prune (1),
.BR hatch\-env\-remove (1),
.BR hatch\-env\-run (1),
.BR hatch\-env\-show (1)
.P
.BR hatch\-env (1),
.BR hatch (1)
