.TH HATCH\-DEP\-SHOW "1" "October 2022" "" "User Commands"
.SH NAME
.B hatch\ dep\ show
\(en Display dependencies in various formats
.SH SYNOPSIS
.B hatch\ dep\ show
.RI [ OPTIONS ]
.I COMMAND
.RI [ ARGS ]...
.SH OPTIONS
.TP
.B \-h\fR, \fB\-\-help
Show a help message and exit
.SS "COMMANDS"
.TP
.B requirements
Enumerate dependencies as a list of requirements
.TP
.B table
Enumerate dependencies in a tabular format
.SH "SEE ALSO"
.BR hatch\-dep\-show\-requirements (1),
.BR hatch\-dep\-show\-table (1)
.P
.BR hatch\-dep\-hash (1)
.P
.BR hatch\-dep (1),
.BR hatch (1)
