.TH HATCH\-VERSION "1" "August 2024" "" "User Commands"
.SH NAME
.B hatch\ version
\(en View or set a project\(cqs version
.SH SYNOPSIS
.B hatch\ version
.RI [ OPTIONS ]
.RI [ DESIRED_VERSION ]
.SH OPTIONS
.TP
.B \-h\fR, \fB\-\-help
Show a help message and exit
.SH "SEE ALSO"
.BR hatch\-build (1),
.BR hatch\-clean (1),
.BR hatch\-config (1),
.BR hatch\-dep (1),
.BR hatch\-env (1),
.BR hatch\-fmt (1),
.BR hatch\-new (1),
.BR hatch\-project (1),
.BR hatch\-publish (1),
.BR hatch\-python (1),
.BR hatch\-run (1),
.BR hatch\-self (1),
.BR hatch\-shell (1),
.BR hatch\-status (1)
.BR hatch\-test (1)
.P
.BR hatch (1)
