.TH HATCH\-ENV\-SHOW "1" "August 2024" "" "User Commands"
.SH NAME
.B hatch\ env\ show
\(en Show the available environments
.SH SYNOPSIS
.B hatch\ env\ show
.RI [ OPTIONS ]
.RI [ ENVS ]...
.SH OPTIONS
.TP
.B \-\-ascii
Whether or not to only use ASCII characters
.TP
.B \-\-json
Whether or not to output in JSON format
.TP
.B \-i\fR, \fB\-\-internal
Show internal environments
.TP
.B \-h\fR, \fB\-\-help
Show a help message and exit
.SH "SEE ALSO"
.BR hatch\-env\-create (1),
.BR hatch\-env\-find (1),
.BR hatch\-env\-prune (1),
.BR hatch\-env\-remove (1),
.BR hatch\-env\-run (1)
.P
.BR hatch\-env (1),
.BR hatch (1)
