.TH HATCH\-CONFIG "1" "August 2024" "" "User Commands"
.SH NAME
.B hatch\ config
\(en Manage the config file
.SH SYNOPSIS
.B hatch\ config
.RI [ OPTIONS ]
.I COMMAND
.RI [ ARGS ]...
.SH OPTIONS
.TP
.B \-h\fR, \fB\-\-help
Show a help message and exit
.SS "COMMANDS"
.TP
.B explore
Open the config location in your file manager
.IP
See
.BR hatch\-config\-explore (1).
.TP
.B find
Show the location of the config file
.IP
See
.BR hatch\-config\-find (1).
.TP
.B restore
Restore the config file to default settings
.IP
See
.BR hatch\-config\-restore (1).
.TP
.B set
Assign values to config file entries
.IP
See
.BR hatch\-config\-set (1).
.TP
.B show
Show the contents of the config file
.IP
See
.BR hatch\-config\-show (1).
.TP
.B update
Update the config file with any new fields
.IP
See
.BR hatch\-config\-update (1).
.SH "SEE ALSO"
.BR hatch\-config\-explore (1),
.BR hatch\-config\-find (1),
.BR hatch\-config\-restore (1),
.BR hatch\-config\-set (1),
.BR hatch\-config\-show (1),
.BR hatch\-config\-update (1)
.P
.BR hatch\-build (1),
.BR hatch\-clean (1),
.BR hatch\-dep (1),
.BR hatch\-env (1),
.BR hatch\-fmt (1),
.BR hatch\-new (1),
.BR hatch\-project (1),
.BR hatch\-publish (1),
.BR hatch\-python (1),
.BR hatch\-run (1),
.BR hatch\-self (1),
.BR hatch\-shell (1),
.BR hatch\-status (1),
.BR hatch\-test (1),
.BR hatch\-version (1)
.P
.BR hatch (1)
