.TH HATCH\-PYTHON "1" "August 2024" "" "User Commands"
.SH NAME
.B hatch\ python
\(en Manage Python installations
.SH SYNOPSIS
.B hatch\ python
.RI [ OPTIONS ]
.I COMMAND
.RI [ ARGS ]...
.SH OPTIONS
.TP
.B \-h\fR, \fB\-\-help
Show a help message and exit
.SS "COMMANDS"
.TP
.B find
Locate Python binaries
.IP
See
.BR hatch\-python\-find (1).
.TP
.B install
Install Python distributions
.IP
See
.BR hatch\-python\-install (1).
.TP
.B remove
Remove Python distributions
.IP
See
.BR hatch\-python\-remove (1).
.TP
.B show
Show the available Python distributions
.IP
See
.BR hatch\-python\-show (1).
.TP
.B update
Update Python distributions
.IP
See
.BR hatch\-python\-update (1).
.SH "SEE ALSO"
.BR hatch\-python\-find (1),
.BR hatch\-python\-install (1),
.BR hatch\-python\-remove (1),
.BR hatch\-python\-show (1),
.BR hatch\-python\-update (1)
.P
.BR hatch\-build (1),
.BR hatch\-clean (1),
.BR hatch\-config (1),
.BR hatch\-dep (1),
.BR hatch\-env (1),
.BR hatch\-fmt (1),
.BR hatch\-new (1),
.BR hatch\-project (1),
.BR hatch\-publish (1),
.BR hatch\-run (1),
.BR hatch\-self (1),
.BR hatch\-shell (1),
.BR hatch\-status (1),
.BR hatch\-test (1),
.BR hatch\-version (1)
.P
.BR hatch (1),
.BR python3 (1)
