%global source0_hash 407286af16f2b5b8aebe577b3610ae9b40ce296ed3c03c66444b5801c2fa3012

# https://fedoraproject.org/wiki/Packaging:Haskell

%global Agda_version 2.8.0

Name:           Agda-stdlib
Version:        2.3
Release:        %autorelease
Summary:        Agda standard libraries

License:        MIT
URL:            https://wiki.portal.chalmers.se/agda/agda.php?n=Libraries.StandardLibrary
Source0:        https://github.com/agda/agda-stdlib/archive/v%{version}.tar.gz#/agda-stdlib-%{version}.tar.gz
BuildRequires:  ghc-Cabal-devel
BuildRequires:  ghc-rpm-macros
BuildRequires:  ghc-filemanip-devel
BuildRequires:  Agda = %{Agda_version}
# .agdai files are arch independent
BuildArch:      noarch
Provides:       agda-stdlib = %{version}-%{release}
Requires:       Agda = %{Agda_version}
# Agda can't build on armv7hl and ix86 currently
ExcludeArch:    armv7hl %{ix86}

%description
Agda standard libraries

%package docs
Summary:        Agda standard libraries documentation
BuildArch:      noarch

%description docs
This package provides the html documentation for the stdlibs
generated by the Agda compiler program.

%prep
test "%{source0_hash}" = "none" || { f="%{SOURCE0}"; test -f "$f" || { echo "oreon: missing Source0 $f" >&2; exit 1; }; h=$(sha256sum "$f" | awk '{print $1}'); test "$h" = "%{source0_hash}" || { echo "oreon: Source0 hash mismatch" >&2; exit 1; }; }

%setup -q -n agda-stdlib-%{version}

%build
%ghc_bin_build
dist/build/GenerateEverything/GenerateEverything

%global agda agda --no-libraries -i. -isrc
%{agda} Everything.agda

%{agda} --html -idoc doc/README.agda

%install
mkdir -p %{buildroot}%{_datadir}/%{name}
cp -pr src _build %{buildroot}%{_datadir}/%{name}

install -p -m 0644 standard-library.agda-lib %{buildroot}%{_datadir}/%{name}/

%check
LANG=C.utf8 %{agda} -idoc doc/README.agda

%files
%license LICENCE
%doc CHANGELOG.md README.md
%{_datadir}/%{name}

%files docs
%license LICENCE
%doc CHANGELOG Everything* HACKING.md README*
%doc html

%changelog
%autochangelog
