.TH DAV\-MKDIR "1" "February 2024" "" "User Commands"
.SH NAME
.B dav\ mkdir
\(en Creates a directory/collection in the remote server
.SH SYNOPSIS
.B dav\ mkdir
.RB [ \-h ]
.RB [ \-\-parents ]
.I path
.SH OPTIONS
.SS "POSITIONAL\ ARGUMENTS"
.TP
.I path
Path to create
.SS "OPTIONAL\ ARGUMENTS"
.TP
.B \-h\fR,\ \fB\-\-help
Show a help message and exit
.TP
.B \-\-parents\fR,\ \fB\-p
No error if existing, make parent directories as needed
.SH "SEE\ ALSO"
.BR dav\-ls (1),
.BR dav\-cp (1),
.BR dav\-mv (1),
.BR dav\-rm (1),
.\" .BR dav\-mkdir (1),
.BR dav\-run (1),
.BR dav\-cat (1),
.BR dav\-sync (1),
.BR dav\-du (1)
.P
.BR dav (1)
