.TH DAV\-CAT "1" "February 2024" "" "User Commands"
.SH NAME
.B dav\ cat
\(en Print remote file content
.SH SYNOPSIS
.B dav\ cat
.RB [ \-h ]
.I FILE
.SH OPTIONS
.SS "POSITIONAL\ ARGUMENTS"
.TP
.I FILE
File to read
.SS "OPTIONAL\ ARGUMENTS"
.TP
.B \-h\fR,\ \fB\-\-help
Show a help message and exit
.SH "SEE\ ALSO"
.BR dav\-ls (1),
.BR dav\-cp (1),
.BR dav\-mv (1),
.BR dav\-rm (1),
.BR dav\-mkdir (1),
.BR dav\-run (1),
.\" .BR dav\-cat (1),
.BR dav\-sync (1),
.BR dav\-du (1)
.P
.BR dav (1)
