Alias /drraw /usr/share/drraw/

<Directory /usr/share/drraw/>
   Options ExecCGI
   DirectoryIndex drraw.cgi
   AddHandler cgi-script .cgi
   order deny,allow
   deny from all
   allow from 127.0.0.1
</Directory>
