# Configuration snippet for vdr-scraper2vdr               -*- sh -*-
#
# Add command line options to pass to the scraper2vdr plugin to PLUGIN_OPTIONS.
# See /usr/share/doc/vdr-scraper2vdr/README for info about available options.

PLUGIN_OPTIONS=""
