%global source0_hash 89e8bf7e0eb2dd7b4228cc1b6821fc5114cd6841ae59f652a85488c016091e5f

# Generated by rust2rpm 24
%bcond check 0
%global debug_package %{nil}

%global crate tester

Name:           rust-tester
Version:        0.9.1
Release:        %autorelease
Summary:        Fork of Rust’s test crate that doesn’t require unstable language features

License:        MIT OR Apache-2.0
URL:            https://crates.io/crates/tester
Source:         %{crates_source}

BuildRequires:  cargo-rpm-macros >= 24

%global _description %{expand:
A fork of Rust’s `test` crate that doesn’t require unstable language
features.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
%license %{crate_instdir}/LICENSE-APACHE
%license %{crate_instdir}/LICENSE-MIT
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+asm_black_box-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+asm_black_box-devel %{_description}

This package contains library source intended for building other packages which
use the "asm_black_box" feature of the "%{crate}" crate.

%files       -n %{name}+asm_black_box-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+capture-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+capture-devel %{_description}

This package contains library source intended for building other packages which
use the "capture" feature of the "%{crate}" crate.

%files       -n %{name}+capture-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
test "%{source0_hash}" = "none" || { f="%{SOURCE0}"; test -f "$f" || { echo "oreon: missing Source0 $f" >&2; exit 1; }; h=$(sha256sum "$f" | awk '{print $1}'); test "$h" = "%{source0_hash}" || { echo "oreon: Source0 hash mismatch" >&2; exit 1; }; }

%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
%autochangelog
