%global source0_hash 06c2cd7ad49baac57beea244a90f0030b43c853d15a8aa25ce49ec40651dc303

# Generated by go2rpm 1.2
%bcond check 0

# https://github.com/apache/cloudstack-cloudmonkey
%global goipath         github.com/apache/cloudstack-cloudmonkey
Version:                6.2.0
%global tag             6.2.0

%gometa

%global common_description %{expand:
Apache Cloudstack Cloudmonkey is a command line interface (CLI) for Apache
CloudStack.

CloudMonkey can be use both as an interactive shell and as a command line tool
which simplifies Apache CloudStack configuration and management.}

%global golicenses      LICENSE
%global godocs          README.md CHANGES.md

Name:           apache-cloudstack-cloudmonkey
Release:        19%{?dist}
Summary:        Apache Cloudstack Cloudmonkey

# Upstream license specification: Apache-2.0
# Automatically converted from old format: ASL 2.0 - review is highly recommended.
License:        Apache-2.0
URL:            %{gourl}
Source0:        %{gosource}

BuildRequires:  golang(github.com/briandowns/spinner)
BuildRequires:  golang(github.com/chzyer/readline)
BuildRequires:  golang(github.com/gofrs/flock)
BuildRequires:  golang(github.com/google/shlex)
BuildRequires:  golang(github.com/mitchellh/go-homedir)
BuildRequires:  golang(github.com/olekukonko/tablewriter)
BuildRequires:  golang(gopkg.in/ini.v1)

%description
%{common_description}

%gopkg

%prep
test "%{source0_hash}" = "none" || { f="%{SOURCE0}"; test -f "$f" || { echo "oreon: missing Source0 $f" >&2; exit 1; }; h=$(sha256sum "$f" | awk '{print $1}'); test "$h" = "%{source0_hash}" || { echo "oreon: Source0 hash mismatch" >&2; exit 1; }; }

%goprep

%build
%gobuild -o %{gobuilddir}/bin/cmk %{goipath}

%install
%gopkginstall
install -m 0755 -vd                     %{buildroot}%{_bindir}
install -m 0755 -vp %{gobuilddir}/bin/* %{buildroot}%{_bindir}/

%if %{with check}
%check
%gocheck
%endif

%files
%license LICENSE
%doc README.md CHANGES.md
%{_bindir}/*

%gopkgfiles

%changelog
%autochangelog
