%global source0_hash e2c8e5735a357899fec83f4b2f4e0f8ad862514f2e4fc29707d62d38d64d37c8

# Generated by go2rpm
%bcond check 1

%global debug_package %{nil}

# https://github.com/golang/tools
%global goipath         golang.org/x/tools/go/expect
%global forgeurl        https://github.com/golang/tools
Version:                0.1.1
%global tag             go/expect/v%{version}-deprecated
%{lua: rpm.define("safe_tag " .. string.gsub(rpm.expand("%tag"), "/", "-"))}
%global distprefix      %{nil}

%gometa -L -f

%global common_description %{expand:
Package expect provides support for interpreting structured comments in Go
source code (including go.mod and go.work files) as test expectations.}

%global golicenses      LICENSE PATENTS
%global godocs          CONTRIBUTING.md

%global godevelheader %{expand:
# Upstream specifically split this subpackage out of golang.org/x/tools for
# backwards-compatibility with things that need it, but specified that it is
# deprecated.
Provides: deprecated()
}

Name:           golang-x-tools-expect
Release:        %autorelease
Summary:        Test expectations from structured comments in Go code

License:        BSD-3-Clause
URL:            %{gourl}
Source:         %{gosource}

%description %{common_description}

%gopkg

%prep
test "%{source0_hash}" = "none" || { f="%{SOURCE0}"; test -f "$f" || { echo "oreon: missing Source0 $f" >&2; exit 1; }; h=$(sha256sum "$f" | awk '{print $1}'); test "$h" = "%{source0_hash}" || { echo "oreon: Source0 hash mismatch" >&2; exit 1; }; }

%goprep -A
%autopatch -q -p1
# Created by goprep, but with the wrong path, so re-create it.
rm -r _build/src/golang.org/x/tools
ln -s %{_builddir}/tools-%{safe_tag} _build/src/golang.org/x/tools
# Delete everything not related to the subpackage to reduce BuildRequires.
rm -r benchmark blog cmd container copyright cover godoc gopls imports internal
rm -r playground present refactor txtar
rm codereview.cfg go.mod go.sum README.md
rm -r go/analysis go/ast go/buildutil go/callgraph go/cfg go/gccgoexportdata
rm -r go/gcexportdata go/internal go/loader go/packages go/ssa go/types

%generate_buildrequires
%go_generate_buildrequires

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog
%autochangelog
