%global source0_hash d786e04875bdbc6bf1e31d65e751c244734afe5642c19e928294764d680cac40

# Generated by go2rpm 1
%bcond check 0

%global debug_package %{nil}

# https://github.com/rickb777/plural
%global goipath         github.com/rickb777/plural
Version:                1.4.1

%gometa

%global common_description %{expand:
Simple Go API for pluralisation.}

%global golicenses      LICENSE
%global godocs          README.md

Name:           %{goname}
Release:        %autorelease
Summary:        Simple Go API for pluralisation

# Upstream license specification: BSD-3-Clause
License:        BSD-3-Clause
URL:            %{gourl}
Source0:        %{gosource}

%description
%{common_description}

%gopkg

%prep
test "%{source0_hash}" = "none" || { f="%{SOURCE0}"; test -f "$f" || { echo "oreon: missing Source0 $f" >&2; exit 1; }; h=$(sha256sum "$f" | awk '{print $1}'); test "$h" = "%{source0_hash}" || { echo "oreon: Source0 hash mismatch" >&2; exit 1; }; }

%goprep

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog
%autochangelog
