%global source0_hash c359bbcfb06928f6b9817d4fb8f44b595382a7d405b63c2ceefed85f26c221d2

# generated by cabal-rpm-2.3.2 --subpackage
# https://docs.fedoraproject.org/en-US/packaging-guidelines/Haskell/

%global pkg_name haskell-gi-base
%global pkgver %{pkg_name}-%{version}
%{?haskell_setup}

%global opticscore optics-core-0.4.1.1

%global subpkgs %{opticscore}

Name:           ghc-%{pkg_name}
Version:        0.26.9
# can only be reset when subpkg bumped
Release:        1%{?dist}
Summary:        Foundation for libraries generated by haskell-gi

License:        LGPL-2.1-or-later
URL:            https://hackage.haskell.org/package/haskell-gi-base
# Begin cabal-rpm sources:
Source0:        https://hackage.haskell.org/package/%{pkgver}/%{pkgver}.tar.gz
Source1:        https://hackage.haskell.org/package/%{opticscore}/%{opticscore}.tar.gz
# End cabal-rpm sources

# Begin cabal-rpm deps:
BuildRequires:  ghc-rpm-macros-extra
BuildRequires:  ghc-Cabal-devel
BuildRequires:  ghc-base-devel
BuildRequires:  ghc-bytestring-devel
BuildRequires:  ghc-containers-devel
#BuildRequires:  ghc-optics-core-devel
BuildRequires:  ghc-text-devel
%if %{with ghc_prof}
BuildRequires:  ghc-base-prof
BuildRequires:  ghc-bytestring-prof
BuildRequires:  ghc-containers-prof
#BuildRequires:  ghc-optics-core-prof
BuildRequires:  ghc-text-prof
%endif
BuildRequires:  pkgconfig(glib-2.0)
BuildRequires:  pkgconfig(gobject-2.0)
# for missing dep 'optics-core':
BuildRequires:  ghc-array-devel
BuildRequires:  ghc-indexed-profunctors-devel
BuildRequires:  ghc-indexed-traversable-devel
BuildRequires:  ghc-transformers-devel
%if %{with ghc_prof}
BuildRequires:  ghc-array-prof
BuildRequires:  ghc-indexed-profunctors-prof
BuildRequires:  ghc-indexed-traversable-prof
BuildRequires:  ghc-transformers-prof
%endif
# End cabal-rpm deps

%description
Foundation for libraries generated by haskell-gi.

%package devel
Summary:        Haskell %{pkg_name} library development files
Provides:       %{name}-static = %{version}-%{release}
Provides:       %{name}-static%{?_isa} = %{version}-%{release}
%if %{defined ghc_version}
Requires:       ghc-compiler = %{ghc_version}
%endif
Requires:       %{name}%{?_isa} = %{version}-%{release}
# Begin cabal-rpm deps:
Requires:       pkgconfig(glib-2.0)
Requires:       pkgconfig(gobject-2.0)
# End cabal-rpm deps

%description devel
This package provides the Haskell %{pkg_name} library development
files.

%if %{with haddock}
%package doc
Summary:        Haskell %{pkg_name} library documentation
BuildArch:      noarch
Requires:       ghc-filesystem

%description doc
This package provides the Haskell %{pkg_name} library documentation.
%endif

%if %{with ghc_prof}
%package prof
Summary:        Haskell %{pkg_name} profiling library
Requires:       %{name}-devel%{?_isa} = %{version}-%{release}
Supplements:    (%{name}-devel and ghc-prof)

%description prof
This package provides the Haskell %{pkg_name} profiling library.
%endif

%global main_version %{version}

%if %{defined ghclibdir}
%ghc_lib_subpackage -l BSD-3-Clause %{opticscore}
%endif

%global version %{main_version}

%prep
test "%{source0_hash}" = "none" || { f="%{SOURCE0}"; test -f "$f" || { echo "oreon: missing Source0 $f" >&2; exit 1; }; h=$(sha256sum "$f" | awk '{print $1}'); test "$h" = "%{source0_hash}" || { echo "oreon: Source0 hash mismatch" >&2; exit 1; }; }

# Begin cabal-rpm setup:
%setup -q -n %{pkgver} -a1
# End cabal-rpm setup
(
    cd %{opticscore}
    cabal-tweak-dep-ver containers '<0.7' '<0.9'
)

%build
# Begin cabal-rpm build:
%ghc_libs_build %{subpkgs}
%ghc_lib_build
# End cabal-rpm build

%install
# Begin cabal-rpm install
%ghc_libs_install %{subpkgs}
%ghc_lib_install
# End cabal-rpm install

%files -f %{name}.files
# Begin cabal-rpm files:
%license LICENSE
# End cabal-rpm files

%files devel -f %{name}-devel.files
%doc ChangeLog.md

%if %{with haddock}
%files doc -f %{name}-doc.files
%license LICENSE
%endif

%if %{with ghc_prof}
%files prof -f %{name}-prof.files
%endif

%changelog
%autochangelog
