%global source0_hash b02a3fbeb9c9dfff9fc9e3f1def80865702a8ce83cbd528995c094a053e7f9a8

# Generated by go2rpm 1.12.0
%bcond check 0
%global debug_package %{nil}

# https://github.com/alecthomas/units
%global goipath         github.com/alecthomas/units
%global commit          9a357b53e9c9395aa5fa9031ac79dc94111814e1

%gometa -L

%global common_description %{expand:
Helpful unit multipliers and functions for Go.}

%global golicenses      COPYING
%global godocs          README.md

Name:           golang-github-alecthomas-units
Version:        0
Release:        %autorelease -p
Summary:        Helpful unit multipliers and functions for Go

License:        MIT
URL:            %{gourl}
Source:         %{gosource}

%description %{common_description}

%gopkg

%prep
test "%{source0_hash}" = "none" || { f="%{SOURCE0}"; test -f "$f" || { echo "oreon: missing Source0 $f" >&2; exit 1; }; h=$(sha256sum "$f" | awk '{print $1}'); test "$h" = "%{source0_hash}" || { echo "oreon: Source0 hash mismatch" >&2; exit 1; }; }

%goprep -A
%autopatch -p1

%generate_buildrequires
%go_generate_buildrequires

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog
%autochangelog
