.TH FUNGULOIDS 6 "July 10, 2007"
.SH NAME
funguloids \- "Those Funny Funguloids!"
.SH SYNOPSIS
.B funguloids
.SH DESCRIPTION
This manual page documents briefly the
.B funguloids
command.
.PP
\fBfunguloids\fP is a the command to run and play the game "Those Funny Funguloids!".
.SH SEE ALSO
.BR /usr/share/doc/funguloids
.br
.BR http://funguloids.sourceforge.net
.SH CREDITS
"Those Funny Funguloids!" was primarily developed by:
.br
.br
\fBCode:\fP Mika Halttunen <lsoftNOSPAM@mbnet.fi>
.br
\fBGame Design:\fP Teemu Ruokolainen
.br
\fBArtwork:\fP Mika Halttunen
.br
\fBSound Design & Music:\fP Teemu Ruokolainen
.SH LICENSE
"Those Funny Funguloids!" is licensed under the zlib/libpng license.
Copyright (C) 2006-2007, Mika Halttunen & Teemu Ruokolainen

This software is provided 'as-is', without any express or implied warranty. In no event will the authors be held liable for any damages arising from the use of this software.

Permission is granted to anyone to use this software for any purpose, including commercial applications, and to alter it and redistribute it freely, subject to the following restrictions:

   1. The origin of this software must not be misrepresented; you must not claim
   that you wrote the original software. If you use this software in a product, an
   acknowledgment in the product documentation would be appreciated but is not
   required.
   2. Altered source versions must be plainly marked as such, and must not be
   misrepresented as being the original software.
   3. This notice may not be removed or altered from any source distribution.

This manual page was written by Andres Mejia <mcitadel@gmail.com>,
for the Debian project (but may be used by others).
