.TH TEND\-EVQ "1" "April 2021" "" "User Commands"
.SH NAME
tend\-evq \- quantize directions of diffusion
.SH SYNOPSIS
.B tend\ evq
.RB [ \-c
.RI < evec\ index >]
.B \-a
.RI < aniso >
.RB [ \-ns ]
.RB [ \-i
.RI < nin >]
.RB [ \-o
.RI < nout >]
.SH DESCRIPTION
Quantize directions of diffusion.
Because VTK doesn\(cqt do multi-dimensional colormaps, we have to quantize
directions of diffusion (usually just the principal eigenvector) in order to
create the usual XYZ<->RGB coloring.
Because eigenvector directions are poorly defined in regions of low anisotropy,
the length of the vector (pre-quantization) is modulated by anisotropy,
requiring the selection of some anisotropy metric.
.SH OPTIONS
.TP
.B \-c\fR <\fIevec\ index\fR>
Which eigenvector should be quantized:

.RB \(lq 0 \(rq
for the direction of fastest diffusion (eigenvector associated with largest
eigenvalue),
.RB \(lq 1 \(rq
or
.RB \(lq 2 \(rq
for other two eigenvectors (associated with middle and smallest eigenvalue)
.RI ( int );
default:
.RB \(lq 0 \(rq
.TP
.B \-a\fR <\fIaniso\fR>
Which anisotropy metric to scale the eigenvector with.
All the Westin metrics come in two versions.
Currently supported:
.RS +7n
.IP \(bu 2
.RB \(lq cl1 \(rq,
.RB \(lq cl2 \(rq:
Westin\(cqs linear
.IP \(bu 2
.RB \(lq cp1 \(rq,
.RB \(lq cp2 \(rq:
Westin\(cqs planar
.IP \(bu 2
.RB \(lq ca1 \(rq,
.RB \(lq ca2 \(rq:
Westin\(cqs linear + planar
.IP \(bu 2
.RB \(lq cs1 \(rq,
.RB \(lq cs2 \(rq:
Westin\(cqs spherical
.IP \(bu 2
.RB \(lq ct1 \(rq,
.RB \(lq ct2 \(rq:
GK\(cqs anisotropy type (cp/ca)
.IP \(bu 2
.RB \(lq ra \(rq:
Basser/Pierpaoli relative anisotropy/sqrt(2)
.IP \(bu 2
.RB \(lq fa \(rq:
Basser/Pierpaoli fractional anisotropy
.IP \(bu 2
.RB \(lq vf \(rq:
volume fraction = 1\-(Basser/Pierpaoli volume ratio)
.IP \(bu 2
.RB \(lq tr \(rq:
trace
.RE
.TP
.B \-ns
Don\(cqt attenuate the color by anisotropy.
By default (not using this option), regions with low or no anisotropy are very
dark colors or black
.TP
.B \-i\fR <\fInin\fR>
input diffusion tensor volume; default:
.RB \(lq \- \(rq
.TP
.B \-o\fR <\fInout\fR>
output image (floating point)
.RI ( string )
default:
.RB \(lq \- \(rq
.SH "SEE\ ALSO"
.BR tend (1)
