.TH UNU\-RMAP "1" "August 2021" "" "User Commands"
.SH NAME
unu\-rmap \- map
.I nrrd
through one
.B regular
univariate map (\(lqcolormap\(rq)
.SH SYNOPSIS
.B unu\ rmap
.BR \-m , \-\-map
.RI < map >
.RB [ \-r , \-\-rescale ]
.RB [ \-min , \-\-minimum
.RI < value >]
.RB [ \-max , \-\-maximum
.RI < value >]
.RB [ \-blind8
.RI < bool >]
.RB [ \-t , \-\-type
.RI < type >]
.RB [ \-i , \-\-input
.RI < nin >]
.RB [ \-o , \-\-output
.RI < nout >]
.SH DESCRIPTION
Map
.I nrrd
through one
.B regular
univariate map (\(lqcolormap\(rq).
A map is regular if the control points are evenly spaced along the domain, and
hence their position isn\(cqt explicitly represented in the map; the axis
.IR min ,
axis
.IR max ,
and number of points determine their location.
The map can be a 1D
.I nrrd
(for \(lqgrayscale\(rq), in which case the output has the same dimension as the
input, or a 2D
.I nrrd
(for \(lqcolor\(rq), in which case the output has one more dimension than the
input.
In either case, the output is the result of linearly interpolating between map
points, either scalar values (\(lqgrayscale\(rq), or scanlines along axis
.B 0
(\(lqcolor\(rq).
.IP \(bu +2n
Uses
.B nrrdApply1DRegMap
.SH OPTIONS
.TP
.B \-m\fR\ <\fImap\fR>\ ,\ \fB\-\-map\fR\ <\fImap\fR>
regular map to map input
.I nrrd
through
.TP
.B \-r\fR ,\ \fB\-\-rescale
rescale the input values from the input range to the map domain.
The map domain is either explicitly defined by the axis
.IR min , max
along axis
.B 0
or
.BR 1 ,
or, it is implicitly defined as zero to the length of that axis minus one.
.TP
.B \-min\fR\ <\fIvalue\fR>\ ,\ \fB\-\-minimum\fR\ <\fIvalue\fR>
Low end of input range.
Defaults to lowest value found in input
.IR nrrd .
Explicitly setting this is useful only with rescaling
.RB (\(lq \-r \(rq)
.RI ( double )
.TP
.B \-max\fR\ <\fIvalue\fR>\ ,\ \fB\-\-maximum\fR\ <\fIvalue\fR>
High end of input range.
Defaults to highest value found in input
.IR nrrd .
Explicitly setting this is useful only with rescaling
.RB (\(lq \-r \(rq)
.RI ( double )
.TP
.B \-blind8\fR\ <\fIbool\fR>
Whether to know the range of 8-bit data blindly
.RI ( uchar
is always
.BR [0,255] ,
.I signed\ char
is
.BR [-128,127] ).
Explicitly setting this is useful only with rescaling
.RB (\(lq \-r \(rq)
.RI ( bool );
default:
.RB \(lq true \(rq
.TP
.B \-t\fR\ <\fItype\fR>\ ,\ \fB\-\-type\fR\ <\fItype\fR>
specify the type
.RB (\(lq int \(rq,
.RB \(lq float \(rq,
etc.) of the output
.IR nrrd .
By default (not using this option), the output type is the map\(cqs type.
.TP
.B \-i\fR\ <\fInin\fR>\ ,\ \fB\-\-input\fR\ <\fInin\fR>
input
.I nrrd
.TP
.B \-o\fR\ <\fInout\fR>\ ,\ \fB\-\-output\fR\ <\fInout\fR>
output
.I nrrd
.RI ( string );
default:
.RB \(lq \- \(rq
.SH "SEE\ ALSO"
.BR unu (1),
.BR unu\-mrmap (1),
.BR unu\-imap (1)
