.TH UNU\-IMAP "1" "August 2021" "" "User Commands"
.SH NAME
unu\-imap \- map
.I nrrd
through
.B irregular
univariate map (\(lqcolormap\(rq)
.SH SYNOPSIS
.B unu\ rmap
.BR \-m , \-\-map
.RI < map >
.RB [ \-l , \-\-length
.RI < aclLen >]
.RB [ \-r , \-\-rescale ]
.RB [ \-min , \-\-minimum
.RI < value >]
.RB [ \-max , \-\-maximum
.RI < value >]
.RB [ \-blind8
.RI < bool >]
.RB [ \-t , \-\-type
.RI < type >]
.RB [ \-i , \-\-input
.RI < nin >]
.RB [ \-o , \-\-output
.RI < nout >]
.SH DESCRIPTION
Map
.I nrrd
through
.B irregular
univariate map (\(lqcolormap\(rq).
A map is irregular if the control points are not evenly spaced along the
domain, and hence their position must be explicitly represented in the map.
As
.IR nrrd s,
these maps are necessarily 2D.
Along axis
.BR 0 ,
the first value is the location of the control point, and the remaining values
give are the range of the map for that control point.
The output value(s) is the result of linearly interpolating between value(s)
from the map.
.IP \(bu +2n
Uses
.B nrrdApply1DIrregMap
.SH OPTIONS
.TP
.B \-m\fR\ <\fImap\fR>\ ,\ \fB\-\-map\fR\ <\fImap\fR>
irregular map to map input
.I nrrd
through
.TP
.B \-l\fR\ <\fIaclLen\fR>\ ,\ \fB\-\-length\fR\ <\fIaclLen\fR>
length of accelerator array, used to try to speed-up task of finding between
which pair of control points a given value lies.
Not terribly useful for small maps (about 10 points or less).
Use
.B 0
to turn accelorator off.
.RI ( unsigned\ int );
default:
.RB \(lq 0 \(rq
.TP
.B \-r\fR ,\ \fB\-\-rescale
rescale the input values from the input range to the map domain.
.TP
.B \-min\fR\ <\fIvalue\fR>\ ,\ \fB\-\-minimum\fR\ <\fIvalue\fR>
Low end of input range.
Defaults to lowest value found in input
.IR nrrd .
Explicitly setting this is useful only with rescaling
.RB (\(lq \-r \(rq)
.RI ( double )
.TP
.B \-max\fR\ <\fIvalue\fR>\ ,\ \fB\-\-maximum\fR\ <\fIvalue\fR>
High end of input range.
Defaults to highest value found in input
.IR nrrd .
Explicitly setting this is useful only with rescaling
.RB (\(lq \-r \(rq)
.RI ( double )
.TP
.B \-blind8\fR\ <\fIbool\fR>
Whether to know the range of 8-bit data blindly
.RI ( uchar
is always
.BR [0,255] ,
.I signed\ char
is
.BR [-128,127] ).
Explicitly setting this is useful only with rescaling
.RB (\(lq \-r \(rq)
.RI ( bool );
default:
.RB \(lq true \(rq
.TP
.B \-t\fR\ <\fItype\fR>\ ,\ \fB\-\-type\fR\ <\fItype\fR>
specify the type
.RB (\(lq int \(rq,
.RB \(lq float \(rq,
etc.) of the output
.IR nrrd .
By default (not using this option), the output type is the map\(cqs type.
.TP
.B \-i\fR\ <\fInin\fR>\ ,\ \fB\-\-input\fR\ <\fInin\fR>
input
.I nrrd
.TP
.B \-o\fR\ <\fInout\fR>\ ,\ \fB\-\-output\fR\ <\fInout\fR>
output
.I nrrd
.RI ( string );
default:
.RB \(lq \- \(rq
.SH "SEE\ ALSO"
.BR unu (1),
.BR unu\-rmap (1)
