.TH UNU\-DATA "1" "May 2021" "" "User Commands"
.SH NAME
unu\-data \- print data segment of a \fInrrd\fR file
.SH SYNOPSIS
.B unu\ data
.RI < nin >
.SH DESCRIPTION
Print data segment of a
.I nrrd
file.
The value of this is to pass the data segment in isolation to a stand-alone
decoder, in case this Teem build lacks an optional data encoding required for a
given nrrd file.
.SS CAVEATS
Will start copying characters from the datafile until EOF is hit, so this
won\(cqt work correctly if the datafile has extraneous content at the end.
Will skip lines (as per
.RB \(lq line\ skip: \(rq
header field) if needed, but can only skip bytes (as per
.RB \(lq byte\ skip: \(rq
if the encoding is NOT a compression. 
.IP \(bu +2n
Uses
.B nrrdLoad
with
.B nio->skipData
and
.B nio->keepNrrdDataFileOpen
both
.B true
in the
.I NrrdIoState
.BR nio .
.SH OPTIONS
.TP
.RI < nin >
input
.I nrrd
.RI ( string )
.SH EXAMPLES
To make
.B vol.raw
contain the uncompressed data from
.B vol.nrrd
which uses
.RB \(lq gz \(rq
encoding:
.in +4n
.EX
.B unu data vol.nrrd | gunzip > vol.raw
.EE
.in
.SH "SEE\ ALSO"
.BR unu (1),
.BR unu\-head (1)
