.TH UNU\-AXINSERT "1" "August 2021" "" "User Commands"
.SH NAME
unu\-axinsert \- add a \(lqstub\(rq (length 1) axis to a
.I nrrd
.SH SYNOPSIS
.B unu\ axinsert
.BR \-a , \-\-axis
.RI < axis >
.RB [ \-l , \-\-label
.RI < label >]
.RB [ \-i , \-\-input
.RI < nin >]
.RB [ \-o , \-\-output
.RI < nout >]
.SH DESCRIPTION
Add a \(lqstub\(rq (length 1) axis to a
.IR nrrd .
The underlying linear ordering of the samples is unchanged, and the information
about the other axes is shifted upwards as needed.
.IP \(bu +2n
Uses
.B nrrdAxesInsert
.SH OPTIONS
.TP
.B \-a\fR\ <\fIaxis\fR>\ ,\ \fB\-\-axes\fR\ <\fIaxis\fR>
dimension (axis index) at which to insert the new axis
.RI ( unsigned\ int )
.TP
.B \-l\fR\ <\fIlabel\fR>\ ,\ \fB\-\-label\fR\ <\fIlabel\fR>
label to associate with axis
.RI ( string )
.TP
.B \-i\fR\ <\fInin\fR>\ ,\ \fB\-\-input\fR\ <\fInin\fR>
input
.I nrrd
.TP
.B \-o\fR\ <\fInout\fR>\ ,\ \fB\-\-output\fR\ <\fInout\fR>
output
.I nrrd
.RI ( string );
default:
.RB \(lq \- \(rq
.SH "SEE\ ALSO"
.BR unu (1),
.BR unu\-axsplit (1)
