.TH UNU\-CCADJ "1" "August 2021" "" "User Commands"
.SH NAME
unu\-ccadj \- form adjacency matrix of connected components
.SH SYNOPSIS
.B unu\ ccadj
.BR \-c , \-\-connect
.RI < connectivity >
.RB [ \-i , \-\-input
.RI < nin >]
.RB [ \-o , \-\-output
.RI < nout >]
.SH DESCRIPTION
Form adjecency matrix of connected components.
This operates on
the output of
.BR unu\-ccfind (1).
Output is
.I unsigned\ char
array containing
.B 1
at locations
.RI ( I , J )
and
.RI ( J , I )
if CCs with ids
.I I
and
.I J
are adjacent, according to the chosen style of adjacency.
.IP \(bu +2n
Uses
.B nrrdCCAdjacency
.SH OPTIONS
.TP
.B \-c\fR\ <\fIconnectivity\fR>\ ,\ \fB\-\-connect\fR\ <\fIconnectivity\fR>
what kind of connectivity to use: the number of coordinates that vary in order
to traverse the neighborhood of a given sample.
In 2D:
.RB \(lq 1 \(rq:
4-connected,
.RB \(lq 2 \(rq:
8-connected
.RI ( unsigned\ int )
.TP
.B \-o\fR\ <\fInout\fR>\ ,\ \fB\-\-output\fR\ <\fInout\fR>
output
.I nrrd
.RI ( string );
default:
.RB \(lq \- \(rq
.SH "SEE\ ALSO"
.BR unu (1),
.BR unu\-ccfind (1),
.BR unu\-ccmerge (1),
.BR unu\-ccsettle (1)
