.TH UNU "1" "April 2021" "" "User Commands"
.SH NAME
unu \- Utah Nrrd Utilities command-line interface
.SH SYNOPSIS
.B unu
.I COMMAND
.RI [ OPTION ]...\:
.SH DESCRIPTION
.BR unu (1)
is a command-line interface to much of the functionality in \(lqnrrd\(rq, a C
library for raster data processing.
Nrrd is one library in the \(lqTeem\(rq collection of libraries.
More information about Teem is at
.UR http://teem.sf.net
http://teem.sf.net
.UE .
A checkout of Teem source is available via:
.in +4n
.EX
.B svn co https://svn.code.sf.net/p/teem/code/teem/trunk teem
.EE
.in
.P
Long-term maintenance of this software depends on funding, and funding depends
on being able to document who is using it for what.
If
.BR unu (1)
or Nrrd has helped in your research, including for simple one-off experiments
or mundane data hacking, the developers of Teem would love to know.
There are multiple ways of communicating this.
In your publications, consider adding a line such as this in the
Acknowledgments:
.in +4n
Data processing performed with the unu tool, part of the Teem toolkit available
at
.UR http://teem.sf.net
http://teem.sf.net
.UE .
.in
Alternatively, please email
.MT glk@uchicago.edu
glk@uchicago.edu
.ME
and briefly describe how Teem software has helped in your work.
Please also consider joining the
.UR https://lists.sourceforge.net/lists/listinfo/teem-users
teem\-users mailing list
.UE .
This is the primary forum for feedback, questions, and feature requests.
.P
A summary list of unu commands is generated by running simply
.RB \(lq unu \(rq.
Running a
.BR unu (1)
command without additional arguments (e.g. \(lq\fBunu\ slice\fR\(rq)
generates its description and usage information.
This includes information (marked with
.RB \(lq *\ Uses\ ... \(rq)
about the underling Nrrd library calls (e.g. \fBnrrdSlice()\fR) that implement
the basic functionality in that
.BR unu (1)
command.
.P
The utility of
.BR unu (1)
is mainly as a pre-processing tool for getting data into a type, encoding,
format, or dimensions best suited for some visualization or rendering task.
Also, slices and projections are effective ways to visually inspect the
contents of a dataset.
Especially useful
 commands include
.BR make ,
.BR resample ,
.BR crop ,
.BR slice ,
.BR project ,
.BR histo ,
.BR dhisto ,
.BR quantize ,
and
.BR save .
.BR unu (1)
can process CT and MRI volume datasets, grayscale and color images,
time-varying volumes of vector fields (5-D arrays), and more.
Currently supported formats are plain text files (2-D float arrays), NRRD, VTK
structured points, and PNG and PNM images.
.RB \(lq unu\ make\ \-bs\ \-1 \(rq
can read from most DICOM files.
.RB \(lq unu\ save \(rq
can generate EPS files.
Supported encodings are raw, ascii, hex, gzip, and bzip2.
.P
Much of the functionality of
.BR unu (1)
derives from chaining multiple invocations together with pipes
.RB (\(lq | \(rq),
minimizing the need to save out intermediate files.
For example, if
.RB (\(lq data.raw.gz \(rq),
is a gzip\(cqed 256\ x\ 256\ x\ 80 volume of raw floats written from a PC, then
the following will save to
.RB (\(lq zsum.png \(rq)
a histogram equalized summation projection along the slowest axis:
.in +4n
.EX
\fBunu\ make\ \-i\ data.raw.gz\ \-t\ float\ \-s\ 256\ 256\ 80\ \-e\ gzip\ \-en\ little\ \(rs
\ |\ unu\ project\ \-a\ 2\ \-m\ sum\ \(rs
\ |\ unu\ heq\ \-b\ 2000\ \-s\ 1\ \(rs
\ |\ unu\ quantize\ \-b\ 8\ \-o\ zsum.png
.EE
.in
.P
Formats available:
.B nrrd pnm png vtk text eps
.P
Nrrd data encodings available:
.B raw ascii hex gz bz2
.SH COMMANDS
.P
Each of the following has a corresponding man page: for example,
.BR unu\-about (1)
for
.RB \(lq unu\ about \(rq.
.SS unu about
Information about this program and its use
.SS unu env
List relevant environment variables and their values
.SS unu i2w
Convert from 1-D index to world position
.SS unu w2i
Convert from 1-D world to index position
.SS unu make
Create a
.I nrrd
(or
.I nrrd
header) from scratch
.SS unu head
Print header of one or more
.I nrrd
files
.SS unu data
Print data segment of a
.I nrrd
file
.SS unu convert
Convert to another type (as if by cast, w/ optional clamp)
.SS unu resample
Filtering and {up,down}sampling with a separable kernel
.SS unu fft
Fast Fourier Transform of selected axes
.SS unu cmedian
Cheap histogram-based median/mode filtering
.SS unu dist
Euclidean distance transform
.SS unu minmax
Print out min and max values in one or more
.IR nrrd s
.SS unu cksum
Compute 32-bit CRC of
.I nrrd
data (same as via
.BR cksum (1))
.SS unu diff
Sees if two
.IR nrrd s
are different in any way
.SS unu quantize
Quantize values to 8, 16, or 32 bits
.SS unu unquantize
Recover floating point values from quantized data
.SS unu project
Collapse scanlines to scalars along some axis
.SS unu slice
Slice along one or more axes at given positions
.SS unu sselect
Select subset of slices along an axis
.SS unu dice
Save all slices along one axis into separate files
.SS unu splice
Replace a slice with a different
.I nrrd
.SS unu join
Connect slices and/or slabs into a bigger
.I nrrd
.SS unu crop
Crop along each axis to make a smaller
.I nrrd
.SS unu acrop
Automatically crop axes based on given measure
.SS unu inset
Replace a sub-region with a different
.I nrrd
.SS unu pad
Pad along each axis to make a bigger
.I nrrd
.SS unu reshape
Superficially change dimension and/or axes sizes
.SS unu permute
Permute ordering of axes
.SS unu swap
Interchange ordering of two axes
.SS unu shuffle
Permute slices along one axis
.SS unu flip
Reverse order of slices along one axis
.SS unu unorient
Make image orientation be axis-aligned
.SS unu axinfo
Modify attributes of one or more axes
.SS unu axinsert
Add a \(lqstub\(rq (length 1) axis to a
.I nrrd
.SS unu axsplit
Split one axis into two axes
.SS unu axdelete
Remove one or more singleton axes from a
.I nrrd
.SS unu axmerge
Merge two adjacent axes into one
.SS unu tile
Tile slices of one axis into two other axes
.SS unu untile
Undo
.BR unu\-tile (1):
merge slow parts of two axis splits
.SS unu histo
Create 1-D histogram of values in a
.I nrrd
.SS unu dhisto
Create image of 1-D value histogram
.SS unu jhisto
Create joint histogram of two or more
.IR nrrd s
.SS unu histax
Replace each scanline along an axis with its histogram
.SS unu heq
Perform histogram equalization
.SS unu gamma
Brighten or darken values with a gamma
.SS unu 1op
Unary operation on a
.I nrrd
.SS unu 2op
Binary operation on two
.IR nrrd s,
or on a
.I nrrd
and a constant
.SS unu 3op
Ternary operation on three
.IR nrrd s
or constants
.SS unu affine
Affine (lerp) mapping on 5
.IR nrrd s
or constants
.SS unu lut
Map
.I nrrd
through one univariate lookup table
.SS unu mlut
Map
.I nrrd
through whole
.I nrrd
of univariate lookup tables
.SS unu subst
Map
.I nrrd
through a univariate substitution table
.SS unu rmap
Map
.I nrrd
through one
.B regular
univariate map (\(lqcolormap\(rq)
.SS unu mrmap
Map
.I nrrd
through a whole
.I nrrd
of regular univariate maps
.SS unu imap
Map
.I nrrd
through
.B irregular
univariate map (\(lqcolormap\(rq)
.SS unu lut2
Map
.I nrrd
through a bivariate lookup table
.SS unu ccfind
Find connected components (CCs)
.SS unu ccadj
Form adjecency matrix of connected components
.SS unu ccmerge
Merge CCs with their neighbors, under various constraints
.SS unu ccsettle
Remap CC values down to lowest contiguous values
.SS unu save
Write
.I nrrd
with specific format, encoding, or endianness
.SH ENVIRONMENT
See
.BR unu\-env (1).
.SH "SEE\ ALSO"
.BR gprobe (1),
.BR ilk (1),
.BR mrender (1),
.BR miter (1),
.BR nrrdSanity (1),
.BR overrgb (1),
.BR puller (1),
.BR tend (1),
.BR vprobe (1),
.BR unu-1op (1),
.BR unu-2op (1),
.BR unu-3op (1),
.BR unu-about (1),
.BR unu-acrop (1),
.BR unu-affine (1),
.BR unu-axdelete (1),
.BR unu-axinfo (1),
.BR unu-axinsert (1),
.BR unu-axmerge (1),
.BR unu-axsplit (1),
.BR unu-ccadj (1),
.BR unu-ccfind (1),
.BR unu-ccmerge (1),
.BR unu-ccsettle (1),
.BR unu-cksum (1),
.BR unu-cmedian (1),
.BR unu-convert (1),
.BR unu-crop (1),
.BR unu-data (1),
.BR unu-dhisto (1),
.BR unu-dice (1),
.BR unu-diff (1),
.BR unu-dist (1),
.BR unu-env (1),
.BR unu-fft (1),
.BR unu-flip (1),
.BR unu-gamma (1),
.BR unu-head (1),
.BR unu-heq (1),
.BR unu-histax (1),
.BR unu-histo (1),
.BR unu-i2w (1),
.BR unu-imap (1),
.BR unu-inset (1),
.BR unu-jhisto (1),
.BR unu-join (1),
.BR unu-lut (1),
.BR unu-lut2 (1),
.BR unu-make (1),
.BR unu-minmax (1),
.BR unu-mlut (1),
.BR unu-mrmap (1),
.BR unu-pad (1),
.BR unu-permute (1),
.BR unu-project (1),
.BR unu-quantize (1),
.BR unu-resample (1),
.BR unu-reshape (1),
.BR unu-rmap (1),
.BR unu-save (1),
.BR unu-shuffle (1),
.BR unu-slice (1),
.BR unu-splice (1),
.BR unu-sselect (1),
.BR unu-subst (1),
.BR unu-swap (1),
.BR unu-tile (1),
.BR unu-unorient (1),
.BR unu-unquantize (1),
.BR unu-untile (1),
.BR unu-w2i (1)
