%global source0_hash be8dcabbc09ece4d30a9aa983d5804203b7e2f8054a171f792deff59b56d31fa

# Generated by rust2rpm 28
%bcond check 0
%global debug_package %{nil}

%global crate git2-curl

Name:           rust-git2-curl
Version:        0.21.0
Release:        %autorelease
Summary:        Backend for an HTTP transport in libgit2 powered by libcurl.

License:        MIT OR Apache-2.0
URL:            https://crates.io/crates/git2-curl
Source:         %{crates_source}

BuildRequires:  cargo-rpm-macros >= 24

%global _description %{expand:
Backend for an HTTP transport in libgit2 powered by libcurl.

Intended to be used with the git2 crate.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
%license %{crate_instdir}/LICENSE-APACHE
%license %{crate_instdir}/LICENSE-MIT
%doc %{crate_instdir}/CHANGELOG.md
%{crate_instdir}/

%package     -n %{name}+zlib-ng-compat-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+zlib-ng-compat-devel %{_description}

This package contains library source intended for building other packages which
use the "zlib-ng-compat" feature of the "%{crate}" crate.

%files       -n %{name}+zlib-ng-compat-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
test "%{source0_hash}" = "none" || { f="%{SOURCE0}"; test -f "$f" || { echo "oreon: missing Source0 $f" >&2; exit 1; }; h=$(sha256sum "$f" | awk '{print $1}'); test "$h" = "%{source0_hash}" || { echo "oreon: Source0 hash mismatch" >&2; exit 1; }; }
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
%autochangelog
