# This is boilerplate text for rbldnsd unit files, which can be
# created using "rbldnsctl create" based on the traditional
# configuration variable RBLDNSD as defined in /etc/sysconfig/rbldnsd

[Unit]
Description=DNS daemon for DNSBLs
After=network.target

[Service]
ExecReload=/bin/kill -HUP $MAINPID

[Install]
WantedBy=multi-user.target


