%global source0_hash 779ae4bf7e8421cf91c0b3b64e7e8b40b862fba4d393f59150042de7c4965a94

# Generated by rust2rpm 28
%bcond check 0
%global debug_package %{nil}

%global crate glam

Name:           rust-glam0.28
Version:        0.28.0
Release:        %autorelease
Summary:        A simple and fast 3D math library for games and graphics

License:        MIT OR Apache-2.0
URL:            https://crates.io/crates/glam
Source:         %{crates_source}

BuildRequires:  cargo-rpm-macros >= 24

%global _description %{expand:
A simple and fast 3D math library for games and graphics}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
%license %{crate_instdir}/LICENSE-APACHE
%license %{crate_instdir}/LICENSE-MIT
%doc %{crate_instdir}/CHANGELOG.md
%doc %{crate_instdir}/CONTRIBUTING.md
%doc %{crate_instdir}/README.md
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+approx-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+approx-devel %{_description}

This package contains library source intended for building other packages which
use the "approx" feature of the "%{crate}" crate.

%files       -n %{name}+approx-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+bytecheck-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+bytecheck-devel %{_description}

This package contains library source intended for building other packages which
use the "bytecheck" feature of the "%{crate}" crate.

%files       -n %{name}+bytecheck-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+bytemuck-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+bytemuck-devel %{_description}

This package contains library source intended for building other packages which
use the "bytemuck" feature of the "%{crate}" crate.

%files       -n %{name}+bytemuck-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+core-simd-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+core-simd-devel %{_description}

This package contains library source intended for building other packages which
use the "core-simd" feature of the "%{crate}" crate.

%files       -n %{name}+core-simd-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+cuda-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+cuda-devel %{_description}

This package contains library source intended for building other packages which
use the "cuda" feature of the "%{crate}" crate.

%files       -n %{name}+cuda-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+debug-glam-assert-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+debug-glam-assert-devel %{_description}

This package contains library source intended for building other packages which
use the "debug-glam-assert" feature of the "%{crate}" crate.

%files       -n %{name}+debug-glam-assert-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+fast-math-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+fast-math-devel %{_description}

This package contains library source intended for building other packages which
use the "fast-math" feature of the "%{crate}" crate.

%files       -n %{name}+fast-math-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+glam-assert-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+glam-assert-devel %{_description}

This package contains library source intended for building other packages which
use the "glam-assert" feature of the "%{crate}" crate.

%files       -n %{name}+glam-assert-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+libm-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+libm-devel %{_description}

This package contains library source intended for building other packages which
use the "libm" feature of the "%{crate}" crate.

%files       -n %{name}+libm-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+mint-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+mint-devel %{_description}

This package contains library source intended for building other packages which
use the "mint" feature of the "%{crate}" crate.

%files       -n %{name}+mint-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+rand-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+rand-devel %{_description}

This package contains library source intended for building other packages which
use the "rand" feature of the "%{crate}" crate.

%files       -n %{name}+rand-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+rkyv-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+rkyv-devel %{_description}

This package contains library source intended for building other packages which
use the "rkyv" feature of the "%{crate}" crate.

%files       -n %{name}+rkyv-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+scalar-math-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+scalar-math-devel %{_description}

This package contains library source intended for building other packages which
use the "scalar-math" feature of the "%{crate}" crate.

%files       -n %{name}+scalar-math-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+serde-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+serde-devel %{_description}

This package contains library source intended for building other packages which
use the "serde" feature of the "%{crate}" crate.

%files       -n %{name}+serde-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+std-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+std-devel %{_description}

This package contains library source intended for building other packages which
use the "std" feature of the "%{crate}" crate.

%files       -n %{name}+std-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
test "%{source0_hash}" = "none" || { f="%{SOURCE0}"; test -f "$f" || { echo "oreon: missing Source0 $f" >&2; exit 1; }; h=$(sha256sum "$f" | awk '{print $1}'); test "$h" = "%{source0_hash}" || { echo "oreon: Source0 hash mismatch" >&2; exit 1; }; }
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
%autochangelog
