#!/usr/bin/bash

#parserng launch script

# JPackage Project <http://www.jpackage.org/>
# Source functions library

source /usr/share/java-utils/java-functions

echo $@ | grep -q -e "-verbose"
verbose=$?

if [ $verbose -eq 0 ] ; then
    set -x
fi
: ${MAIN_CLASS:=math.Main}
set_classpath parserng
#export FLAGS="$FLAGS -Djdk.attach.allowAttachSelf=true --add-exports jdk.jdeps/com.sun.tools.javap=ALL-UNNAMED"
run "$@"

