%global source0_hash ceab88cd12c9379daab12ffd303eb58788171d2b58353e6d8e6e05aab7fa8780

# Generated by go2rpm 1.3
%bcond check 0

%global debug_package %{nil}

# https://github.com/xaionaro-go/unsafetools
%global goipath         github.com/xaionaro-go/unsafetools
%global commit          4686db630395367dffebe4dc767686d62cc55e73

%gometa

%global common_description %{expand:
This package provides a FieldByName function to access to any field (including
private/unexported) of a structure. This is meant to be used for unit-tests
only.}

%global golicenses      LICENSE
%global godocs          README.md

Name:           %{goname}
Version:        0
Release:        %autorelease
Summary:        Access to private/unexported fields of a structure

# Upstream license specification: CC0-1.0
# Automatically converted from old format: CC0 - review is highly recommended.
License:        CC0-1.0
URL:            %{gourl}
Source0:        %{gosource}

%if %{with check}
# Tests
BuildRequires:  golang(github.com/stretchr/testify/assert)
%endif

%description
%{common_description}

%gopkg

%prep
test "%{source0_hash}" = "none" || { f="%{SOURCE0}"; test -f "$f" || { echo "oreon: missing Source0 $f" >&2; exit 1; }; h=$(sha256sum "$f" | awk '{print $1}'); test "$h" = "%{source0_hash}" || { echo "oreon: Source0 hash mismatch" >&2; exit 1; }; }

%goprep

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog
%autochangelog
