specfile_path: delve.spec
files_to_sync:
    - delve.spec
    - go-vendor-tools.toml
    - .packit.yml
upstream_package_name: delve
upstream_project_url: https://github.com/go-delve/delve
downstream_package_name: delve
upstream_tag_template: v{version}

actions:
  changelog-entry:
    - bash -c "echo - New release ${PACKIT_PROJECT_VERSION}"
  post-modifications:
    - |
      sh -xeuc "
        cd $PACKIT_DOWNSTREAM_REPO
        export GOTOOLCHAIN=local+auto
        spec=\"$PACKIT_DOWNSTREAM_PACKAGE_NAME.spec\"
        go_vendor_archive create --config go-vendor-tools.toml \"$spec\"
        go_vendor_license \
          --config go-vendor-tools.toml \
          --path \"$spec\" \
          report \
          --verify-spec \
          --autofill=auto
      "

create_sync_note: false

jobs:
- job: pull_from_upstream
  trigger: release
  dist_git_branches:
    rawhide:
      fast_forward_merge_into: [fedora-branched]

- job: koji_build
  trigger: commit
  dist_git_branches: fedora-all

- job: bodhi_update
  trigger: commit
  dist_git_branches: fedora-all
