%global source0_hash b1b6becbca1d6375d426461d95c7daf5532770e4747b4ee600627d97aae10f87

# Generated by go2rpm
%bcond check 0

%global debug_package %{nil}

# https://github.com/smartystreets/assertions
%global goipath         github.com/smartystreets/assertions
Version:                1.2.0

%gometa

%global common_description %{expand:
Package assertions contains the implementations for all assertions which are
referenced in goconvey's convey package and gunit for use with the So(...)
method. They can also be used in traditional Go test functions and even in
applications.}

%global golicenses      LICENSE.md
%global godocs          CONTRIBUTING.md README.md

Name:           %{goname}
# because why would you use releases in ascending order, silly
Epoch:          1
Release:        %autorelease
Summary:        Fluent assertion-style functions used by goconvey and gunit

# Upstream license specification: Apache-2.0 and BSD-3-Clause and MIT
# MIT: main library
# ASL 2.0: internal/oglematchers, internal/go-diff
# BSD: internal/go-render
# Automatically converted from old format: ASL 2.0 and BSD and MIT - review is highly recommended.
License:        Apache-2.0 AND LicenseRef-Callaway-BSD AND LicenseRef-Callaway-MIT
URL:            %{gourl}
Source0:        %{gosource}

%description
%{common_description}

%gopkg

%prep
test "%{source0_hash}" = "none" || { f="%{SOURCE0}"; test -f "$f" || { echo "oreon: missing Source0 $f" >&2; exit 1; }; h=$(sha256sum "$f" | awk '{print $1}'); test "$h" = "%{source0_hash}" || { echo "oreon: Source0 hash mismatch" >&2; exit 1; }; }

%goprep

%install
%gopkginstall

%if %{with check}
%check
# https://github.com/smartystreets/assertions/issues/42
%gocheck -d internal/go-render/render
%endif

%gopkgfiles

%changelog
%autochangelog
