.TH GHERKIN\-GENERATE\-TOKENS "1" "February 2025" "" "User Commands"
.SH NAME
.B gherkin\-generate\-tokens
\(en
generate tokens from Gherkin files
.SH SYNOPSIS
.B gherkin\-generate\-tokens
.IR FILE ...
.SH DESCRIPTION
Outputs tokens from the given files.
.SH OPTIONS
.SH POSITIONAL ARGUMENTS
.I FILE
A Gherkin file
.SH "SEE ALSO"
.BR gherkin (1)
