%global source0_hash 670fdfda89751bc4a84ac13eaa63e205cf0fd22b4c9a5fbfa085b63c1f1d3a30

# Generated by rust2rpm 28
%bcond check 0
%global debug_package %{nil}

%global crate macro_rules_attribute-proc_macro

Name:           rust-macro_rules_attribute-proc_macro
Version:        0.2.2
Release:        %autorelease
Summary:        Use declarative macros as proc_macro attributes or derives

License:        Apache-2.0 OR MIT OR Zlib
URL:            https://crates.io/crates/macro_rules_attribute-proc_macro
Source:         %{crates_source}

BuildRequires:  cargo-rpm-macros >= 24

%global _description %{expand:
Use declarative macros as proc_macro attributes or derives}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
%license %{crate_instdir}/LICENSE-APACHE
%license %{crate_instdir}/LICENSE-MIT
%license %{crate_instdir}/LICENSE-ZLIB

%{crate_instdir}/

%package     -n %{name}+verbose-expansions-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+verbose-expansions-devel %{_description}

This package contains library source intended for building other packages which
use the "verbose-expansions" feature of the "%{crate}" crate.

%files       -n %{name}+verbose-expansions-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
test "%{source0_hash}" = "none" || { f="%{SOURCE0}"; test -f "$f" || { echo "oreon: missing Source0 $f" >&2; exit 1; }; h=$(sha256sum "$f" | awk '{print $1}'); test "$h" = "%{source0_hash}" || { echo "oreon: Source0 hash mismatch" >&2; exit 1; }; }
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
%autochangelog
