	
#Type   Name            ID      GECOS                           Home directory              Shell
	
u       forgejo-runner  -       "Forgejo-Runner System User"    /var/lib/forgejo-runner     /bin/bash
