.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH HERCULESSTUDIO 1 "July  2, 2010"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
HerculesStudio \- Hercules GUI Interface
.SH SYNOPSIS
.B HerculesStudio
.RI [ \-f\ <hercules-config-file> ] 
.RI [ \-r\ <hercules-run-commands-file> ] 
.RI [ \-h ] 
.SH DESCRIPTION
Hercules Studio is a GUI front-end to the Hercules mainframe Emulator
.SH OPTIONS
.TP
.B \-f <hercules-config-file> 
Use <hercules-config-file> as hercules virtual machine configuration file. 
.TP
.B \-r <hercules-run-commands-file>
Run <hercules-run-commands-file> after hercules is started. 
.TP
.B \-h
Print help information. 
.SH SEE ALSO
.BR hercules (1),
.SH AUTHOR
HerculesStudio was written by Jacob Dekel <jacob@mvsdasd.org >.
.PP
This manual page was written by Liang Guo <bluestonechina@gmail.com>,
for the Debian project (and may be used by others). Permission is  granted
to  copy, distribute and/or modify this document under the terms of the GNU 
Free Documentation License, Version 1.1 or any later version published by 
the Free Software Foundation; with no Invariant Sections, no Front-Cover
Texts and no Back-Cover Texts.
