# This is a sample configuration for a wiki instance located under
# /var/www/wiki and exposed as http://thishost/wiki. Please read
# /usr/share/doc/mediawiki/README.RPM on whether to use this
# instance or create copies of it.

# Alias /wiki/skins /usr/share/mediawiki/skins
# <Directory "/usr/share/mediawiki/skins">
#   AllowOverride None
#   Require all granted
# </Directory>
# Alias /wiki /var/www/wiki
# <Directory "/var/www/wiki">
#   SetEnv MW_INSTALL_PATH "/var/www/wiki"
#   AllowOverride None
#   Require all granted
# </Directory>

# If your DocumentRoot points into the wiki itself all that is needed is

# Alias /skins /usr/share/mediawiki/skins
# <Directory "/usr/share/mediawiki/skins">
#   AllowOverride None
#   Require all granted
# </Directory>
