%global source0_hash 308ae749734e28d749a86f33212c7b756748568ce332f970ac1d9cd8531f32e6

# Generated by rust2rpm 26
%bcond check 0
%global debug_package %{nil}

%global crate grep

Name:           rust-grep
Version:        0.3.2
Release:        %autorelease
Summary:        Fast line oriented regex searching as a library

License:        Unlicense OR MIT
URL:            https://crates.io/crates/grep
Source:         %{crates_source}

BuildRequires:  cargo-rpm-macros >= 24

%global _description %{expand:
Fast line oriented regex searching as a library.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
%license %{crate_instdir}/COPYING
%license %{crate_instdir}/LICENSE-MIT
%license %{crate_instdir}/UNLICENSE
%doc %{crate_instdir}/README.md
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+grep-pcre2-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+grep-pcre2-devel %{_description}

This package contains library source intended for building other packages which
use the "grep-pcre2" feature of the "%{crate}" crate.

%files       -n %{name}+grep-pcre2-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+pcre2-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+pcre2-devel %{_description}

This package contains library source intended for building other packages which
use the "pcre2" feature of the "%{crate}" crate.

%files       -n %{name}+pcre2-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
test "%{source0_hash}" = "none" || { f="%{SOURCE0}"; test -f "$f" || { echo "oreon: missing Source0 $f" >&2; exit 1; }; h=$(sha256sum "$f" | awk '{print $1}'); test "$h" = "%{source0_hash}" || { echo "oreon: Source0 hash mismatch" >&2; exit 1; }; }

%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
%autochangelog
