%global source0_hash 75ae8b5984a4863d8a32109a848d038bd6d914f20f010cc141375f7a183c41cf

# Generated by rust2rpm 27
%bcond check 1
%global debug_package %{nil}

%global crate file-locker

Name:           rust-file-locker
Version:        1.1.4
Release:        %autorelease
Summary:        File locking via POSIX advisory record locks

License:        MIT
URL:            https://crates.io/crates/file-locker
Source:         %{crates_source}

BuildRequires:  cargo-rpm-macros >= 24

%global _description %{expand:
File locking via POSIX advisory record locks.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
%license %{crate_instdir}/LICENSE
%doc %{crate_instdir}/README.md
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
test "%{source0_hash}" = "none" || { f="%{SOURCE0}"; test -f "$f" || { echo "oreon: missing Source0 $f" >&2; exit 1; }; h=$(sha256sum "$f" | awk '{print $1}'); test "$h" = "%{source0_hash}" || { echo "oreon: Source0 hash mismatch" >&2; exit 1; }; }

%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
# * Skip due to failure on ppc64le
# * https://todo.sr.ht/~zethra/file-locker/1
%cargo_test -- -- --skip FileLock::lock
%endif

%changelog
%autochangelog
