%global source0_hash 7d343e1967bf9739dc5734c3ba232fb61c35bf68436a948e1b42c70791ea95b2

# Generated by go2rpm
%bcond check 0

# https://github.com/rwcarlsen/goexif
%global goipath         github.com/rwcarlsen/goexif
%global commit          9e8deecbddbd4989a3e8d003684b783412b41e7a

%gometa

%global common_description %{expand:
This package provides decoding of basic exif and tiff encoded data.}

%global golicenses      LICENSE
%global godocs          README.md README-exif.md

Name:           %{goname}
Version:        0
Release:        0.24%{?dist}
Summary:        Decode embedded EXIF meta data from image files

# Upstream license specification: BSD-2-Clause
# Automatically converted from old format: BSD - review is highly recommended.
License:        LicenseRef-Callaway-BSD
URL:            %{gourl}
Source0:        %{gosource}

%description
%{common_description}

%gopkg

%prep
test "%{source0_hash}" = "none" || { f="%{SOURCE0}"; test -f "$f" || { echo "oreon: missing Source0 $f" >&2; exit 1; }; h=$(sha256sum "$f" | awk '{print $1}'); test "$h" = "%{source0_hash}" || { echo "oreon: Source0 hash mismatch" >&2; exit 1; }; }

%goprep
mv exif/README.md README-exif.md

%build
for cmd in exif exifstat; do
  %gobuild -o %{gobuilddir}/bin/$(basename $cmd) %{goipath}/$cmd
done
mv %{gobuilddir}/bin/exif %{gobuilddir}/bin/goexif
mv %{gobuilddir}/bin/exifstat %{gobuilddir}/bin/goexifstat

%install
%gopkginstall
install -m 0755 -vd                     %{buildroot}%{_bindir}
install -m 0755 -vp %{gobuilddir}/bin/* %{buildroot}%{_bindir}/

%if %{with check}
%check
%gocheck
%endif

%files
%license LICENSE
%doc README.md README-exif.md
%{_bindir}/*

%gopkgfiles

%changelog
%autochangelog
