# packit config for glslang
# Build Stage 3 - depends on spirv-tools

jobs:
  - job: koji_build
    trigger: commit | koji_build
    dist_git_branches:
      - fedora-all
    sidetag_group: vulkan-sdk-releases
    dependencies:
      - spirv-tools
    dependents:
      - vulkan-validation-layers
      - vulkan-tools
      - shaderc
