.TH QDARKSTYLE "1" "June 2024" "" "User Commands"
.SH NAME
.B qdarkstyle
\(en QDarkStyle helper
.SH SYNOPSIS
.B qdarkstyle
.RB [ \-h ]
.RB [ \-i ]
.RB [ \-b ]
.RB [ \-a ]
.RB [ \-d ]
.RB [ \-\-all ]
.RB [ \-\-version ]
.SH OPTIONS
Use the option
.B \-\-all
to report bugs (requires
.BR python3-helpdev ).
.TP
.B \-h\fR, \fB\-\-help
Show a help message and exit.
.TP
.B \-i\fR, \fB\-\-information
Show information about environment.
.TP
.B \-b\fR, \fB\-\-bindings
Show available bindings for Qt.
.TP
.B \-a\fR, \fB\-\-abstractions
Show available abstraction layers for Qt bindings.
.TP
.B \-d\fR, \fB\-\-dependencies
Show information about dependencies.
.TP
.B \-\-all
Show all information options at once.
.TP
.B \-v\fR, \fB\-\-version
Show program\(cqs version number and exit.
.SH "SEE\ ALSO"
.BR qdarkstyle.example (1)
.BR qdarkstyle.utils (1)
