.TH FASTAPI\-CLOUD\-LINK "1" "March 2026" "" "User Commands"
.SH NAME
.B fastapi\ cloud\ link
\(en Link a local directory to an existing FastAPI Cloud app.
.SH SYNOPSIS
.B fastapi\ cloud\ link
.RI [ OPTIONS ]
.SH OPTIONS
.TP
.B \-\-help\fR, \fB\-h
Show a help message and exit.
.SH "SEE ALSO"
.BR fastapi\-cloud\-deploy (1),
.BR fastapi\-cloud\-login (1),
.BR fastapi\-cloud\-logs (1),
.BR fastapi\-cloud\-logout (1),
.BR fastapi\-cloud\-whoami (1),
.BR fastapi\-cloud\-unlink (1),
.BR fastapi\-cloud\-setup\-ci (1),
.BR fastapi\-cloud\-env (1)
.P
.BR fastapi\-cloud (1)
.P
.BR fastapi (1)
