.TH FASTAPI\-CLOUD\-ENV\-DELETE "1" "January 2026" "" "User Commands"
.SH NAME
.B fastapi\ cloud\ env\ delete
\(en Delete an environment variable from the app.
.SH SYNOPSIS
.B fastapi\ cloud\ env\ delete
.RI [ OPTIONS ]
.RI [ NAME ]
.RI [ PATH ]
.SH OPTIONS
.TP
.B \-\-help\fR, \fB\-h
Show a help message and exit.
.SS "ARGUMENTS"
.TP
.I NAME
The name of the environment variable to delete.
.TP
.I PATH
A path to the folder containing the app you want to deploy.
.SH "SEE ALSO"
.BR fastapi\-cloud\-env\-list (1),
.BR fastapi\-cloud\-env\-set (1)
.P
.BR fastapi\-cloud\-env (1)
.P
.BR fastapi\-cloud (1)
.P
.BR fastapi (1)
