.TH FASTAPI\-CLOUD\-ENV\-LIST "1" "January 2026" "" "User Commands"
.SH NAME
.B fastapi\ cloud\ env\ list
\(en List the environment variables for the app.
.SH SYNOPSIS
.B fastapi\ cloud\ env\ list
.RI [ OPTIONS ]
.RI [ PATH ]
.SH OPTIONS
.TP
.B \-\-help\fR, \fB\-h
Show a help message and exit.
.SS "ARGUMENTS"
.TP
.I PATH
A path to the folder containing the app you want to deploy.
.SH "SEE ALSO"
.BR fastapi\-cloud\-env\-set (1),
.BR fastapi\-cloud\-env\-delete (1)
.P
.BR fastapi\-cloud\-env (1)
.P
.BR fastapi\-cloud (1)
.P
.BR fastapi (1)
