.TH FASTAPI\-CLOUD\-ENV "1" "March 2026" "" "User Commands"
.SH NAME
.B fastapi\ cloud\ env
.SH SYNOPSIS
.B fastapi\ cloud\ env
.RI [ OPTIONS ]
.I COMMAND
.RI [ ARGS ]...\:
.SH OPTIONS
.TP
.B \-\-help\fR, \fB\-h
Show a help message and exit.
.SS COMMANDS
.TP
.B list
List the environment variables for the app.
.TP
.B delete
Delete an environment variable from the app.
.TP
.B set
Set an environment variable for the app.
.SH "SEE ALSO"
.BR fastapi\-cloud\-env\-list (1),
.BR fastapi\-cloud\-env\-delete (1),
.BR fastapi\-cloud\-env\-set (1)
.P
.BR fastapi\-cloud\-deploy (1),
.BR fastapi\-cloud\-link (1),
.BR fastapi\-cloud\-login (1),
.BR fastapi\-cloud\-logs (1),
.BR fastapi\-cloud\-logout (1),
.BR fastapi\-cloud\-whoami (1),
.BR fastapi\-cloud\-setup\-ci (1),
.BR fastapi\-cloud\-unlink (1)
.P
.BR fastapi\-cloud (1)
.P
.BR fastapi (1)
