%global source0_hash e670041f591d994f54d597ddcd8f4ebc930e282c4c76a42268743b71f0c8b6b3

# Generated by rust2rpm 27
%bcond check 1
%global debug_package %{nil}

%global crate tree-sitter-xml

Name:           rust-tree-sitter-xml
Version:        0.7.0
Release:        %autorelease
Summary:        XML & DTD grammars for tree-sitter

License:        MIT
URL:            https://crates.io/crates/tree-sitter-xml
Source:         %{crates_source}
# include license file
# https://github.com/tree-sitter-grammars/tree-sitter-xml/pull/27
Source:         https://raw.githubusercontent.com/tree-sitter-grammars/%{crate}/refs/tags/v%{version}/LICENSE
# Manually created patch for downstream crate metadata changes
# * include LICENSE
Patch:          tree-sitter-xml-fix-metadata.diff

BuildRequires:  cargo-rpm-macros >= 24

%global _description %{expand:
XML & DTD grammars for tree-sitter.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
%license %{crate_instdir}/LICENSE
%doc %{crate_instdir}/README.md
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
test "%{source0_hash}" = "none" || { f="%{SOURCE0}"; test -f "$f" || { echo "oreon: missing Source0 $f" >&2; exit 1; }; h=$(sha256sum "$f" | awk '{print $1}'); test "$h" = "%{source0_hash}" || { echo "oreon: Source0 hash mismatch" >&2; exit 1; }; }

%autosetup -n %{crate}-%{version} -p1
%cargo_prep
# copy in license file
cp -p %{SOURCE1} .

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
%autochangelog
