%global source0_hash 992fc6e0a575a53350540c57e13dbd7485bf873b3db71ee1b1a9d8f887e58c12

# Generated by go2rpm 1.8.0
%bcond check 0
%global debug_package %{nil}

# https://github.com/google/renameio
%global goipath         github.com/google/renameio/v2
Version:                2.0.0

%gometa -f

%global common_description %{expand:
Provides a way to atomically create or replace a file or
symbolic link}

%global golicenses      LICENSE
%global godocs          CONTRIBUTING.md README.md

Name:           %{goname}
Release:        %autorelease
Summary:        Package renameio provides a way to atomically create or replace a file or symbolic link

License:        Apache-2.0
URL:            %{gourl}
Source:         %{gosource}

%description %{common_description}

%gopkg

%prep
test "%{source0_hash}" = "none" || { f="%{SOURCE0}"; test -f "$f" || { echo "oreon: missing Source0 $f" >&2; exit 1; }; h=$(sha256sum "$f" | awk '{print $1}'); test "$h" = "%{source0_hash}" || { echo "oreon: Source0 hash mismatch" >&2; exit 1; }; }

%goprep

%generate_buildrequires
%go_generate_buildrequires

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog
%autochangelog
