%global source0_hash 3f8d0bd3f69f56a9165dbb360987001e699ab4f57805905d6d85bb7dd884c101

# Generated by rust2rpm 28
%bcond check 0
%global debug_package %{nil}

%global crate ignition-config

Name:           rust-ignition-config
Version:        0.6.1
Release:        %autorelease
Summary:        Data structures for reading/writing Ignition configs

License:        Apache-2.0
URL:            https://crates.io/crates/ignition-config
Source:         %{crates_source}

BuildRequires:  cargo-rpm-macros >= 24

%global _description %{expand:
Data structures for reading/writing Ignition configs}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
%license %{crate_instdir}/LICENSE
%doc %{crate_instdir}/README.md
%{crate_instdir}/

%package     -n %{name}+regenerate-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+regenerate-devel %{_description}

This package contains library source intended for building other packages which
use the "regenerate" feature of the "%{crate}" crate.

%files       -n %{name}+regenerate-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
test "%{source0_hash}" = "none" || { f="%{SOURCE0}"; test -f "$f" || { echo "oreon: missing Source0 $f" >&2; exit 1; }; h=$(sha256sum "$f" | awk '{print $1}'); test "$h" = "%{source0_hash}" || { echo "oreon: Source0 hash mismatch" >&2; exit 1; }; }
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
%autochangelog
