.TH dumpasn1 "1"               "User Manual September 2025"             dumpasn1
.SH NAME
\fBdumpasn1\fR \- ASN.1 object dump/syntax check program

.SH SYNOPSIS
\fB/bin/dumpasn1 [\fIoptions\fB] \fI<file>\fB
\f1

.SH DESCRIPTION
\fBdumpasn1\fR is an ASN.1 display and diagnostic tool used to display binary ASN.1-encoded data in human-readable form.

The program assumes that the input data is binary, having come from a MIME-aware mailer or been piped through a decoding utility if the original format used base64 encoding. If you need to decode it, it's recommended that you use a utility like uudeview, which will strip most kinds of encoding (MIME, PEM, PGP, whatever) to recover the binary original.

.SH OPTIONS:
\
.SS Input Options:

.TP +12n
.B  -
Take input from stdin (some display options will be disabled)
.TP
.B  -q
Disable warning about stdin use affecting display options
.TP
\fB-\fR<number>
Start <number> bytes into the file
.TP
.B   --
End of arg list
.TP
\fB-c\fR<file>
Read Object Identifier info from alternate config file
(values will override equivalents in global config file)

.SS Output Options:
\

.TP +12n
\fB-f\fR<file>
Dump object at offset -<number> to file (allows data to be extracted from encapsulating objects)
.TP
\fB-w\fR<number>
Set width of output, default = 80 columns

.SS Display Options:
\

.TP +12n
.B  -a
Print all data in long data blocks, not just the first 128 bytes
.TP
.B  -d
Print dots to show column alignment
.TP
.B  -g
Display ASN.1 structure outline only (no primitive objects)
.TP
.B  -h
Hex dump object header (tag+length) before the decoded output
.TP
.B  -hh
Same as -h but display more of the object as hex data
.TP
.B  -i
Use shallow indenting, for deeply-nested objects
.TP
.B  -l
Long format, display extra info about Object Identifiers
.TP
\fB-m\fR<number>
Maximum nesting level for which to display content
.TP
.B  -p
Pure ASN.1 output without encoding information
.TP
.B  -t
Display text values next to hex dump of data
.TP
.B  -v
Verbose mode, equivalent to -ahlt

.SS Format Options:
\

.TP +12n
.TP
.B  -e
Don't print encapsulated data inside OCTET/BIT STRINGs
.TP
.B  -r
Print bits in BIT STRING as encoded in reverse order
.TP
.B  -u
Don't format UTCTime/GeneralizedTime string data
.TP
.B  -x
Display size and offset in hex not decimal

.SS Checking Options:
\

.TP +12n
.B  -o
Don't check validity of character strings hidden in octet strings
.TP
.B  -s
Syntax check only, don't dump ASN.1 structures
.TP
.B  -z
Allow zero-length items

Warnings generated by deprecated OIDs require the use of '-l' to be displayed.

Program return code is the number of errors found or EXIT_SUCCESS.

.SH FILES
\fI./dumpasn1.cfg, $HOME/.dumpasn1.cfg, /etc/dumpasn1/dumpasn1.cfg\f1: This is the configuration file, it will be searched in this order. It contains OIDs commonly used.

.SH AUTHORS

ASN.1 data display code copyright Peter Gutmann based on ASN.1 dump program by David Kemp, with contributions from various people including Matthew Hamrick, Bruno Couillard, Hallvard Furuseth, Geoff Thorpe, David Boyce, John Hughes, 'Life is hard, and then you die', Hans-Olof Hermansson, Tor Rustad, Kjetil Barvik, James Sweeny, Chris Ridd, David Lemley, John Tobey, James Manger, Igor Perminov, and several other people whose names I've misplaced.

dumpasn1 is available at \fBhttps://github.com/cryptlib/dumpasn1/\f1

.SH COPYRIGHT
dumpasn1 is licensed under the MIT license. (https://github.com/cryptlib/dumpasn1/blob/main/LICENSE)

.SH COMMENTS
This man page has been derived from the internal help page.
