%global source0_hash ed08d8f98b4620637be97602d4c9e13c0b53e2347bb21a3a0a8f85ad9919b7dd

# Generated by go2rpm 1.12.0
%bcond check 0
%global debug_package %{nil}

# https://github.com/go-test/deep
%global goipath         github.com/go-test/deep
Version:                1.1.1

%gometa -L

%global common_description %{expand:
Golang deep variable equality test that returns human-readable differences.}

%global golicenses      LICENSE
%global godocs          CHANGES.md README.md SECURITY.md

Name:           golang-github-test-deep
Release:        %autorelease
Summary:        Golang deep variable equality test
License:        MIT
URL:            %{gourl}
Source:         %{gosource}

%description %{common_description}

%gopkg

%prep
test "%{source0_hash}" = "none" || { f="%{SOURCE0}"; test -f "$f" || { echo "oreon: missing Source0 $f" >&2; exit 1; }; h=$(sha256sum "$f" | awk '{print $1}'); test "$h" = "%{source0_hash}" || { echo "oreon: Source0 hash mismatch" >&2; exit 1; }; }

%goprep -A
%autopatch -p1

%generate_buildrequires
%go_generate_buildrequires

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog
%autochangelog
