%global source0_hash fb3aa78ecda1ebc9ec9847d5d3aba7d618823446a049ba2491940506da6e2782

# Generated by rust2rpm 28
# * outdated dev-dependencies: rstest ^0.12, simple_logger ^2.1
%bcond check 0
%global debug_package %{nil}

%global crate serde-xml-rs

Name:           rust-serde-xml-rs0.6
Version:        0.6.0
Release:        %autorelease
Summary:        Xml-rs based deserializer for Serde (compatible with 0.9+)

License:        MIT
URL:            https://crates.io/crates/serde-xml-rs
Source:         %{crates_source}

BuildRequires:  cargo-rpm-macros >= 24

%global _description %{expand:
Xml-rs based deserializer for Serde (compatible with 0.9+).}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
%license %{crate_instdir}/LICENSE
%doc %{crate_instdir}/README.md
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
test "%{source0_hash}" = "none" || { f="%{SOURCE0}"; test -f "$f" || { echo "oreon: missing Source0 $f" >&2; exit 1; }; h=$(sha256sum "$f" | awk '{print $1}'); test "$h" = "%{source0_hash}" || { echo "oreon: Source0 hash mismatch" >&2; exit 1; }; }

%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
%autochangelog
