%global source0_hash a251099ad7b7791be0e96f646ec486d8c047d44107eb9219e18b74d76d6529da

# Generated by go2rpm 1
%bcond check 0

# https://github.com/gobwas/ws
%global goipath         github.com/gobwas/ws
Version:                1.4.0

%gometa

%global common_description %{expand:
Tiny WebSocket library for Go.}

%global golicenses      LICENSE
%global godocs          example README.md

Name:           %{goname}
Release:        8%{?dist}
Summary:        Tiny WebSocket library

License:        MIT
URL:            %{gourl}
Source0:        %{gosource}

BuildRequires:  golang(github.com/gobwas/httphead)
BuildRequires:  golang(github.com/gobwas/pool)

%description
%{common_description}

%gopkg

%prep
test "%{source0_hash}" = "none" || { f="%{SOURCE0}"; test -f "$f" || { echo "oreon: missing Source0 $f" >&2; exit 1; }; h=$(sha256sum "$f" | awk '{print $1}'); test "$h" = "%{source0_hash}" || { echo "oreon: Source0 hash mismatch" >&2; exit 1; }; }

%goprep

%build
for cmd in autobahn; do
  %gobuild -o %{gobuilddir}/bin/$(basename $cmd) %{goipath}/$cmd
done
rm -rf %{gobuilddir}/usr/share/gocode/src/github.com/gobwas/ws/server_test.s

%install
%gopkginstall
install -m 0755 -vd                     %{buildroot}%{_bindir}
install -m 0755 -vp %{gobuilddir}/bin/* %{buildroot}%{_bindir}/

%if %{with check}
%check
%gocheck
%endif

%files
%license LICENSE
%doc example README.md
%{_bindir}/*

%gopkgfiles

%changelog
%autochangelog
