%global source0_hash 46502ad458c9a52b69d4d4d32775c788b7a1b85e8bc9d482d92250fc0e3f8efe

# Generated by rust2rpm 28
%bcond check 0
%global debug_package %{nil}

%global crate blake2

Name:           rust-blake2
Version:        0.10.6
Release:        %autorelease
Summary:        BLAKE2 hash functions

License:        MIT OR Apache-2.0
URL:            https://crates.io/crates/blake2
Source:         %{crates_source}

BuildRequires:  cargo-rpm-macros >= 24

%global _description %{expand:
BLAKE2 hash functions}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
%license %{crate_instdir}/LICENSE-APACHE
%license %{crate_instdir}/LICENSE-MIT
%doc %{crate_instdir}/CHANGELOG.md
%doc %{crate_instdir}/README.md
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+reset-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+reset-devel %{_description}

This package contains library source intended for building other packages which
use the "reset" feature of the "%{crate}" crate.

%files       -n %{name}+reset-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+simd-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+simd-devel %{_description}

This package contains library source intended for building other packages which
use the "simd" feature of the "%{crate}" crate.

%files       -n %{name}+simd-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+simd_asm-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+simd_asm-devel %{_description}

This package contains library source intended for building other packages which
use the "simd_asm" feature of the "%{crate}" crate.

%files       -n %{name}+simd_asm-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+simd_opt-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+simd_opt-devel %{_description}

This package contains library source intended for building other packages which
use the "simd_opt" feature of the "%{crate}" crate.

%files       -n %{name}+simd_opt-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+size_opt-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+size_opt-devel %{_description}

This package contains library source intended for building other packages which
use the "size_opt" feature of the "%{crate}" crate.

%files       -n %{name}+size_opt-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+std-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+std-devel %{_description}

This package contains library source intended for building other packages which
use the "std" feature of the "%{crate}" crate.

%files       -n %{name}+std-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
test "%{source0_hash}" = "none" || { f="%{SOURCE0}"; test -f "$f" || { echo "oreon: missing Source0 $f" >&2; exit 1; }; h=$(sha256sum "$f" | awk '{print $1}'); test "$h" = "%{source0_hash}" || { echo "oreon: Source0 hash mismatch" >&2; exit 1; }; }
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
%autochangelog
