%global source0_hash d0ca030c0a3a9283d5945f5576877f08becdbf2b983e12a634d0597a1a1678b5

# Generated by go2rpm
%bcond check 0

%global debug_package %{nil}

# https://github.com/bshuster-repo/logrus-logstash-hook
%global goipath         github.com/bshuster-repo/logrus-logstash-hook
Version:                1.1.0

%gometa

%global common_description %{expand:
Use this hook to send the logs to Logstash.}

%global golicenses      LICENSE
%global godocs          CHANGELOG.md README.md

Name:           %{goname}
Release:        %autorelease
Summary:        Logstash hook for logrus

License:        MIT
URL:            %{gourl}
Source0:        %{gosource}

BuildRequires:  golang(github.com/sirupsen/logrus)

%description
%{common_description}

%gopkg

%prep
test "%{source0_hash}" = "none" || { f="%{SOURCE0}"; test -f "$f" || { echo "oreon: missing Source0 $f" >&2; exit 1; }; h=$(sha256sum "$f" | awk '{print $1}'); test "$h" = "%{source0_hash}" || { echo "oreon: Source0 hash mismatch" >&2; exit 1; }; }

%goprep

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog
%autochangelog
