[General]
AudioSystem=0

[Radios]
1\AudioInput=default
1\AudioOutput=default
1\ForceRTSasPTT=false
1\GUID={703948b1-91eb-46cc-8014-8d42021d6e41}
1\RigCIVuInt=0
1\RigName=<NONE>
1\SerialPortBaud=115200
1\SerialPortRadio=auto
1\WaterfallFormat=0
size=1

[Server]
ServerAudioPort=50003
ServerCivPort=50002
ServerControlPort=50001
ServerEnabled=true
Users\1\Password=(+\\Dz\"6w
Users\1\UserType=0
Users\1\Username=user
Users\size=1
