Alias /anyterm /usr/share/anyterm

<Location /anyterm>
   # admins are greatly encouraged to uncomment and 
   # install/use mod_ssl here to secure traffic 
   # SSLRequireSSL 
   # Require valid-user
   # AuthType YYY

   DirectoryIndex anyterm.html
</Location>

<Location /anyterm/proxy>
   # admins are greatly encouraged to uncomment and 
   # install/use mod_ssl here to secure traffic 
   # SSLRequireSSL 
   # Require valid-user
   # AuthType YYY

   # proxy to the local-only anyterm daemon
   ProxyPass http://localhost:81 ttl=60
   ProxyPassReverse http://localhost:81
</Location>

