%global source0_hash none

Name:           med
Version:        5.0.0
Release:        9%{?dist}
Summary:        Library to exchange meshed data

License:        LGPL-3.0-or-later
URL:            https://www.salome-platform.org/
Source0:        https://files.salome-platform.org/Salome/medfile/%{name}-%{version}.tar.bz2

# - Install headers in %%_includedir/med
# - Install cmake config files to %%_libdir/cmake
# - Install doc to %%_pkgdocdir
# - Use GNUInstallDirs for libdir
Patch0:         med_cmake.patch
# Fix python3.13 build
Patch1:         med-py3.13.patch
# Fix compatibility with hdf-1.14
Patch2:         hdf5-1.14.patch
# Fix swig-4.3.0 compatibility
Patch3:         med-swig-4.3.0.patch
# Fix build with gcc15
Patch4:         med-gcc15.patch

BuildRequires:  gcc-c++
BuildRequires:  cmake
BuildRequires:  gcc
BuildRequires:  gcc-gfortran
BuildRequires:  hdf5-devel
BuildRequires:  make
BuildRequires:  python3-devel
BuildRequires:  swig
BuildRequires:  zlib-devel

# For autoreconf
BuildRequires: autoconf automake libtool

%description
MED-fichier (Modélisation et Echanges de Données, in English Modelisation
and Data Exchange) is a library to store and exchange meshed data or
computation results. It uses the HDF5 file format to store the data.

%package -n     python3-%{name}
Summary:        Python3 bindings for %{name}
Requires:       %{name}%{?_isa} = %{version}-%{release}

%description -n python3-%{name}
The python3-%{name} package contains python3 bindings for %{name}.

%package        tools
Summary:        Runtime tools for %{name}
Requires:       %{name}%{?_isa} = %{version}-%{release}
Requires:       tk

%description    tools
This package contains runtime tools for %{name}:
  - mdump: a tool to dump MED files
  - xmdump: graphical version of mdump.
  - medconforme: a tool to validate a MED file
  - medimport: a tool to convert a MED v2.1 or v2.2 file into a MED v2.3 file

%package        devel
Summary:        Development files for %{name}
Requires:       %{name}%{?_isa} = %{version}-%{release}
Requires:       cmake-filesystem

%description    devel
The %{name}-devel package contains libraries and header files for
developing applications that use %{name}.

%package        doc
Summary:        Documentation for %{name}
BuildArch:      noarch

%description    doc
The %{name}-doc package contains the documentation for %{name}.

%prep
%autosetup -p1 -n %{name}-%{version}

# Delete files generated by swig
grep -l 'This file was automatically generated' python/* | xargs rm

%build
%cmake -DMEDFILE_BUILD_PYTHON=1 \
    -DPYTHON_EXECUTABLE=%{__python3} \
    -DPYTHON_INCLUDE_DIR=%{_includedir}/python%{python3_version}$(python3-config --abiflags)/ \
    -DPYTHON_LIBRARY=%{_libdir}/libpython%{python3_version}$(python3-config --abiflags).so
%cmake_build

%install
%cmake_install

# Remove test-suite files
rm -rf %{buildroot}%{_bindir}/testc
rm -rf %{buildroot}%{_bindir}/testf
rm -rf %{buildroot}%{_bindir}/testpy

%check
%ctest || :

%files
%doc AUTHORS ChangeLog  README
%license COPYING.LESSER
%{_libdir}/libmed.so.1*
%{_libdir}/libmedC.so.1*
%{_libdir}/libmedimport.so.0*
%{_libdir}/libmedfwrap.so.11*

%files -n python3-%{name}
%{python3_sitearch}/%{name}/

%files tools
%{_bindir}/*mdump*
%{_bindir}/medconforme
%{_bindir}/medimport

%files devel
%{_libdir}/*.so
%{_libdir}/cmake/MEDFile/
%{_includedir}/%{name}/

%files doc
%license COPYING.LESSER
%doc %{_pkgdocdir}

%changelog
%autochangelog
