---
downstream_package_name: objenesis
specfile_path: objenesis.spec
upstream_package_name: objenesis
upstream_project_url: https://github.com/easymock/objenesis

jobs:
- job: pull_from_upstream
  trigger: release
  dist_git_branches:
    - fedora-rawhide

- job: koji_build
  trigger: commit
  dist_git_branches:
    - fedora-rawhide
