.TH SDLHACK 1 "NOVEMBER 2010" sdlhack "Linux User's Manual"
.SH NAME
sdlhack \- Force SDL fullscreen games to minimize
.SH SYNOPSIS
.B sdlhack [options] game [arguments]
.SH DESCRIPTION
SDLHack is a wrapper for SDL which lets you force full-screen games to minimize.
It also allows you to disable joystick detection.
.SH OPTIONS
.IP -h
show brief help
.IP -d
disable joystick
.SH AUTHOR
Jared Stafford <jspenguin at gmail dot com)


