%global source0_hash 4435396023e8997ee6119c8519e8c91d46a08ba6e22806f495f3a2f070c71f6d

# Generated by go2rpm 1.9.0
%bcond check 0
%global debug_package %{nil}

# https://github.com/alecthomas/kong
%global goipath         github.com/alecthomas/kong
Version:                1.13.0

%gometa -f

%global common_description %{expand:
Kong is a command-line parser for Go.}

%global golicenses      COPYING
%global godocs          _examples README.md

Name:           %{goname}
Release:        %autorelease
Summary:        Command-line parser for Go

License:        MIT
URL:            %{gourl}
Source:         %{gosource}

%description %{common_description}

%gopkg

%prep
test "%{source0_hash}" = "none" || { f="%{SOURCE0}"; test -f "$f" || { echo "oreon: missing Source0 $f" >&2; exit 1; }; h=$(sha256sum "$f" | awk '{print $1}'); test "$h" = "%{source0_hash}" || { echo "oreon: Source0 hash mismatch" >&2; exit 1; }; }

%goprep
%autopatch -p1

%generate_buildrequires
%go_generate_buildrequires

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog
%autochangelog
