%global source0_hash dc9c802e0df5d0638fd4847ab18b9adbbc174f4feccf2de60f53e63eff95e50f

# Generated by go2rpm 1.14.0
%bcond check 1
%bcond bootstrap 0

%global debug_package %{nil}
%if %{with bootstrap}
%global __requires_exclude %{?__requires_exclude:%{__requires_exclude}|}^golang\\(.*\\)$
%endif

# https://github.com/shirou/gopsutil
%global goipath         github.com/shirou/gopsutil/v4
Version:                4.24.12

%gometa -L -f

%global common_description %{expand:
Psutil for golang.}

%global golicenses      LICENSE
%global godocs          README.md windows_memo.rst

Name:           golang-github-shirou-gopsutil4
Release:        %autorelease
Summary:        Psutil for golang

License:        BSD-3-Clause
URL:            %{gourl}
Source:         %{gosource}

BuildRequires:	/usr/bin/pgrep

%description %{common_description}

%gopkg

%prep
test "%{source0_hash}" = "none" || { f="%{SOURCE0}"; test -f "$f" || { echo "oreon: missing Source0 $f" >&2; exit 1; }; h=$(sha256sum "$f" | awk '{print $1}'); test "$h" = "%{source0_hash}" || { echo "oreon: Source0 hash mismatch" >&2; exit 1; }; }

%goprep -A
%autopatch -p1

%if %{without bootstrap}
%generate_buildrequires
%go_generate_buildrequires
%endif

%install
%gopkginstall

%if %{without bootstrap}
%if %{with check}
%check
export CI=true
# TestUsers: needs access to /var/run/utmp
for test in "TestCountsAgainstLscpu" "TestUsers" "TestCwd" \
; do
awk -i inplace '/^func.*'"$test"'\(/ { print; print "\tt.Skip(\"disabled failing test\")"; next}1' $(grep -rl $test)
done
%gocheck
%endif
%endif

%gopkgfiles

%changelog
%autochangelog
