.TH GENGO\-DIRECTORY "1" "November 2024" "" "User Commands"
.SH NAME
.B gengo\ directory
\(en
.B BETA
Analyze a directory
.SH SYNOPSIS
.B gengo\ directory
.RI [ OPTIONS ]
.SH OPTIONS
.TP
.B \-D\fR, \fB\-\-directory\ \fIDIRECTORY
The path to the directory to analyze
[default:
.BR .]
.TP
.B \-h\fR, \fB\-\-help
Print help
.TP
.B \-V\fR, \fB\-\-version
Print version
.SH "SEE ALSO"
.BR gengo-git (1)
.P
.BR gengo (1)
