.TH GENGO\-GIT "1" "November 2024" "" "User Commands"
.SH NAME
.B gengo\ git
\(en
Analyze a git repository
.SH SYNOPSIS
.B gengo\ git
.RI [ OPTIONS ]
.SH OPTIONS
.TP
.B \-R\fR, \fB\-\-repository\ \fIREPOSITORY
The path to the repository to analyze
[default:
.BR .]
.TP
.B \-r\fR, \fB\-\-rev\ \fIREVISION
The git revision to analyze
[default:
.BR HEAD ]
.TP
.B \-h\fR, \fB\-\-help
Print help
.TP
.B \-V\fR, \fB\-\-version
Print version
.SH "SEE ALSO"
.BR gengo-directory (1)
.P
.BR gengo (1)
