# Configuration snippet for vdr-skinenigmang                   -*- sh -*-
#
# Add command line options to pass to the skinenigmang plugin to PLUGIN_OPTIONS.
# See /usr/share/doc/vdr-skinenigmang-*/README for info about available options.

PLUGIN_OPTIONS=""
