# For more information about this file, see the ntp.conf(5) man page.

# Use public servers from the pool.ntp.org project.
# Please consider joining the pool (https://www.pool.ntp.org/join.html).
pool 2.VENDORZONE.pool.ntp.org iburst

# Reduce the maximum number of servers used from the pool.
tos maxclock 5

# Record the frequency of the system clock.
driftfile VARNTP/drift

# Disable configuration and monitoring access by default.
restrict default nomodify noquery

# Enable all access for localhost.
restrict 127.0.0.1
restrict ::1

# Enable writing of statistics records.
#statistics clockstats cryptostats loopstats peerstats
