.TH "ETR" "6"
.SH "NAME"
extremetuxracer \- 3D-Rennspiel mit Tux, dem Linux-Pinguin
.SH "SYNOPSIS"
.PP
\fBetr\fR
.SH "BESCHREIBUNG"
.PP
\fBetr\fR alias Extreme Tux Racer ist ein einfaches OpenGL-Rennspiel mit Tux, dem Linux
Maskottchen. Ziel ist es einen schnee- und eisbedeckten Berg so schnell
wie möglich hinunterzurutschen und dabei möglichst viele Fische
einzusammeln. Vermeiden Sie Bäume und felsigen Untergrund, der Sie
abbremsen wird.
.SH "OPTIONEN"
.PP
Für dieses Spiel existieren keine Kommandozeilenparameter.
