%global source0_hash 7aa6cfd69a1235ab2b3f9fc2015a2d8d92068d4a241283cb7ac5d6d22c9b84a5

# Generated by go2rpm 1.11.1
%bcond check 0
%global debug_package %{nil}

# https://github.com/miekg/dns
%global goipath         github.com/miekg/dns
Version:                1.1.73

%gometa -L

%global common_description %{expand:
Complete and usable DNS library. All Resource Records are supported, including
the DNSSEC types. It follows a lean and mean philosophy. If there is stuff you
should know as a DNS programmer there isn't a convenience function for it.
Server side and client side programming is supported, i.e. you can build servers
and resolvers with it.}

%global golicenses      COPYRIGHT LICENSE
%global godocs          AUTHORS CONTRIBUTORS README.md

Name:           golang-github-miekg-dns
Release:        %autorelease
Summary:        DNS library in Go

License:        BSD-3-Clause
URL:            %{gourl}
Source:         %{gosource}

%description %{common_description}

%gopkg

%prep
test "%{source0_hash}" = "none" || { f="%{SOURCE0}"; test -f "$f" || { echo "oreon: missing Source0 $f" >&2; exit 1; }; h=$(sha256sum "$f" | awk '{print $1}'); test "$h" = "%{source0_hash}" || { echo "oreon: Source0 hash mismatch" >&2; exit 1; }; }

%goprep -A
%autopatch -p1

%generate_buildrequires
%go_generate_buildrequires

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog
%autochangelog
