# mod_cluster modules configuration
# See http://modcluster.io/ for docs, tutorials and examples

# Load mod_cluster modules
# Please, note:
#  - mod_cluster cannot coexist with proxy_balancer_module; disable it
#  - mod_cluster needs proxy_module and proxy_ajp_module loaded for AJP transport

# Uncomment to enable mod_cluster:
#LoadModule proxy_cluster_module modules/mod_proxy_cluster.so
#LoadModule cluster_slotmem_module modules/mod_cluster_slotmem.so
#LoadModule manager_module modules/mod_manager.so
#LoadModule advertise_module modules/mod_advertise.so

<IfModule manager_module>
  # Place for slotmem files - do not set this to NFS/CIFS
  MemManagerFile /var/cache/httpd/mod_cluster

  # We suggest to use a restricted VirtualHost
  # for receiving MCPM (Mod Cluster Protocol Message) from worker nodes.
  # To allow 6666 port for httpd, install policycoreutils-python-utils
  # and then label it:
  #
  #    semanage port -a -t http_port_t -p tcp 6666
  #
  # For UDP datagrams with httpd's location to be sent to UDP Multicast address, one might have
  # to allow it:
  #
  #    semanage port -a -t http_port_t -p udp 23364
  #
  # also Firewalld might need to know about it (depends on your network
  # domains and particular setup), example:
  #
  #    firewall-cmd --add-port=6666/tcp
  #    firewall-cmd --add-port=6666/tcp --permanent
  #
  #
  Listen 6666
  <VirtualHost *:6666>

    <Location />
      # Change this to the range from which worker nodes are
      # going to contact the Apache HTTP Server,
      # e.g. your 10. internal network.
      Require ip 127.0.0.1
      # Worker nodes need to be contacted by Apache HTTP Server and also they
      # need to be able to initiate connections to Apache HTTP Server.
      # For example, if you have 2 workers reporting on your console
      # (see Management and monitoring console below) as:
      #
      #    <h1> Node worker-1 (ajp://192.168.122.138:8011): </h1>
      #    <h1> Node worker-2 (ajp://192.168.122.138:8012): </h1>
      #
      # you might need to label these ports for Selinux:
      #
      #    semanage port -a -t http_port_t -p tcp 8012
      #    semanage port -a -t http_port_t -p tcp 8011
      #
      # See aforementioned firewall-cmd for firewall settings.
    </Location>

    # Apache HTTP Server advertises its presence
    # on 224.0.1.105:23364 via UDP multicast by default.
    # One has to allow this through Selinux:
    #
    #    semanage port -a -t http_port_t -p udp 23364
    #
    ServerAdvertise on

    # Here we declare that THIS and none other VirtualHost can
    # process configuration messages from worker nodes.
    EnableMCPMReceive

    # Management and monitoring console with the following default setup
    # appears on http://<your httpd address>:6666/mod_cluster_manager
    # and it is accessible only from localhost.
    <Location /mod_cluster_manager>
      SetHandler mod_cluster-manager
      Require ip 127.0.0.1
    </Location>
  </VirtualHost>
</IfModule>

