%global source0_hash 3f7fdc86e3db433c48cb6505fe3000ec1b3e84a4a40a84ad67b8df3a847f0697

%global pypi_name llfuse

Name:               python-llfuse
Version:            1.5.2
Release:            2%{?dist}
Summary:            Python Bindings for the low-level FUSE API
License:            LGPL-2.0-or-later
URL:                https://pypi.python.org/pypi/llfuse
Source0:            %{pypi_source %{pypi_name}}
Patch1:             python-llfuse-new-build-ext.patch

BuildRequires:      gcc
BuildRequires:      libattr-devel
BuildRequires:      fuse >= 2.9.0
BuildRequires:      fuse-devel >= 2.9.0
BuildRequires:      python3-Cython
BuildRequires:      python3-devel
BuildRequires:      pyproject-rpm-macros
BuildRequires:      python3dist(pytest)

%description
LLFUSE is a set of Python bindings for the low level FUSE API.
LLFUSE was originally part of S3QL, but has been factored out so that it can be
used by other projects as well.

%package -n python3-llfuse
Summary:            Python Bindings for the low-level FUSE API Python %{python3_version} packages
%{?python_provide:%python_provide python%{python3_pkgversion}-llfuse}

%description -n python%{python3_pkgversion}-llfuse
LLFUSE is a set of Python %{python3_version} bindings for the low level FUSE API.
LLFUSE was originally part of S3QL, but has been factored out so that it can be
used by other projects as well.

%prep
test "%{source0_hash}" = "none" || { f="%{SOURCE0}"; test -f "$f" || { echo "oreon: missing Source0 $f" >&2; exit 1; }; h=$(sha256sum "$f" | awk '{print $1}'); test "$h" = "%{source0_hash}" || { echo "oreon: Source0 hash mismatch" >&2; exit 1; }; }

%autosetup -n llfuse-%{version}
rm -rf src/llfuse.egg-info

# Remove the cythonized files in order to regenerate them during build.
rm $(grep -rl '/\* Generated by Cython')

%generate_buildrequires
%pyproject_buildrequires -r

%build
%{__python3} setup.py build_cython
%pyproject_wheel

%install
%pyproject_install
%pyproject_save_files %{pypi_name}

%check
%pytest -v test

%files -n python3-%{pypi_name} -f %{pyproject_files}
%doc README.rst Changes.rst

%changelog
%autochangelog
