upstream_package_name: awscli
downstream_package_name: awscli2

upstream_project_url: https://github.com/aws/aws-cli

# react only to v2 tags, skip patch versions
upstream_tag_include: "^2\\.\\d+\\.0"

specfile_path: awscli2.spec

jobs:
  - job: pull_from_upstream
    trigger: release
    dist_git_branches:
      - fedora-all

  - job: koji_build
    trigger: commit
    dist_git_branches:
      - fedora-all

  - job: bodhi_update
    trigger: commit
    dist_git_branches:
      - fedora-branched
