%global source0_hash 6e825cfb1cbc32dc2273bff2132f107395d111b4ef20d0637d86a6603422d3eb

Name:           cohomCalg
Version:        0.32
Release:        22%{?dist}
Summary:        Sheaf cohomologies for line bundles on toric varieties

License:        GPL-3.0-or-later
URL:            https://github.com/BenjaminJurke/cohomCalg
VCS:            git:%{url}.git
Source0:        %{url}/archive/v%{version}/%{name}-%{version}.tar.gz
# Test output generated by Jerry James with cohomCalg on the upstream-tested
# architecture (x86_64), to verify that other architectures generate the same
# output.
Source1:        %{name}-test.tar.xz
# Fix a typo that skips an assignment
Patch:          https://github.com/BenjaminJurke/cohomCalg/commit/e2c2635.patch

# See https://fedoraproject.org/wiki/Changes/EncourageI686LeafRemoval
ExcludeArch:    %{ix86}

BuildRequires:  gcc-c++
BuildRequires:  make
BuildRequires:  tex(latex)
BuildRequires:  tex(extdash.sty)
BuildRequires:  tex(hyperxmp.sty)
BuildRequires:  tex(totpages.sty)
BuildRequires:  texlive-rsfs
BuildRequires:  texlive-txfonts
BuildRequires:  texlive-utopia

%description
This package computes sheaf cohomologies for line bundles on toric varieties.

%package doc
# The content is GPL-3.0-or-later.  The remaining licenses cover the various
# fonts embedded in PDFs.
# AMS: OFL-1.1-RFN
# CM: Knuth-CTAN
# CM-Super: GPL-1.0-or-later
# Txfonts: GPL-1.0-or-later
# Utopia: LicenseRef-Utopia
License:        GPL-3.0-or-later AND OFL-1.1-RFN AND Knuth-CTAN AND GPL-1.0-or-later AND LicenseRef-Utopia
Summary:        Manual for %{name}
BuildArch:      noarch

%description doc
User manual for %{name}.

%prep
test "%{source0_hash}" = "none" || { f="%{SOURCE0}"; test -f "$f" || { echo "oreon: missing Source0 $f" >&2; exit 1; }; h=$(sha256sum "$f" | awk '{print $1}'); test "$h" = "%{source0_hash}" || { echo "oreon: Source0 hash mismatch" >&2; exit 1; }; }

%autosetup -p1 -a 1

%conf
# Remove prebuilt Windows binaries and the prebuilt manual
rm -f bin/*.exe manual.pdf

%build
# Build the binary
%make_build CFLAGS="%{build_cflags}" CXXFLAGS="%{build_cxxflags}"

# Build the manual
cd manual/latex_source
pdflatex manual
bibtex manual
pdflatex manual
pdflatex manual

%install
mkdir -p %{buildroot}%{_bindir}
cp -p bin/cohomcalg %{buildroot}%{_bindir}

%check
# Do not check P31SU8.in; it takes about half a day on a reasonably fast
# computer.
pushd bin
for fil in CP2 P31SU7 Quintic WCP11114 dP1 dP3; do
  ./cohomcalg --integrated $fil.in 2>/dev/null | diff -q out/$fil.out -
done
popd

%files
%license LICENSE
%doc README.md
%{_bindir}/cohomcalg

%files doc
%doc manual/latex_source/manual.pdf

%changelog
%autochangelog
