Alias /wsapi/2.0 /usr/share/yubikey-val

<Location /wsapi/2.0>
    Require local
    # Require ip 10.1.2.3
    # Require host example.org
    <IfModule mod_php5.c>
        # Keep old config directory /etc/ykval for compatibility
        php_value include_path ".:/etc/ykval:/etc/yubico/val:/usr/share/yubikey-val"
    </IfModule>
</Location>

<Directory /usr/share/yubikey-val>
    Options +FollowSymLinks
    RewriteEngine on
    RewriteBase "/wsapi/2.0/"
    RewriteRule ^([^/\.\?]+)(\?.*)?$ ykval-$1.php$2 [L]
</Directory>
