.TH RTAS_ERRD "8" "rtas_errd" "System Administration Utilities"
.SH NAME
rtas_errd \- rtas_errd
.SH SYNOPSIS
.B rtas_errd
[\fI\,OPTION\/\fR]
.SH DESCRIPTION
.TP
\fB\-c\fR, \fB\-\-config\fR=\fI\,FILE\/\fR
path to config file (default \fI\,/etc/ppc64\-diag/ppc64\-diag.config\/\fP)
.TP
\fB\-d\fR, \fB\-\-debug\fR
don't daemonize, increase librtas debug level
.TP
\fB\-e\fR, \fB\-\-epowfile\fR=\fI\,FILE\/\fR
path to epow status file (default \fI\,/var/log/epow_status\/\fP)
.TP
\fB\-f\fR, \fB\-\-file\fR=\fI\,FILE\/\fR
path to RTAS test file
.TP
\fB\-h\fR, \fB\-\-help\fR
help (this message)
.TP
\fB\-l\fR, \fB\-\-logfile\fR=\fI\,FILE\/\fR
path to rtas_errd debug logfile (default \fI\,/var/log/rtas_errd.log\/\fP)
.TP
\fB\-m\fR, \fB\-\-msgsfile\fR=\fI\,FILE\/\fR
path to syslog
.TP
\fB\-p\fR, \fB\-\-platformfile\fR=\fI\,FILE\/\fR
path to platform_log (default \fI\,/var/log/platform\/\fP)
.TP
\fB\-R\fR, \fB\-\-nodrmgr\fR
no drmgr
.TP
\fB\-s\fR, \fB\-\-scenario\fR=\fI\,FILE\/\fR
path to RTAS scenario file
