%global source0_hash b59e46941c09c6e6f062e162a07cd6c84458564ab6ae77661ab8295e74351cba

# Generated by go2rpm 1.11.1
%bcond check 0

# https://github.com/neurosnap/sentences
%global goipath         gopkg.in/neurosnap/sentences.v1
%global forgeurl        https://github.com/neurosnap/sentences
Version:                1.1.2

%gometa -L -f

%global common_description %{expand:
A multilingual command line sentence tokenizer in Golang.}

%global golicenses      LICENSE.md
%global godocs          CHANGES.md README.md test_files/english/anarchy.txt\\\
                        test_files/english/anarchy_s.txt\\\
                        test_files/english/carolyn.txt\\\
                        test_files/english/carolyn_s.txt\\\
                        test_files/english/clinton.txt\\\
                        test_files/english/clinton_s.txt\\\
                        test_files/english/demolitions.txt\\\
                        test_files/english/demolitions_s.txt\\\
                        test_files/english/dr.txt test_files/english/dr_s.txt\\\
                        test_files/english/dre.txt\\\
                        test_files/english/dre_s.txt\\\
                        test_files/english/duma.txt\\\
                        test_files/english/duma_s.txt\\\
                        test_files/english/ecig.txt\\\
                        test_files/english/ecig_s.txt\\\
                        test_files/english/ethicist.txt\\\
                        test_files/english/ethicist_s.txt\\\
                        test_files/english/fbi.txt\\\
                        test_files/english/fbi_s.txt\\\
                        test_files/english/foul_ball.txt\\\
                        test_files/english/foul_ball_s.txt\\\
                        test_files/english/iphone6s.txt\\\
                        test_files/english/iphone6s_s.txt\\\
                        test_files/english/kentucky.txt\\\
                        test_files/english/kentucky_s.txt\\\
                        test_files/english/kiss.txt\\\
                        test_files/english/kiss_s.txt\\\
                        test_files/english/lebanon.txt\\\
                        test_files/english/lebanon_s.txt\\\
                        test_files/english/markets.txt\\\
                        test_files/english/markets_s.txt\\\
                        test_files/english/nuns.txt\\\
                        test_files/english/nuns_s.txt\\\
                        test_files/english/nyfed.txt\\\
                        test_files/english/nyfed_s.txt\\\
                        test_files/english/punct.txt\\\
                        test_files/english/punct_s.txt\\\
                        test_files/english/qa.txt test_files/english/qa_s.txt\\\
                        test_files/english/quotes.txt\\\
                        test_files/english/quotes_s.txt\\\
                        test_files/english/self_reliance.txt\\\
                        test_files/english/self_reliance_s.txt

Name:           golang-gopkg-neurosnap-sentences-1
Release:        8%{?dist}
Summary:        A multilingual command line sentence tokenizer in Golang

License:        MIT
URL:            %{gourl}
Source:         %{gosource}

%description %{common_description}

%gopkg

%prep
test "%{source0_hash}" = "none" || { f="%{SOURCE0}"; test -f "$f" || { echo "oreon: missing Source0 $f" >&2; exit 1; }; h=$(sha256sum "$f" | awk '{print $1}'); test "$h" = "%{source0_hash}" || { echo "oreon: Source0 hash mismatch" >&2; exit 1; }; }

%goprep -A
find . -name "*.go" -exec sed -i "s|github.com/neurosnap/sentences|gopkg.in/neurosnap/sentences.v1|" "{}" +;
%autopatch -p1

%generate_buildrequires
%go_generate_buildrequires

%build
for cmd in cmd/* ; do
  %gobuild -o %{gobuilddir}/bin/$(basename $cmd) %{goipath}/$cmd
done

%install
%gopkginstall
install -m 0755 -vd                     %{buildroot}%{_bindir}
install -m 0755 -vp %{gobuilddir}/bin/* %{buildroot}%{_bindir}/

%if %{with check}
%check
%gocheck
%endif

%files
%license LICENSE.md
%doc CHANGES.md README.md test_files/english/anarchy.txt
%doc test_files/english/anarchy_s.txt test_files/english/carolyn.txt
%doc test_files/english/carolyn_s.txt test_files/english/clinton.txt
%doc test_files/english/clinton_s.txt test_files/english/demolitions.txt
%doc test_files/english/demolitions_s.txt test_files/english/dr.txt
%doc test_files/english/dr_s.txt test_files/english/dre.txt
%doc test_files/english/dre_s.txt test_files/english/duma.txt
%doc test_files/english/duma_s.txt test_files/english/ecig.txt
%doc test_files/english/ecig_s.txt test_files/english/ethicist.txt
%doc test_files/english/ethicist_s.txt test_files/english/fbi.txt
%doc test_files/english/fbi_s.txt test_files/english/foul_ball.txt
%doc test_files/english/foul_ball_s.txt test_files/english/iphone6s.txt
%doc test_files/english/iphone6s_s.txt test_files/english/kentucky.txt
%doc test_files/english/kentucky_s.txt test_files/english/kiss.txt
%doc test_files/english/kiss_s.txt test_files/english/lebanon.txt
%doc test_files/english/lebanon_s.txt test_files/english/markets.txt
%doc test_files/english/markets_s.txt test_files/english/nuns.txt
%doc test_files/english/nuns_s.txt test_files/english/nyfed.txt
%doc test_files/english/nyfed_s.txt test_files/english/punct.txt
%doc test_files/english/punct_s.txt test_files/english/qa.txt
%doc test_files/english/qa_s.txt test_files/english/quotes.txt
%doc test_files/english/quotes_s.txt test_files/english/self_reliance.txt
%doc test_files/english/self_reliance_s.txt
%{_bindir}/*

%gopkgfiles

%changelog
%autochangelog
