%global source0_hash 5c3d1316e90ffec6ac0b56601147136e767daf4efbd94d669b747e1c3cb54714

# Generated by go2rpm
%bcond check 0
%global debug_package %{nil}

%global debug_package %{nil}

# https://github.com/Masterminds/semver
%global goipath         github.com/Masterminds/semver
Version:                3.5.0

%gometa

%global goaltipaths     github.com/Masterminds/semver/v3

%global common_description %{expand:
The semver package provides the ability to work with Semantic Versions in Go.
Specifically it provides the ability to:

 - Parse semantic versions
 - Sort semantic versions
 - Check if a semantic version fits within a set of constraints
 - Optionally work with a v prefix}

%global golicenses      LICENSE.txt
%global godocs          CHANGELOG.md README.md

%global gosupfiles glide.lock glide.yaml

Name:           %{goname}
Release:        %autorelease
Summary:        Work with semantic versions in Go

License:        MIT
URL:            %{gourl}
Source0:        %{gosource}
Source1:        glide.yaml
Source2:        glide.lock

%description
%{common_description}

%gopkg

%prep
test "%{source0_hash}" = "none" || { f="%{SOURCE0}"; test -f "$f" || { echo "oreon: missing Source0 $f" >&2; exit 1; }; h=$(sha256sum "$f" | awk '{print $1}'); test "$h" = "%{source0_hash}" || { echo "oreon: Source0 hash mismatch" >&2; exit 1; }; }

%goprep
cp %{S:1} %{S:2} .

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog
%autochangelog
