GL:     "BioF" \
        rss-glx-biof -r \n\
GL:     "Busy Spheres" \
        rss-glx-busyspheres -r \n\
GL:     "Colorfire" \
        rss-glx-colorfire -r \n\
GL:     "Cyclone" \
        rss-glx-cyclone -r \n\
GL:     "Drempels" \
        rss-glx-drempels -r \n\
GL:     "Euphoria" \
        rss-glx-euphoria -r \n\
GL:     "Feedback" \
        rss-glx-feedback -r \n\
GL:     "Fieldlines" \
        rss-glx-fieldlines -r \n\
GL:     "Flocks" \
        rss-glx-flocks -r \n\
GL:     "Flux" \
        rss-glx-flux -r \n\
GL:     "Helios" \
        rss-glx-helios -r \n\
GL:     "Hufo's Smoke" \
        rss-glx-hufo_smoke -r \n\
GL:     "Hufo's Tunnel" \
        rss-glx-hufo_tunnel -r \n\
GL:     "Hyperspace" \
        rss-glx-hyperspace -r \n\
GL:     "Lattice" \
        rss-glx-lattice -r \n\
GL:     "Lorenz" \
        rss-glx-lorenz -r \n\
GL:     "Pixel City" \
        rss-glx-pixelcity -r \n\
GL:     "Plasma" \
        rss-glx-plasma -r \n\
GL:     "Skyrocket (silent)" \
        rss-glx-skyrocket -v 0 -r \n\
GL:     "Skyrocket" \
        rss-glx-skyrocket -r \n\
GL:     "Solarwinds" \
        rss-glx-solarwinds -r \n\
GL:     "SpirographX" \
        rss-glx-spirographx -r \n\
GL:     "Sundancer2" \
        rss-glx-sundancer2 -r \n\
GL:     "Matrix" \
        rss-glx-matrixview -r \n\
