%global source0_hash 0d99ddaf19153a22cba223f6301760156abf0f14e7fdfec49435cba84e178dc3

# Generated by go2rpm 1.9.0
%bcond check 0
%global debug_package %{nil}

# https://github.com/AzureAD/microsoft-authentication-library-for-go
%global goipath         github.com/AzureAD/microsoft-authentication-library-for-go
Version:                1.0.0

%gometa -f

%global common_description %{expand:
The MSAL library for Go is part of the Microsoft identity platform for
developers (formerly named Azure AD) v2.0. It enables you to acquire security
tokens to call protected APIs. It uses industry standard OAuth2 and OpenID
Connect.}

%global golicenses      LICENSE
%global godocs          CODE_OF_CONDUCT.md CONTRIBUTING.md SECURITY.md\\\
                        changelog.md RELEASES.md README.md

Name:           %{goname}
Release:        %autorelease
Summary:        The MSAL library for Go

License:        MIT
URL:            %{gourl}
Source:         %{gosource}

%description %{common_description}

%gopkg

%prep
test "%{source0_hash}" = "none" || { f="%{SOURCE0}"; test -f "$f" || { echo "oreon: missing Source0 $f" >&2; exit 1; }; h=$(sha256sum "$f" | awk '{print $1}'); test "$h" = "%{source0_hash}" || { echo "oreon: Source0 hash mismatch" >&2; exit 1; }; }

%goprep
%autopatch -p1

%generate_buildrequires
%go_generate_buildrequires

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog
%autochangelog
