.TH MRS_TOOLS-CONJUGATE "1" "November 2023" "" "User Commands"
.SH NAME
.B mrs_tools\ conjugate
\(en Conjugate data to correct phase/frequency convention in a NIfTI-MRS file
.SH SYNOPSIS
.B mrs_tools\ conjugate
.RB [ \-h ]
.B \-\-file\ \fIFILE
.RB [ \-\-output\ \fIOUTPUT ]
.RB [ \-\-filename\ \fIFILENAME ]
.SH OPTIONS
.SS "OPTIONAL\ ARGUMENTS"
.TP
.B \-h\fR,\ \fB\-\-help
Show a help message and exit.
.TP
.B \-\-output\ \fIOUTPUT
Output folder (defaults to current directory).
.TP
.B \-\-filename\ \fIFILENAME
Override output file names.
.SS "REQUIRED\ ARGUMENTS"
.TP
.B \-\-file\ \fIFILE
File to conjugage.
.SH "SEE ALSO"
.BR mrs_tools (1)
.P
.BR mrs_tools\-info (1),
.BR mrs_tools\-vis (1),
.BR mrs_tools\-merge (1),
.BR mrs_tools\-split (1),
.BR mrs_tools\-reorder (1),
.BR mrs_tools\-reshape (1)
.\" .BR mrs_tools\-conjugate (1)
