.TH MRS_TOOLS-VIS "1" "November 2023" "" "User Commands"
.SH NAME
.B mrs_tools\ vis
\(en Quick visualisation of a NIfTI-MRS file or FSL-MRS basis set
.SH SYNOPSIS
.B mrs_tools\ vis
.RB [ \-h ]
.RB [ \-\-ppmlim\ \fILOW\fR\ \fIHIGH ]
.RB [ \-\-mask\ \fIMASK ]
.RB [ \-\-save\ \fISAVE ]
.RB [ \-\-display_dim\ \fIDISPLAY_DIM ]
.RB [ \-\-no_mean ]
.I FILE\fR\ or\ \fIDIR
.RI [ FILE\fR\ or\ list\ of\ \fIFILE\fRs ...]
.SH OPTIONS
.SS "POSITIONAL\ ARGUMENTS"
.TP
.I FILE\fR\ or\ \fIDIR
NIfTI file or directory of basis sets
.SS "OPTIONAL\ ARGUMENTS"
.TP
.B \-h\fR,\ \fB\-\-help
Show a help message and exit.
.TP
.B \-\-ppmlim\ \fILOW\fR\ \fIHIGH
Limit the fit to a freq range
.RB (default= (.2,4.2) ).
.TP
.B \-\-mask\ \fIMASK
Mask for MRSI.
.TP
.B \-\-save\ \fISAVE
Save fig to path.
.TP
.B \-\-display_dim\ \fIDISPLAY_DIM
NIFTI-MRS tag.
Do not average across this dimension.
.TP
.B \-\-no_mean
Do not plot the mean signal line in the case of multiple spectra.
.SH "SEE ALSO"
.BR mrs_tools (1)
.P
.BR mrs_tools\-info (1),
.\" .BR mrs_tools\-vis (1),
.BR mrs_tools\-merge (1),
.BR mrs_tools\-split (1),
.BR mrs_tools\-reorder (1),
.BR mrs_tools\-reshape (1),
.BR mrs_tools\-conjugate (1)
